### ISSUE TITLE
Enable backwards navigation using "Backspace" key as before.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#540] opened 2018-07-08 16:49 UTC
Not being able to use "Backspace" key to navigate backwards is making keyboard navigation extremely difficult. "Alt+Left arrow" is not intuitive at all and even if one knew the key combo, it still takes two keys instead of one to go back.

**Comment by stsdc** [comment] 2018-07-08 16:55
Duplicate of #291, #388 and #436

**Closed** 2018-07-08 20:10 UTC
Labels: Status: Duplicate
