### ISSUE TITLE
Auto mount drives on startup

### ISSUE THREAD

**Issue by kmoj86** [elementary/files#729] opened 2018-11-02 15:52 UTC
**issue: second hard drive doesn't mount unless I open Files app and click on it.**

**suggestion: add an option to auto mount a specific drive when the OS starts.**

hello,
I have two HDDs on my machine. I'd like to have access to both of them first thing when the OS boots up.
right now, when the OS starts, the only mounted drive is the one where the OS is installed. the other drive isn't mounted and apps don't have access to it unless I manually launch Files app and click on the drive to let it mount.
I use the second drive for different things (Gdrive files, Steam library ... etc) and not having access to it at boot up is making these apps not reach any files (i.e. Steam llibrary reverts back to the old default location and I have to mount the drive then add the new library manually in steam every time).

**Comment by jeremypw** [comment] 2018-11-04 11:56
If you want drives to automount without running Files then it needs to be handled at the system level.  There are some 3rd party utilities available I believe although a volume manager plug in Settings is an idea you could put forward.

**Comment by kmoj86** [comment] 2018-11-04 15:43
@jeremypw 
I only created the issue here because a lot of other file managers have this feature available. so I thought it would be great if Files had it too.
whether the option would be available in settings or in Files is not an issue, I just think it should be something that is supported by the OS itself and not by using 3rd party utility.

**Comment by jeremypw** [comment] 2018-11-04 17:40
I do not know whether other file managers actually handle this or whether it is the underlying system. It is possible they do as some run in the background all the time (eg Nautilus) but Files does not do so at the moment as it does not, by design, handle the desktop.  I agree that 3rd party utilities are only a workaround.

**Comment by kmoj86** [comment] 2018-11-04 17:55
@jeremypw should I reopen this in elementary/switchboard ?

**Comment by peteruithoven** [comment] 2018-11-05 02:17
Some older conversations on this:
https://bugs.launchpad.net/elementaryos/+bug/1262270
https://bugs.launchpad.net/pantheon-files/+bug/1094669

One interesting seeming Stack Exchange question with 2 answers:
https://elementaryos.stackexchange.com/questions/605/is-there-a-way-to-mount-another-partition-on-startup
If it's simply a matter of editing this file we wouldn't need a daemon perse?

**Comment by jeremypw** [comment] 2018-11-05 17:08
As I understand it, the wish is not to mount on startup (which can be done by editing fstab) but to automount on plugging in a drive (not necessarily known in advance).

**Comment by kmoj86** [comment] 2018-11-05 17:40
mounting on startup is what I'm looking for. a simple switch or option that I can tick to make my second HDD mount on startup every time. this is what I'm primarily looking for instead of editing fstab. after all elementary is all about the user experience and avoiding the terminal as much as possible.

now about the automount when a flash drive is plugged in, that is another highly requested feature from what I saw. I would like to see that as well. it's intuitive and, again, improves the user experience.

**Comment by jeremypw** [comment] 2018-11-06 15:04
@kmoj86 :  If you want to mount certain drives (which are already plugged in) on startup then you need to edit /etc/fstab.  You can find the procedure online e.g. https://community.linuxmint.com/tutorial/view/1513.

Mounting on startup is not a Files issue so I will close this now.

**Closed by jeremypw** 2018-11-06 15:04 UTC
Labels: Status: Out of Scope
