### ISSUE TITLE
No information when I can't mount a drive

### ISSUE THREAD

**Issue by gorghino** [elementary/files#204] opened 2017-11-09 10:08 UTC
If for some reason I cannot mount a drive (i.e. it's an exfat partition and I don't have exfat support installed, it's a Windows partition that is locked, etc.), I do not get any information as to why I cannot mount it and Files silently fails.

**Comment by jeremypw** [comment] 2017-11-09 12:35
Thank you for reporting this issue.

I assume you are referring to clicking on one of the device entries in the sidebar?

If this fails to mount the device the there should normally be a message appearing in the view, with a reason.  I'll try to reproduce the ccircumstance you mentioned.

Try running Files in the terminal with the --debug flag.  This should give more information of what is happening when it tries to mount the device.  If you could post the relevant lines here it may help.

**Comment by jeremypw** [comment] 2017-11-09 16:57
OK, thanks - that helps a lot.  The UX team will have to decide which is the preferred way to inform the user in these circumstances - I guess a message in the view.

**Comment by danrabbit** [comment] 2017-11-09 17:12
Ah yeah probably throw an error dialog since it looks like there’s some useful copy there about what the error is (Windows is in hibernate mode and it’s unsafe to mount the drive) and how to resolve it (Boot back in to Windows and do a full shut down)

**Comment by jeremypw** [comment] 2017-11-09 17:29
OK, that's easier than alternatives.

**Comment by gorghino** [comment] 2017-11-09 17:36
@jeremypw I don't have io.elementary.pantheon-files but only 
```
gorgo@dago:~$ io
io.elementary.appcenter   io.elementary.calculator  ionice    
```

I used` pantheon-files ` to debug.
Linux 4.4.0-98-generic (even if its boot is buggy - check stackexchange) but tried also 4.4.0-97...
OS 0.4.1 Loki
GTK+ 3.18.9

**Comment by jeremypw** [comment] 2017-11-09 17:50
Sorry - I meant io.elementary.files.  I think it is only in unstable repo at the moment.

Just pushed a fix for this.

**Closed** 2017-11-25 18:20 UTC
Labels: Status: Confirmed, Status: In Progress
