### ISSUE TITLE
Set custom icon on folder

### ISSUE THREAD

**Issue by Djaler** [elementary/files#392] opened 2018-03-25 16:55 UTC
For example, I have some cool icon in elementary style for dropbox folder. And I want to set it to dropbox folder. But I can't. Yeah, I can make Dropbox folder one on xdg directories and override icon, but it's a crutch.

**Comment by jeremypw** [comment] 2018-03-26 15:34
It would be necessary to decide where to store the custom icons. see https://gitlab.gnome.org/GNOME/nautilus/issues/196.

**Comment by micahilbery** [comment] 2018-03-26 15:37
Could we not store the custom icons in `~/.local/share/icons/`?

**Comment by jeremypw** [comment] 2018-03-26 15:44
That is one possibility.

**Comment by Djaler** [comment] 2018-03-26 16:01
Another question is where to store info about directory icon. Maybe in hidden file inside the directory? This way it works in dolphin (kde)

**Comment by jeremypw** [comment] 2018-03-26 17:08
Another possibility is to use a custom file attribute (metadata) - this is the way Files stores the preferred sort column and order for the folder.

**Comment by Djaler** [comment] 2018-03-26 17:08
Oh, I didn't know about this feature. Yeah, this would be better solution

**Comment by aljelly** [comment] 2018-03-27 01:22
Isn't this a duplicate of #171?

**Comment by jeremypw** [comment] 2018-03-27 09:06
Hmm, yes you're right.

**Closed** 2018-04-06 19:40 UTC
Labels: Status: Duplicate
