### ISSUE TITLE
"Open in Terminal" does not open terminal in the folder if the path to it has a space

### ISSUE THREAD

**Issue by teamcons** [elementary/files#2490] opened 2024-09-29 14:00 UTC
### What Happened?

I have a HDD with a name including a space. And a few folders with spaces in the name

Whenever i do "open in terminal" in any folder where there is a space in the name at any point of the absolute path
(ex: /home/teamcons/a folder with spaces/whatever

The new terminal will just default to opening in $HOME

### Steps to Reproduce

-create a folder whose name include blank spaces (any amount)
-open folder
-right-click, "open in terminal"
-terminal shows up. Witness $PWD

### Expected Behavior

terminal opens with $PWD being the working directory for which i clicked on "open in terminal"

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
nothing alas
```

**Comment by jeremypw** [comment] 2024-10-01 09:49
Probably related to #664?  There is a PR to fix that (#2268) being worked on - may be able to ifix this issue there too.

**Comment by jeremypw** [comment] 2024-10-01 10:04
Actually, this is a duplicate of https://github.com/elementary/terminal/issues/775,  which is being addressed by https://github.com/elementary/terminal/pull/777

**Comment by jeremypw** [comment] 2024-10-01 10:06
Closing as the issue needs fixing in Terminal, not Files.

**Closed by jeremypw** 2024-10-01 10:06 UTC
