### ISSUE TITLE
Open in folder (firefox) opens Files successfully but with the filename in the pathbar

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/files#239] opened 2017-11-20 18:58 UTC
I don't know whether this is problem with Files or Firefox, but when I hit show in folder in downloads, this happens:
![image](https://user-images.githubusercontent.com/20795161/33035920-cf71a3e8-ce52-11e7-98f9-5bbcdcb81e0e.png)

**Comment by jeremypw** [comment] 2017-11-20 19:02
This PR: https://github.com/elementary/files/pull/201 is intended to fix problems opening certain files in their folder from FireFox.  Some filenames get garbled at the moment.

This report is a duplicate of issue #42.

**Comment by SubhadeepJasu** [comment] 2017-11-21 05:49
Good to see it is being fixed.

**Comment by pieplu** [comment] 2018-01-10 17:19
I have a similar problem, when the download folder name contain non ASCII char (Ex, un french: `Téléchargements`), it cannot open the folder and repace `é` by an encoded value.

**Comment by jeremypw** [comment] 2018-01-10 17:52
The fix merged at 493e5d59b1aa773d663b3644bcd8a7917fdd84ce should have fixed this.  I created a download folder with an è character in the name and downloaded a file into it using Firefox.  Opening this with the Firefox "Open in Containing Folder" option worked fine.  Can you suggest a publicly available file with problematic characters in the filename  that I can try out?

**Comment by jlnr** [comment] 2018-05-07 12:54
I am using a recent build of Files, and showing downloads from Firefox works. However, there's still a little glitch because the filename should not be a part of the navigation bar:

![screenshot von 2018-05-07 14 48 38 2x](https://user-images.githubusercontent.com/70772/39702820-4cf31702-5206-11e8-8ae4-64dc6252528c.png)

It disappears from the navigation bar when I deselect the file.

**Closed** 2018-05-11 09:48 UTC
Labels: Status: Confirmed, Status: In Progress
