### ISSUE TITLE
Open in folder does not highlight (select) file

### ISSUE THREAD

**Issue by mosschief** [elementary/files#176] opened 2017-10-16 23:04 UTC
With many programs (including chrome) clicking 'open in folder' does not highlight (select) the file in the folder. In large folders this can be problematic as the user must look through the files in the folder to find it.

I would like to work on this issue myself. Does anyone have any hints about where to look to implement this?

**Comment by jeremypw** [comment] 2017-10-17 17:04
This is related to the implementation of the FIleManager1 DBus interface.  There are couple of in progress PRs relating to this (#72 & #88).   However, the problem probably is that at the moment you cannot launch FIles from the commandline with a parameter that is not a folder (that might be a regression) and you need to look at the creation of a new ViewContainer when passing a non folder parameter.  However, there is PR awaiting review that makes significant changes to ViewContainer and the parent tab and window (#154) so it may be better to wait for that to land.  I'll see whether a fix might be possible inside that PR.

**Comment by jeremypw** [comment] 2017-10-17 17:25
Ignore last remark re regression - I made a type when testing.  Current master does correctly open non-folder files from the commandline.

**Comment by jeremypw** [comment] 2017-10-17 17:30
Further testing shows that 'FIrefox' does cause the file to be selected when Files opens (because it correctly uses the FileManager1 interface).  However, with 'Chrome' the file is not selected so it must use a different way of launching Files.

**Comment by jeremypw** [comment] 2017-10-17 17:37
OK, so Chrome launches the file manager with the name of the parent folder so it is not surprising that the file is not selected!  A suspect the same reason applies to other programs but you would have to name them to confirm.  I am going to mark this as invalid as Files does implement the standard FIleManager1 interface and selects the file if that interface is used.

**Comment by jeremypw** [comment] 2023-06-25 12:11
Closing as it is marked "Out of Scope"

**Closed by jeremypw** 2023-06-25 12:11 UTC
Labels: Status: Out of Scope
