### ISSUE TITLE
Entire item in sidebar not clickable

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1626] opened 2021-03-11 23:45 UTC
## What Happened

I thought Files required me to click sidebar items several times to open things, but I found out the root cause: the entire item in the sidebar is not clickable.

![Screenshot from 2021-03-11 16-43-19](https://user-images.githubusercontent.com/611168/110870108-0e7aee80-8289-11eb-9e72-da5f83f68244.png)

Instead, only the middle area of each sidebar item is clickable, even though the entire item responds to :hover events.

## Expected Behavior

The entire item is clickable, edge-to-edge and top-to-bottom.

## Steps to Reproduce

1. Open Files
2. Hover over the edge of a sidebar item, noting that it's highlighted
3. Click! and nothing happens

## Platform Information

elementary OS 6 early access

**Comment by jeremypw** [comment] 2021-03-12 08:59
Looks like an unwanted margin of about 12px at the edges of the active area.  I guess I always click in the centre as I never noticed this!

**Comment by jeremypw** [comment] 2021-03-12 09:55
It seems that if you add an empty listbox row to a listbox you get a selectable by *not activatable* area about 12px high by default.  Not sure if this something to do with the implementation, css or what.

**Comment by hanaral** [comment] 2021-04-23 07:44
I can't tell if this is fixed or not, I think it is?(I can't reproduce it anymore, can anyone else attest?)

**Comment by jeremypw** [comment] 2021-04-23 07:55
I think this was fixed by https://github.com/elementary/files/pull/1628/files.

**Closed by jeremypw** 2021-04-23 07:55 UTC
Labels: Status: Confirmed
