### ISSUE TITLE
The address bar is not updated when the window reopens

### ISSUE THREAD

**Issue by X1lef** [elementary/files#963] opened 2019-06-11 00:40 UTC
When you have opened several tabs and you close the window and then re-open it, it keeps on the correct tab, but in the address bar the first tab path is shown.
Only by clicking on it will the address bar be updated with the currently active tab.

![program files](https://user-images.githubusercontent.com/22915450/59235450-543fea00-8bbf-11e9-8074-10da56b7afca.png)

*When I reopen the application I'm in the Music tab, which is where I left it the last time I used it, but the address bar shows the video path.*

**Comment by jeremypw** [comment] 2019-06-11 13:31
Thanks for the report. This is essentially a duplicate of #761 and a fix is currently awaiting someone to review and approve it (https://github.com/elementary/files/pull/762).

**Closed** 2020-01-04 02:21 UTC
Labels: Status: Duplicate
