### ISSUE TITLE
With multiple files selected, clicking the right mouse button deselects everything

### ISSUE THREAD

**Issue by wout** [elementary/files#2483] opened 2024-09-18 11:02 UTC
### What Happened?

It is now impossible to assign a colour or perform any other action in the contextual menu on multiple selected files.

### Steps to Reproduce

1. Select multiple files
2. Click the right mouse button
3. Selection is removed

### Expected Behavior

The selected files should remain selected

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

```
         eeeeeeeeeeeeeeeee            wout@Framey 
      eeeeeeeeeeeeeeeeeeeeeee         ----------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 7.1 Horus x86_64 
  eeee   eeeee       eee     eeee     Host: Laptop (12th Gen Intel Core) A8 
 eeee   eeee          eee     eeee    Kernel: 6.8.0-40-generic 
eee    eee            eee       eee   Uptime: 10 days, 23 hours, 36 mins 
eee   eee            eee        eee   Packages: 2822 (dpkg), 108 (flatpak), 16 (snap) 
ee    eee           eeee       eeee   Shell: bash 5.1.16 
ee    eee         eeeee      eeeeee   Resolution: 3000x2000 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: io.elementary.stylesheet.mint [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: 12th Gen Intel i7-1280P (20) @ 4.700GHz 
      eeeeeee         eeeeeee         GPU: Intel Alder Lake-P 
         eeeeeeeeeeeeeeeee            Memory: 21538MiB / 64010MiB 
```

**Comment by jeremypw** [comment] 2024-09-18 15:59
@wout Thanks for the report.  This appears to be a regression, possibly introduced while preparing for porting to Gtk4.  While we look into it, there are work rounds available: 
 - Use the Icon View
 - or use the `Menu` key to open the context menu.

**Comment by jeremypw** [comment] 2024-09-18 18:33
@wout I have located the cause of this issue and pushed a fix in the linked PR.  It should be available in the next release.  Thanks again for pointing this out.

**Comment by wout** [comment] 2024-09-18 18:41
Great! Thanks for the quick fix!

**Closed** 2024-10-07 18:30 UTC
Labels: Status: Confirmed, Regression
