### ISSUE TITLE
Highlight sidebar places while drag and drop.

### ISSUE THREAD

**Issue by queeup** [elementary/files#1969] opened 2021-12-31 06:45 UTC
### Problem

Small indicator icons is not enough while drag and drop to sidebar. (I added this line because of "Problem" box is mandatory.)

### Proposal

If I hover sidebar places (Downloads, Videos, etc.) with my cursor, it is highlighting. It's a good addition to have this same behavier while drag and drop.

### Prior Art (Optional)

![Ekran görüntüsü 2021-12-31 09-39-33](https://user-images.githubusercontent.com/87835/147807911-adbf4cea-2ff1-4e98-bc61-9e3ff7e06b7c.png)

**Comment by jeremypw** [comment] 2021-12-31 11:10
Yes, I think it is a good idea to highlight rows that are a drop target. Thanks.

**Comment by jeremypw** [comment] 2022-01-01 18:59
Having looked at the code, the sidebar rows should be highlighted and if Files is run with the Adwaita theme for example then they are.  So it looks like this issue is actually a stylesheet one.

**Comment by jeremypw** [comment] 2022-01-01 19:00
Could one of the design team transfer this issue to the stylesheet project please? I do not have the rights to do this.

**Comment by queeup** [comment] 2022-02-10 15:50
Any news?

**Comment by jeremypw** [comment] 2022-02-10 18:39
I think this report may be a duplicate of #1915?

**Closed** 2022-05-18 22:23 UTC
Labels: Status: Confirmed
