### ISSUE TITLE
Copying multiple files throws an error

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#598] opened 2018-08-12 19:38 UTC
If I try to copy and paste multiple files as once (by rubber-band selecting or Ctrl+A or similar), I get an error that makes it look like all of the filenames are being concatenated:

>Error when getting information for file “/home/cassidyjames/Projects/elementary/stylesheet/README.mdfile:/home/cassidyjames/Projects/elementary/stylesheet/package.jsonfile:/home/cassidyjames/Projects/elementary/stylesheet/index.themefile:/home/cassidyjames/Projects/elementary/stylesheet/COPYINGfile:/home/cassidyjames/Projects/elementary/stylesheet/CONTRIBUTORSfile:/home/cassidyjames/Projects/elementary/stylesheet/CODE_OF_CONDUCT.mdfile:/home/cassidyjames/Projects/elementary/stylesheet/AUTHORSfile:/home/cassidyjames/Projects/elementary/stylesheet/plankfile:/home/cassidyjames/Projects/elementary/stylesheet/gtk-3.0file:/home/cassidyjames/Projects/elementary/stylesheet/gtk-2.0”: No such file or directory

Copying each file one-at-a-time works fine.

**Comment by danrabbit** [comment] 2018-08-12 19:40
Duplicate of #583 :)

**Closed by danrabbit** 2018-08-12 19:40 UTC
Labels: Priority: Critical
