### ISSUE TITLE
Use admin:/// for administrator operations

### ISSUE THREAD

**Issue by donadigo** [elementary/files#363] opened 2018-03-14 20:34 UTC
It turns out that you can do admin operations on files or any other process if you use the `admin:///` URI scheme instead of the `file:///` one. In this case we should make all the context menu entries in root protected directories enabled and use this URI to allow the user to perform wanted operations.

**Comment by mdh34** [comment] 2018-03-31 20:08
at the moment, putting `admin://` into the address bar of files and authenticating allows most standard procedures like renaming, deleting etc. A few things i noticed were that permissions aren't available, and copying files creates a file owned by the current user rather than root.

**Comment by danrabbit** [comment] 2020-01-04 03:29
Closing as a duplicate of #165

**Closed by danrabbit** 2020-01-04 03:29 UTC
Labels: Status: Confirmed
