### ISSUE TITLE
Large unknown files causes flicker on mouse hover

### ISSUE THREAD

**Issue by therocco** [elementary/files#887] opened 2019-02-13 19:11 UTC
I noticed that with one of the recent updates if you are browsing a folder that has unknown file types in it that have a file size greater than 500MB that the icons will flicker between a hover/focus and unfocused visual state when you hover over any item in that folder when using the `View as Grid` (CTRL+1) layout view. 

I apologize for lack of logging data. I tried running in debug mode to see if I could gather any log data but none was displayed in the console. I hope the above description will be sufficient enough to reproduce and test.

**Comment by jeremypw** [comment] 2019-02-13 19:48
This may be a duplicate of #883, which is fixed in master but not yet released.  But if it only occurs with with very large files it may be a separate bug - I'll check.

**Closed** 2023-01-23 18:01 UTC
