### ISSUE TITLE
Unable to add bookmark directly below home folder entry

### ISSUE THREAD

**Issue by mcclurgm** [elementary/files#1819] opened 2021-08-28 22:47 UTC
## What Happened

I recently deleted the Documents bookmark in the sidebar. I am unable to add it back by dragging the folder from my home folder into the sidebar. When I try, I receive an error that says "Error while creating link to Documents: the target doesn't support symbolic links." 

I haven't tried other standard folders, since I'm worried that I won't be able to get them back either.

I've confirmed that I can add other folders (ones that I've created myself, so they're not standard, like `Downloads/Temporary`) to the sidebar.

## Expected Behavior

I should be able to (re-)create a bookmark for this directory.

## Steps to Reproduce

1. Right-click on the Documents bookmark in the sidebar (with the documents icon) and click Remove
2. Go to the home folder
3. Drag the Documents folder into the sidebar to create a bookmark
4. Error will appear

### Logs

These are the log entries that appeared after I started dragging:
```
** (io.elementary.files:3947): DEBUG: 16:44:49.638: DndHandler.vala:284: DNDHANDLER selection data is uri list returning true
** (io.elementary.files:3947): DEBUG: 16:44:49.862: DndHandler.vala:284: DNDHANDLER selection data is uri list returning true
** (io.elementary.files:3947): DEBUG: 16:44:52.532: DndHandler.vala:284: DNDHANDLER selection data is uri list returning true
** (io.elementary.files:3947): DEBUG: 16:44:52.538: Directory.vala:1130: found cached dir file:///home/michael
```

## Platform Information

Odin 6.0 stable (up to date as of 8/28/21). Latest release.

**Comment by mcclurgm** [comment] 2021-08-28 22:52
I did a little more experimenting, and I found that if I try to drag a folder into the sidebar that's already a custom bookmark, I see the same error message. Based on this, it seems plausible that Files thinks there's an existing Documents bookmark, even though there isn't one in the UI.

**Comment by jeremypw** [comment] 2021-08-30 08:22
As a work round you should probably be able to get the bookmark back by editing `~/.config/gtk+3.0/bookmarks` and adding back the Documents entry (assuming there isn't already one).  I'll see whether I can reproduce your issue.

**Comment by jeremypw** [comment] 2021-08-30 08:27
Hmm, after a quick test with the master version, I could not reproduce the issue - I had no problem deleting and re-adding the bookmarks by various methods.  There haven't been any relevant commits since release of version 6.0.2

**Comment by jeremypw** [comment] 2021-08-30 08:28
You are right that Files intentionally does not permit duplicate bookmarks.

**Comment by mcclurgm** [comment] 2021-08-30 15:56
Ok, I just realized the issue is completely different from what I thought. I mixed it up because of a behavioral quirk of how I was trying to re-add the bookmark.

The actual culprit is that you can't add a bookmark to the first position in the sidebar, directly below the home folder bookmark and above any other bookmarks. When I add anything there, it shows this error. When I try to add to the spot below the first custom bookmark, it works fine.

I always have my Documents folder in the first position, so I tried to drag it in there and when it failed, decided it must be something about a well-known folder, not the position I dragged it to. I got it back by dragging it to a different position and then rearranging.

**Comment by jeremypw** [comment] 2021-08-31 08:47
This is because the `Home`, `Recent` and `Trash` bookmarks are created as "pinned" i.e. they cannot be moved or removed.  Not sure whether "Recent" needs to be pinned though.

**Comment by jeremypw** [comment] 2021-08-31 08:52
I note that in Nautilus, *all* the xdg dirs are pinned (and appear in a different section).

**Comment by jeremypw** [comment] 2021-08-31 15:22
Before changing things, it would be good to get UX team confirmation as to which of the bookmarks in the sidebar should be (i) immovable (pinned) and/or (ii) undeletable (permanent).

**Comment by mcclurgm** [comment] 2021-09-25 18:56
Thinking about this some more, there should be a way to fix the original issue I had without any real design changes. The issue is that if I try to drag and drop a folder to the first bookmark spot, it seems to not allow me to add one there. Instead it only tries to drop it into the "Recents" folder. For example:

![dnd-example](https://user-images.githubusercontent.com/29022469/134783099-25b01d68-2984-4edd-962b-2ff104fa9fc5.png)

This would drop it into a location that's not pinned, replacing `Dokumente` as the first item in the user-customizable list. I would expect this to work, no matter if we change the pinned directories to be in their own section. So if we can get the first item in the list to allow dropping, that would mostly fix this.

There's also a related issue where the revealers show "drop here to make a bookmark" lines when dropping a folder in invalid locations, for example between Home and Recents or after Trash. If the fix for that would be separate, I can open a new issue report there.

**Comment by jeremypw** [comment] 2021-09-26 11:18
Yes, there is something not quite right here.  You should be able to create a bookmark immediately after "Recent" since that does not involve moving it.  I'll try to fix that.

**Closed** 2021-11-23 22:00 UTC
Labels: Needs Design
