### ISSUE TITLE
[column view] Can't rename folder on pressing F2

### ISSUE THREAD

**Issue by artemanufrij** [elementary/files#134] opened 2017-09-16 14:34 UTC
it's not possible to rename a folder in column view by pressing F2. renaming a file works as expected.

**Comment by jeremypw** [comment] 2017-09-16 17:54
I can rename a folder with F2 as long as it selected (blue).

**Comment by jeremypw** [comment] 2017-09-18 15:59
Is it possible to narrow down more precisely the circumstances under which folders are not renamable?

**Comment by jeremypw** [comment] 2018-02-11 17:27
Closing as not reproduced and no further feedback.

**Comment by mridulganga** [comment] 2018-04-23 17:11
I can confirm this. Even if the folder is selected, on pressing F2 Nothing happens.
This happens only in column view.

**Comment by mridulganga** [comment] 2018-04-23 17:32
I am using the Daily Builds on a Ubuntu 18.04 Beta version.
I dont think this is a problem with the system though. Maybe I don't have the latest updates.

**Comment by jeremypw** [comment] 2018-04-23 17:42
OK, thanks.  Have you changed any of the default settings?  I assume the context menu rename works OK?  I don't think any recent commits directly involved rename.

**Comment by mridulganga** [comment] 2018-04-23 17:43
No I didnt change any Settings related to Panthon-Files.
Ya the context menu rename works fine.

**Comment by jeremypw** [comment] 2018-04-23 17:47
OK. thanks.  I just managed to get it to be unresponsive in column view (in double-click mode) - but I cannot reproduce it!  May be a weird race condition depending hardware speed. NB if the cursor is grey then the view does not have focus and F2 will not work but I guess that is not your problem.

**Comment by jeremypw** [comment] 2018-04-23 17:51
Just found another bug in Column View :-(  In some cases the column gets stuck in "working" mode (spinner on tab).  This also inhibits renaming.

**Comment by mridulganga** [comment] 2018-04-23 17:52
I am using Single Click Mode as of Now. Maybe that shifts the focus to the next column and so the rename doesnt work. It works with files because no new Column opens.

Oh yaa I fotgot to tell about the working mode bug.

**Comment by jeremypw** [comment] 2018-04-23 17:55
I'll open a new report for the "stuck working" bug.

**Comment by mridulganga** [comment] 2018-04-23 17:56
Yaa sure, I think that the Column view Rename thing can be safely ignored. Its not really a bug.

**Comment by jeremypw** [comment] 2018-04-23 17:59
OK, I'll close this again.  If someone wants to raise an issue suggesting that keyboard focus should not shift to new column they can, but I think that is the desired behaviour.

**Closed by jeremypw** 2018-04-23 17:59 UTC
Labels: Status: Incomplete
