### ISSUE TITLE
The sidebar border cannot decide between white & a dark color

### ISSUE THREAD

**Issue by jlnr** [elementary/files#646] opened 2018-10-08 10:05 UTC
Depending on which part of the app I am hovering over with the mouse, the line that separates the sidebar from the content changes from white to a dark grey, and back.

![whiteline](https://user-images.githubusercontent.com/70772/46603104-5f072400-caf2-11e8-8d19-19a956d58e7a.png)
![darkline](https://user-images.githubusercontent.com/70772/46603107-5f072400-caf2-11e8-9af8-e1fb8d586c68.png)

**Comment by jeremypw** [comment] 2018-10-08 14:44
Not seeing this on my install at the moment; possibly a HPaned theme issue?

**Comment by jlnr** [comment] 2018-10-08 14:46
I assume the darker line is the correct one? It mostly switches to white when I move around in the sidebar.

Also, this is on a LoDPI setup. I am not sure whether the "pixel-doubled" HiDPI mode is affected.

**Comment by jeremypw** [comment] 2018-10-08 14:54
Yes, on my install the line is always dark grey and I also have a LoDPI screen.  I haved tried focusing and hovering various widgets.

**Comment by danila-io** [comment] 2018-11-30 14:43
I have the same issue, it also occurs in other apps such as Music, Calendar and Code. LoDPI as well (1920x1080 - Nvidia GTX1060). 

It didn't happen on Loki.

**Comment by peteruithoven** [comment] 2018-11-30 15:02
That many people experience the issue doesn't really help though, if the developers can't reproduce it they can't really fix it. 
Please help us find a way to predictably reproduce the issue. 

For the people who experience this issue:
- What happens when you restart Files?
- What happens when you reboot?
- Do you have a Nvidia card?
- Does this start happening after the computer was suspended? 
- Does it only happen on LoDPI screens? (1x scale)
- Does it happen consistently? Does the same color consistently appear when hovering over specific areas?

**Comment by tkashkin** [comment] 2018-11-30 18:07
It seems to be not Files-specific bug. It also occurs in any app using `Gtk.Paned` widget. See #617.

Looks like it's either stylesheet bug or GTK bug that occurs on Nvidia.

* Nothing changes when Files (or any other app with this bug) is restarted.
* Nothing changes after reboot.
* I can reproduce this on Nvidia (1070, laptop with 1050), can't reproduce on Intel graphics.
* No, it happens even without suspend.
* Haven't tested with HiDPI.
* Yes, it happens consistently in any app with `Gtk.Paned` widget.

**Comment by peteruithoven** [comment] 2018-11-30 18:38
Thanks, looks like this is a duplicate of #617

**Closed by peteruithoven** 2018-11-30 18:38 UTC
Labels: Not reproducible
