### ISSUE TITLE
Merging folders/overwriting files freezes or crashes Files

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1771] opened 2021-07-27 18:20 UTC
## What Happened

I was copying a bunch of files off a flash drive that had been backed up. Since some folder names were the same, I was prompted to merge the folders which I did. Shortly thereafter, Files completely froze up. Repeating it on another machine yielded the same result.

## Expected Behavior

Files doesn't freeze up when copying/merging/overwriting files. :)

## Steps to Reproduce

1. Copy a collection of files onto a flash drive, e.g. your ~/ directory
2. Copy those files back to your machine
3. Choose to merge folders when prompted

## Platform Information

Odin RC

**Comment by jeremypw** [comment] 2021-07-28 10:30
I tried this with a folder containing a small number of files and it merged with no issue.  Is this perhaps an efficiency issue?  If you are merging your whole home directory that could be a very large number of files. I havent checked the code yet but this might involve a large number of comparisons or a lot of undo data.  Need to check how the operation scales.

**Comment by jeremypw** [comment] 2021-07-28 10:31
Anyway, the operation should be async and not freeze the interface.

**Comment by jeremypw** [comment] 2021-07-28 10:37
Just tried it with a more demanding folder containing a deep subfolder tree and Files crashed so this issue is confirmed.

**Comment by jeremypw** [comment] 2021-07-28 11:02
After reinstalling Files from master (I am not sure development branch I had installed at the time) I can confirm that File freezes, not crashes.  However, it was not consuming cpu so must be waiting for a timeout for some fileoperation I guess.

**Comment by jeremypw** [comment] 2021-07-28 11:18
I have now got a crash again merging into a local folder rather than an external flash drive.

The backtrace was:
```
Thread 28 "pool-io.element" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffae7fc700 (LWP 8849)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6aa4859 in __GI_abort () at abort.c:79
#2  0x00007ffff6b0f3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6c39285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff6b1747c in malloc_printerr (str=str@entry=0x7ffff6c3b200 "mremap_chunk(): invalid pointer") at malloc.c:5347
#4  0x00007ffff6b177ec in mremap_chunk (p=p@entry=0x7ffff7a65b30, new_size=new_size@entry=64) at malloc.c:2858
#5  0x00007ffff6b1d0f0 in __GI___libc_realloc (oldmem=0x7ffff7a65b40, bytes=52) at malloc.c:3206
#6  0x00007ffff7dd9f40 in g_realloc () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7451ed4 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff7452210 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff7450d21 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff73f9b79 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff7d3c526 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7d3e378 in g_object_new_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7d3e6cd in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff746ecf8 in gtk_dialog_add_button () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff7eff927 in files_file_conflict_dialog_constructorPython Exception <class 'gdb.error'> No type named TypeNode.: 
 (type=, n_construct_properties=8, construct_properties=0x55555613e400) at ../libcore/FileConflictDialog.vala:190
#16 0x00007ffff7d3c26c in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7d3e378 in g_object_new_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7d3e6cd in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7efcdff in files_file_conflict_dialog_constructPython Exception <class 'gdb.error'> No type named TypeNode.: 
 (object_type=, parent=0x555555a96370, _source=0x555555816380, _destination=0x5555557fd300, _dest_dir=0x5555557eeb80) at ../libcore/FileConflictDialog.vala:60
#20 0x00007ffff7efd20a in files_file_conflict_dialog_new (parent=0x555555a96370, _source=0x555555816380, _destination=0x5555557fd300, _dest_dir=0x5555557eeb80) at ../libcore/FileConflictDialog.vala:59
#21 0x00007ffff7f37f3f in pf_run_conflict_dialog
    (parent_window=0x555555a96370, time=0x555556142b80, info=0x555556086e30, src=0x555555816380, dest=0x5555557fd300, dest_dir=0x5555557eeb80, new_name=0x7fffae7fb658, apply_to_all=0x7fffae7fb61c)
    at ../libcore/FileOperations/DialogUtils.vala:150
#22 0x00007ffff7f3f78e in copy_move_file
    (copy_job=0x555556002130, src=0x555555816380, dest_dir=0x5555557eeb80, same_fs=0, unique_names=0, dest_fs_type=0x7fffae7fb7e0, source_info=0x7fffae7fbb10, transfer_info=0x7fffae7fbb30, debuting_files=0x0, overwrite=0, skipped_file=0x7fffae7fb7c8, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:2897
#23 0x00007ffff7f3dcf9 in copy_move_directory
   Python Exception <class 'gdb.error'> There is no member named keys.: 
 (copy_job=0x555556002130, src=0x5555558564e0, dest=0x7fffae7fb918, same_fs=0, create_dest=0, parent_dest_fs_type=0x7fffae7fba80, source_info=0x7fffae7fbb10, transfer_info=0x7fffae7fbb30, debuting_files=0x555555c234c0, skipped_file=0x7fffae7fba6c, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:2187
#24 0x00007ffff7f3fe58 in copy_move_file
   Python Exception <class 'gdb.error'> There is no member named keys.: 
 (copy_job=0x555556002130, src=0x5555558564e0, dest_dir=0x555555817880, same_fs=0, unique_names=0, dest_fs_type=0x7fffae7fba80, source_info=0x7fffae7fbb10, transfer_info=0x7fffae7fbb30, debuting_files=0x555555c234c0, overwrite=1, skipped_file=0x7fffae7fba6c, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:3034
#25 0x00007ffff7f402de in copy_files (job=0x555556002130, dest_fs_id=0x7fff9402e5c0 "l2051", source_info=0x7fffae7fbb10, transfer_info=0x7fffae7fbb30) at ../libcore/marlin-file-operations.c:3152
#26 0x00007ffff7f40530 in copy_job (task=0x555556140d80, source_object=0x0, task_data=0x555556002130, cancellable=0x0) at ../libcore/marlin-file-operations.c:3228
#27
```

**Comment by jeremypw** [comment] 2021-07-28 11:19
The crash does not occur if you tick "Apply to all" whenever a dialog appears.

**Comment by jeremypw** [comment] 2021-07-28 11:23
@tintou Could you look into this when you have time - it seems to be associated with repeated showing of the FileConflict dialog.

**Comment by jeremypw** [comment] 2021-07-28 14:30
I got this backtrace when Files froze:
```
Thread 9 (Thread 0x7fffe153c700 (LWP 11258)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff7e20623 in g_cond_wait () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7dd02c5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7dd3758 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7f3708c in pf_run_conflict_dialog (parent_window=0x55555596c370, time=0x555555fbd7e0, info=0x555556012580, src=0x55555585cda0, dest=0x555555865120, dest_dir=0x55555581ae20, new_name=0x7fffe153b388, apply_to_all=0x7fffe153b34c) at ../libcore/FileOperations/DialogUtils.vala:177
#5  0x00007ffff7f3e815 in copy_move_file (copy_job=0x555555e950b0, src=0x55555585cda0, dest_dir=0x55555581ae20, same_fs=0, unique_names=0, dest_fs_type=0x7fffe153b510, source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30, debuting_files=0x0, overwrite=0, skipped_file=0x7fffe153b4f8, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:2897
#6  0x00007ffff7f3cd80 in copy_move_directory (copy_job=0x555555e950b0, src=0x555555863360, dest=0x7fffe153b648, same_fs=0, create_dest=0, parent_dest_fs_type=0x7fffe153b7e0, source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30, debuting_files=0x0, skipped_file=0x7fffe153b7c8, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:2187
#7  0x00007ffff7f3eedf in copy_move_file (copy_job=0x555555e950b0, src=0x555555863360, dest_dir=0x5555558579a0, same_fs=0, unique_names=0, dest_fs_type=0x7fffe153b7e0, source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30, debuting_files=0x0, overwrite=1, skipped_file=0x7fffe153b7c8, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:3034
#8  0x00007ffff7f3cd80 in copy_move_directory (copy_job=0x555555e950b0, src=0x555555827c00, dest=0x7fffe153b918, same_fs=0, create_dest=0, parent_dest_fs_type=0x7fffe153ba80, source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30, debuting_files=Python Exception <class 'gdb.error'> There is no member named keys.: 
0x555555ea2580, skipped_file=0x7fffe153ba6c, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:2187
#9  0x00007ffff7f3eedf in copy_move_file (copy_job=0x555555e950b0, src=0x555555827c00, dest_dir=0x5555558186c0, same_fs=0, unique_names=0, dest_fs_type=0x7fffe153ba80, source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30, debuting_files=Python Exception <class 'gdb.error'> There is no member named keys.: 
0x555555ea2580, overwrite=1, skipped_file=0x7fffe153ba6c, readonly_source_fs=0) at ../libcore/marlin-file-operations.c:3034
#10 0x00007ffff7f3f365 in copy_files (job=0x555555e950b0, dest_fs_id=0x7fffc80017b0 "l2051", source_info=0x7fffe153bb10, transfer_info=0x7fffe153bb30) at ../libcore/marlin-file-operations.c:3152
#11 0x00007ffff7f3f5b7 in copy_job (task=0x555555dc74b0, source_object=0x0, task_data=0x555555e950b0, cancellable=0x0) at ../libcore/marlin-file-operations.c:3228
#12 0x00007ffff7bf5c62 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007ffff7dfd374 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff7dfcad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6a37609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#16 0x00007ffff6ba0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Closed** 2021-07-29 06:38 UTC
Labels: Priority: Critical
