### ISSUE TITLE
Performance issue and high CPU usage

### ISSUE THREAD

**Issue by codygarver** [elementary/files#162] opened 2017-10-12 10:43 UTC
When using Pantheon-files, the CPU usage is generelly high. Comparing to PCMan, it's about 10 percent-point higher. Also, resizing is very slow in Pantheon-files, the window always lags way behind the cursor, while it's very snappy in PCMan file browser.

Output from terminal gives this:

runej@runej-Aspire-5750:/var/lib/apt$ pantheon-files
[_LOG_LEVEL_INFO 04:06:22.648780] Application.vala:155: Files version: 0.2.0
[_LOG_LEVEL_INFO 04:06:22.648841] Application.vala:157: Kernel version: 3.13.0-40-generic
[_LOG_LEVEL_WARN 04:06:22.651571] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-CQYdIAyWEr: Connection refused
[_LOG_LEVEL_INFO 04:06:22.682395] Application.vala:84: Report any issues/bugs you might find to http://bugs.launchpad.net/pantheon-files
[_LOG_LEVEL_INFO 04:06:23.055054] gof-callwhenready.vala:79: call when ready OK - empty list

I have same issues with other built in APPs, which makes me think it *could* be a GTK issue. In addition the responsiveness when clicking on a button varies a lot, but in generel in the built in APPs are quite long compared to third parties.

Fx. Firefox is very snappy as well is FileZilla, while Maya and update manager is not.

Bounty: https://www.bountysource.com/issues/6625223-performance-issue-and-high-cpu-usage

**Comment by jeremypw** [comment] 2017-10-12 11:20
The difference in window resizing is mainly in the IconView especially with folders containing a large number of files.  I suspect it is due to use of Gtk.IconView rather than a custom widget.

**Comment by jeremypw** [comment] 2018-05-20 11:52
I find the speed of window resize is now comparable to Nautilus so I am not sure this is still an issue.  Therefore marking incomplete.  Need a more precise definition of the target in order gain the bounty.

**Comment by dennismayr** [comment] 2019-02-05 23:44
Scrolling and window resizing is slow, visible redraw flicker.
CPU usage oscillates between 25% and 65%.

This, coupled with Ubuntu's 4.15 kernel power regression that causes Intel 1st-gen i5 CPUs to run 15°C to 20°C hotter than kernel 4.4 (like back in Loki / xenial), makes up for a pretty hot laptop.

**Comment by jeremypw** [comment] 2019-02-06 10:58
@dennismayr : Are the figures you quote relating to Icon VIew or List View or is there no difference? How may files are in the viewed folder?  For my home directory, with an 4 year old i5 laptop, I find overall CPU usage around 10 -15% (i.e around 50% of one of the four cores) when resizing, with minimal lag (comparable to another similar file manager).  It is known that scrolling and resizing very large icon views (10,000s of files) is slow - due to the use of the native Gtk.IconView widget.  Use of a more efficient custom widget is being considered. 

Note that there was a bug in the color tag plugin in release 4.1.4 that caused excessive continuous cpu usage and flickering.  A fix was merged 3 days ago. If you have not received that update then a workround is to use the "Hide Local Thumbnails" option.

**Comment by dennismayr** [comment] 2019-02-06 11:05
Hi Jeremy!

This happens in Icon View -haven't tried list view yet-, the CPU activity is seen oscillating  in htop.
The directories don't hold more than 100 files / directories. 

Scrolling is especially laggy (as if you were using as CPU 2 generations older); resizing lag/flicker is comparatively unimportant.

I'll check for updates today and/or try your workaround suggestion.

**Comment by dennismayr** [comment] 2019-09-23 23:22
After several eOS updates this year, the problem isn't visible on my side anymore.

**Comment by jeremypw** [comment] 2023-03-08 14:35
Closing as too generic, there are several more specific performance related issues open.

**Closed by jeremypw** 2023-03-08 14:35 UTC
Labels: Status: Incomplete, Priority: Low, Bounty
