### ISSUE TITLE
Set double click for folders as default

### ISSUE THREAD

**Issue by HollowedEmpire** [elementary/files#1892] opened 2021-11-13 16:36 UTC
### Problem

Being virtually the only OS to use single click folders as a default, with the additional resistance to add an option to change this at the risk of 'making things more confusing', the default should be to double click a folder instead of single click.

### Proposal

Virtually all computer users are accustomed to the decades old standard that you double click a folder to open it. The current single click method makes in near impossible to actually highlight a folder for management, since trying to select the folder instead opens it. It is unfriendly user design that will make it significantly harder for a new user to know how to actually highlight a folder for such purposes. This immediately goes against elementary OS's philosophy to be "easy and simple".  It also gives any other computer user a very abrasive entrance by needing to get over decades of learned standards in order to do basic file management.

The argument for 'because you single click web links' does not hold up as you do not need to manage web links the way you manage files on a computer. You do not need to highlight a weblink to alter properties of it, put it in a grouping for file management, or any other such actions. There is a reason double clicking a folder has become a standard across nearly all operating systems.

The argument for 'making it easier for a user who's never used a computer before' does not hold up either. How is a person who's never used a computer before supposed to actually find and install elementary OS in the first place? That entire process requires significant prior computer knowledge... of which they will likely be using an OS that has double click as a standard, which then will confuse them coming to elementary OS. And if a new user did somehow use elementary OS before any other OS, you are simply setting them up for failure as if they try to use any other OS they will have major issues doing basic file management.

Since there is a very, very strong resistance to allowing a simple option for this, the only solution is to set double clicking a folder as the new default.

Much like Blender's previous push to use right click as the primary mouse button ultimately getting reverted (though to be fair they provided an option to set left or right click), elementary OS must also get passed the need to be different with the folder clicking in order to be the simple OS it desires to be.

(Edited to be much clearer and fixed some grammar issues. Sorry, was in a distracting environment at the time of writing.)

**Comment by danrabbit** [comment] 2021-11-16 20:06
Gonna close this as a duplicate of the discussion here: https://github.com/elementary/files/discussions/1877

**Closed by danrabbit** 2021-11-16 20:06 UTC
Labels: Needs Design
