### ISSUE TITLE
Copying thousands of files from a ext4-formatted flash drive freezes Files

### ISSUE THREAD

**Issue by seanballais** [elementary/files#1516] opened 2020-11-08 10:53 UTC
## What Happened
I tried copying thousands of files from my `ext4`-formatted USB flash drive to my PC. I'm copying 26,695 files to be exact. The total file size is less than 8 GB. After a while, the progress bar in the copy dialog in Files will stop, and the app itself will freeze, only copying a portion of the thousands of files I wanted to copy. I have to copy the files using `cp`.

## Expected Behavior
Normally, I expected Files to not freeze and copy all files successfully.

## Steps to Reproduce

1. Have an `ext4`-formatted USB flash drive with thousands of files of mixed sizes.
2. Copy the files to your PC.

## Platform Information
**Version:** 5.1.7 Hera (Built on Ubuntu 18.04.4 LTS)
**Kernel Version:** 5.4.0-52-generic
**GTK Version:** 3.22.30

**CPU:** Intel Core i5-7400 (3.00 GHz)
**GPU:** NVIDIA GeForce GTX 1050 Ti (Driver: NVIDIA Linux Driver Version 450.80.02)
**RAM:** 8 GB
**Storage:**
  * **SSD (Mount Point: `/`):** 120 GB
  * **HDD (Mount Point: `/home`):** 500 GB

**Comment by jeremypw** [comment] 2020-11-08 13:29
Sounds like a duplicate of #1484 and may also be related to #1386.  There have been a number of fixes related to file copying/progress indication since the last stable release which will hopefully improve the situation.  Unfortunately the latest Files no longer runs on elementary 5.1.7 as it needs libraries not available on that version so a new stable release will have to wait until the release of elementary 6.  Files has never been that good at handling very large numbers of files - I would recommend a specialist app like `grsync` for this.  Also, at the moment, it is best to close and reopen Files between significant files operations.

**Closed** 2020-11-08 13:29 UTC
Labels: Status: Duplicate

**Comment by seanballais** [comment] 2020-11-08 13:31
@jeremypw, I see. Thanks!
