### ISSUE TITLE
Global hot key configuration

### ISSUE THREAD

**Issue by douglasheld2** [elementary/files#2445] opened 2024-06-18 22:16 UTC
### Problem

As a MacOS user with Apple hardware, I would like to use ElementaryOS utilizing the muscle memory of my familiar keystrokes ⌘C, ⌘V, ⌘W, ⌘Q etc., 

### Proposal

I played with the keyboard configuration and liked the variety of keystrokes that I could program. But, pressing the left ⌘ key to bring up the global keystrokes reminder was not something that I could reconfigure or remap.

I think it would be really nice to make a one-stop configuration to enable a number of familiar keystrokes, namely:

- ⌘C for copy in any app that allows copy to the clipboard
- ⌘X for cut in any app that allows cut to the clipboard
- ⌘V for paste from the clipboard in any app that allows paste
- ⌘T for opening and focusing on a new tab (in any tabbed app) 
- ⌘W to close a tab in any tabbed application, or to close the app window otherwise
- ⌘Q to close all windows of the focused app
- ⌘R in any app that allows a refresh
- ⌘P to invoke print for any app that supports a print command

The existing keystrokes reminder pane could still be displayed, simply any time an unrecognized modifier-key combination is entered.

### Prior Art (Optional)

I do not know that this has ever been attempted for a Linux GUI. I find it a little discouraging in fact, to try to decode what Super, Meta and Hyper actually mean on a keyboard where I have an Apple `⌘` or a `Windows key`, or an `Alt-Gr` etc.

**Comment by danirabbit** [comment] 2024-06-18 22:55
Hey thanks for your issue report! I'm going to close it as a duplicate of https://github.com/elementary/switchboard-plug-keyboard/issues/69 however

You can change the behavior of pressing the super key alone in System Settings → Keyboard → Layout. There's a dropdown with the label "⌘ key behvaior"

In all of elementary OS you'll see either the ⌘ symbol or the word "Super" which depending on your keyboard is "⌘", the Windows symbol, or the word "Super". We don't use the words "Meta" or "Hyper" in any of our apps or their shortcuts

**Closed by danirabbit** 2024-06-18 22:55 UTC
