### ISSUE TITLE
Missing previews for files on the Network

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#541] opened 2018-07-09 04:26 UTC
Files on the internal network lack previews. There is even no option to turn it on as the Files app has no toggleable settings whatsoever. 

![screenshot from 2018-07-09 09-52-15](https://user-images.githubusercontent.com/22585732/42430677-4e3cff04-835e-11e8-92cc-86001d226df6.png)

**Comment by jeremypw** [comment] 2018-07-09 09:09
Duplicate of #438

**Closed by jeremypw** 2018-07-09 09:09 UTC
Labels: Status: Design Conflict, Status: Duplicate
