### ISSUE TITLE
Software "File" freezes opening a folder with many files inside

### ISSUE THREAD

**Issue by Satelliteo** [elementary/files#2180] opened 2023-05-01 19:46 UTC
### What Happened?

I have a folder with more than 14.000 small files (.zip) in it. 
When I try to open it with "Files" it freezes. 
If I wait a LONG time (like 1 minute) it opens it, but before it opens I get the message "Files is not responding, you may choose to wait a short while for the application to continue, or force it to quit entirely".

I've opened that folder with Dolphin on Kubuntu, with Nemo on Mint, So that means that there is not something wrong with the folder.

It seems like it have to index all the files before open it, so it takes a lot of time and resources.

### Steps to Reproduce

1. Open "Files" app
2. Click on the folder
3. Get it freeze

### Expected Behavior

I wanted the folder to open to check the files inside, it doesn't open.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![Cattura da 2023-05-01 21 44 49](https://user-images.githubusercontent.com/132300506/235518569-88d504a6-5e9e-435e-95f8-10f057572e53.png)
![Cattura da 2023-05-01 21 44 40](https://user-images.githubusercontent.com/132300506/235518578-9f357cd7-83b1-489a-9f05-707914a4a737.png)

**Comment by jeremypw** [comment] 2023-05-02 08:37
Thanks for the report, but this looks like a duplicate of #2172.   What kind of files does the problematic folder contain? Is it git folder or otherwise "special" (e.g. synced to NextCloud)?  I'll try to investigate whether there has been any slow down recently.

**Closed by jeremypw** 2023-05-02 08:37 UTC

**Comment by Satelliteo** [comment] 2023-05-02 10:32
Thanks for your answer.

The folder is in the main SSD disk and it contains anly .zip files (game roms that I play on Mame arcade simulator). 

The folder is about 70 GBite, and there are something like 14.400 zip files.

**Comment by jeremypw** [comment] 2023-05-03 19:26
@Satelliteo PR #2184 Makes a big difference in speed of loading large folders as the time is reduced from ~N^2 to ~N so a folder with 10^4 items loads about 100 times faster.
