### ISSUE TITLE
Can not access local network and remote locations

### ISSUE THREAD

**Issue by pauliusdunauskas** [elementary/files#510] opened 2018-05-24 20:38 UTC
Trying to access local network i'm getting an error message that can not mount location

Trying to connect to Server - error about gvfs package. But trying to install it i'm having dependency issues.
`sudo apt-get install gvfs-backends 
[sudo] password for paulius:     
   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gvfs-backends : Depends: gvfs (= 1.28.2-1ubuntu1~16.04.2) but 1:1.28.1-2salbabix27xenial is to be installed
                 Depends: gvfs-daemons (= 1.28.2-1ubuntu1~16.04.2)
                 Depends: gvfs-libs (= 1.28.2-1ubuntu1~16.04.2) but 1:1.28.1-2salbabix27xenial is to be installed
                 Depends: gvfs-common (= 1.28.2-1ubuntu1~16.04.2) but 1:1.28.1-2salbabix27xenial is to be installed
E: Unable to correct problems, you have held broken packages.
`

![screenshot from 2018-05-24 23 34 43](https://user-images.githubusercontent.com/19975221/40512426-7c48af00-5fab-11e8-928d-a82ae789bf04.png)
![screenshot from 2018-05-24 23 34 59](https://user-images.githubusercontent.com/19975221/40512427-7c6b6ca2-5fab-11e8-8d24-96b261e5951e.png)

**Comment by pauliusdunauskas** [comment] 2018-05-25 05:30
Looks like when removed all gvfs-* and reinstalled again - problem with error message dissapeared (error about gvfs installation).
but can not access network share

**Comment by jeremypw** [comment] 2018-05-25 13:59
Please give more information about which release of Elementary you are running and which version of Files.  You seem to be install gvfs from a ppa?  The appropriate package should already be installed if you are running a stable version of Elementary,

**Comment by pauliusdunauskas** [comment] 2018-05-28 19:03
Files 0.3.5
elementary OS 0.4.1 Loki
Built on "Ubuntu 16.04.3 LTS"
Linux 4.13.0-43-generic
GTK+ 3.18.9

**Comment by pauliusdunauskas** [comment] 2018-05-28 19:08
Here is a screenshot from today - something changed, but can not understand what.
![screenshot from 2018-05-28 22 05 34](https://user-images.githubusercontent.com/19975221/40626772-71352628-62c3-11e8-9bb9-68c66d367e18.png)

In case that you can be thinking of something changed on my network - no it's not. Other devices (Windows, TV and Phones) are accessing network folders without any isues.

**Comment by jeremypw** [comment] 2018-05-29 09:43
OK, thanks.  There does seem to have been a change affecting both Loki and Juno.  A Loki stable has not received and updates to Files for quite some time, it is probably due to something else.  It also seems to be affecting Nautilus.   I find that the entire Windows Network address (smb://) is no longer showing servers that used to show up (the servers have also been updated recently of course).  However, if the ip address of a particular server is entered in the pathbar (in the form smb://192.168.x.x) then I can connect without problem.  Also I can connect using the "Connect to Server" dialog after entering the server details and credentials.

Could be upstream changes to gvfs and/or samba??

**Comment by jeremypw** [comment] 2018-05-29 09:54
This seems to be the same bug reported for Ubuntu so it looks like it is upstream:

https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1767454

**Comment by artemanufrij** [comment] 2018-10-28 18:13
I don't know if this issue is the right place: Files doesn't show Servers inside "smb://" location. Loki did/does it (I have Loki on a second machine).
![screenshot von 2018-10-28 19 10 22](https://user-images.githubusercontent.com/16517095/47620007-47b1ca00-dae5-11e8-82de-1c0d86de05af.png)

**Comment by jeremypw** [comment] 2018-10-30 11:10
@artemanufrij : Can you connect using the Connect to Server dialog?  I can confirm that I cannot see SMB servers in the network:// view but I can connect to known ones using the dialog.  There seems to be a problem with discovery, which may be something to do with default smb.conf settings - I'll investigate.

**Comment by jeremypw** [comment] 2018-10-30 11:39
One fix for this problem can be found here:

https://forums.linuxmint.com/viewtopic.php?f=157&t=185410#p960482

It involves setting up a avahi-daemon service to handle samba share discovery.  Note. this only works for Linux/MacOS.   There are probably ways of configuring the network conventionally to handle all Samba servers.  You need to look at smb.conf files, DNS handling, hosts files etc.

I do not think this is a Files problem as such.

**Closed by jeremypw** 2018-10-30 11:39 UTC
Labels: Upstream

**Comment by jeremypw** [comment] 2018-10-30 11:41
Note: The avahi-daemon fix causes serves to show up in network:// but not in smb:// (Windows Network) view.
