### ISSUE TITLE
Expose keyboard shortcuts in context menu like the rest of the OS

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#945] opened 2019-05-14 14:24 UTC
I love the fact that elementary hints keyboard shortcuts on the Desktop interface.
![Screenshot from 2019-05-14 19-52-47](https://user-images.githubusercontent.com/22585732/57705669-e79a0400-7681-11e9-9af9-d44a78301a80.png)

If the same could be done for the Files app context menu, it would be so much easier and natural for new users to learn the shortcuts.
![Screenshot from 2019-05-14 19 37 17](https://user-images.githubusercontent.com/22585732/57705745-08faf000-7682-11e9-86c3-fba891131d89.png)

**Comment by peteruithoven** [comment] 2019-05-14 14:50
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/files/issues/697

**Closed by peteruithoven** 2019-05-14 14:50 UTC

**Comment by jeremypw** [comment] 2019-05-14 16:46
I don't disagree but should be decided and implemented on all app context menus.
