### ISSUE TITLE
Operating system theme-dependency

### ISSUE THREAD

**Issue by TheNewSound** [elementary/files#1473] opened 2020-09-13 01:25 UTC
I would like to note that this application has a dependency on a specific theme, the Elementary-OS themes (elementary/stylesheets). Using this application on plain Ubuntu causes non-critical bugs (UI bugs).

For example, functionality like color-buttons (for labeling folders) and progress bars (see how much free space % is available) do not work with ubuntu's yaru-light theme.

**Comment by danrabbit** [comment] 2020-09-13 01:30
This is not a bug. If you would like Yaru to support the style classes used by Files, please file an issue there.

Closing as "Out of Scope"

**Closed by danrabbit** 2020-09-13 01:30 UTC

**Comment by TheNewSound** [comment] 2020-09-13 01:49
Too bad this will not be fixed in the pantheon-files app itself. Gracefully handling missing dependencies is part of the application's scope in my opinion. Not OS-level theme shipment.
Would you be open to accept a PR handling this if the style dependency is missing (Elementary theme not selected as OS theme)?
