### ISSUE TITLE
rename looks bad on list and columns view with materia dark compact theme

### ISSUE THREAD

**Issue by xididri** [elementary/files#437] opened 2018-04-24 05:45 UTC
On right click > rename it seems an overlay is kept in view, resulting in 2 texts being displaying making it hard to read.

Easier to explain with pictures (original filename is horizontal-scroll.sh) :

- after clicking rename :

![screenshot from 2018-04-24 07-31-59](https://user-images.githubusercontent.com/18724661/39168068-b77f7d6e-4792-11e8-90c5-500436b0f22e.png)

- inputting some text :

![screenshot from 2018-04-24 07-32-36](https://user-images.githubusercontent.com/18724661/39168065-b735654e-4792-11e8-8993-3c82312e7a8f.png)

- after rename :

![screenshot from 2018-04-24 07-32-43](https://user-images.githubusercontent.com/18724661/39168064-b71ae160-4792-11e8-850e-b1e0d72998ee.png)

- pantheon-files from git source, commit 74b8c8880ff9e5380d1c1896b2e64266c7fd103e
- ubuntu 18.04 beta (had same bug with 17.10)
- gnome-shell v3.28.1
- gnome dark theme + materia GTK theme

**Comment by jeremypw** [comment] 2018-04-24 08:43
Thanks for the detailed report.  I notice your screenshots have a dark background - I have only used the default background (on Loki/Juno) and have not seen this issue. So I guess this may be a theme related bug.  There has been some UX discussion about changing the rename UX to use a native popover widget instead of a custom editable widget which I quess would be more tolerant of theme changes.  Elementary apps are only strictly speaking only intended to work on elementaryos. Some elementary apps have a dark theme either as default or as an option but at the moment, FIles is not one of them.  I'll see if there is a simple fix for this.

**Comment by monkeydri** [comment] 2019-05-02 08:49
Sorry for the bump but any update on this ? Can't leave my dark theme I like to work at nights !

**Comment by jeremypw** [comment] 2019-05-02 10:21
Sorry for the delay.  There has been some willingness to make Files dark-theme friendly recently (e.g. 9b6aa439ae917b78511d7c05b1247142cad828ae) so I will raise the priority of this.

**Comment by jeremypw** [comment] 2019-05-02 11:48
@monkeydri :  I cannot seem to reproduce this using the latest master - which version are you using?

**Comment by monkeydri** [comment] 2019-05-02 12:06
io.elementary.files --version => 4.1.7
I am on commit 45b3cd5e11
I will check with other dark themes and keep you updated here.

**Comment by monkeydri** [comment] 2019-05-02 12:28
for the record the related issue is here : https://github.com/nana-4/materia-theme/issues/345 (same issue on nemo actually)

**Comment by jeremypw** [comment] 2019-05-02 17:16
Probably worth leaving this open - Files should fall back to a sensible behaviour if the theme does not conform to expectations.

**Comment by jeremypw** [comment] 2023-10-31 16:59
Closing as Files now honors the system dark theme setting.

**Closed by jeremypw** 2023-10-31 16:59 UTC
Labels: Priority: Medium
