### ISSUE TITLE
Files wrong left column icons OS 7 stable!

### ISSUE THREAD

**Issue by fayjie92** [elementary/files#2126] opened 2023-02-02 18:43 UTC
### What Happened?

The Files app in elementary os 7 shows generic directory icons in the left column instead of the styled icons. This happens when the system starts or reboots. Closing the app and reopening (or refreshing) brings back the correct icons. This issue was mentioned before for os 6.1 and closed. But seems that it reappears in elementary os 7.
![Screenshot from 2023-02-02 19 31 29](https://user-images.githubusercontent.com/32283602/216418944-05fef3f6-b6b6-4f0c-97d9-64bb0f732909.png)

Check the icons for Documents, Music, Pictures, and Videos in the left column (Fig.)
Also, the cloud icon for remote directories is shown as a question mark.

### Steps to Reproduce

1. Boot the os 7.
2. Open the files app. 

### Expected Behavior

The styled icons instead of generic icons. 

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2023-02-02 19:03
This is a duplicate of #2105.  A fix for this was merged last December, but unfortunately this was after the last stable release.  I'll try to get a newer stable release out soon.

**Comment by fayjie92** [comment] 2023-02-03 01:50
Aah, okay. That would be great. Thanks for your reply @jeremypw .

**Comment by TomiOhl** [comment] 2023-02-06 21:23
This was fixed in 6.2.2, however, remote directories still revert to the question mark for me - see the two items above the trash:
![image](https://user-images.githubusercontent.com/6696659/217090866-0cb34647-8ef5-4bda-91e7-f55b5afc751a.png)
Feel like it's a different issue, but similar from the user's perspective. Let me know if I should open a new issue

**Comment by jeremypw** [comment] 2023-02-07 10:17
@TomiOhl Yes, please open a new issue and give details as the kind of uris that this affects.

**Comment by TomiOhl** [comment] 2023-02-07 19:40
Alright, opened #2129

**Comment by jeremypw** [comment] 2023-06-29 10:48
Closing as now fixed.

**Closed by jeremypw** 2023-06-29 10:48 UTC
Labels: Status: Duplicate
