### ISSUE TITLE
Missing File's icon

### ISSUE THREAD

**Issue by marcogiannini** [elementary/files#841] opened 2019-01-01 22:30 UTC
No icon of File after latest update
File version: 4.1.1+r3273+pkg74~ubuntu5.0.1
![schermata da 2019-01-01 23-26-29](https://user-images.githubusercontent.com/4943897/50576932-e4158700-0e1c-11e9-81c6-a5b4d5693d70.png)

**Comment by ryonakano** [comment] 2019-01-02 01:48
This is because a translator of the language you're using translated its icon name by mistake. However, as far as I confirmed now, [that string is not translated in any language](https://l10n.elementary.io/translate/files/extra/ja/?checksum=a87f72ffdd2ab41a#translations) (indeed some language has a string, but they are copy of original English string). So I think this issue will be fixed in the next release of Files.

**Comment by ryonakano** [comment] 2019-01-02 12:33
That's also because of unneeded translation (already reported at https://github.com/elementary/gala/issues/358)

**Comment by danrabbit** [comment] 2019-01-03 02:53
Closing since @ryonakano confirmed this is resolved in master

**Closed by danrabbit** 2019-01-03 02:53 UTC
