### ISSUE TITLE
Items stay in the "illuminated" state after deselecting

### ISSUE THREAD

**Issue by dar5hak** [elementary/files#535] opened 2018-07-05 17:19 UTC
Files version: 0.3.6
elementary OS version: Juno beta

Steps to reproduce:

1. Select one or more items using the check mark or the keyboard:

![screenshot from 2018-07-05 17-30-20](https://user-images.githubusercontent.com/8205055/42338381-2efb8cf6-8079-11e8-8363-9fcf0344310d.png)

Notice that the last selected item appears illuminated (same as the hover state)

2. Clear the selection either by clicking elsewhere or by pressing <kbd>ESC</kbd>.

![screenshot from 2018-07-05 17-31-38](https://user-images.githubusercontent.com/8205055/42338421-5198f7da-8079-11e8-84f1-e03ed6e00fb2.png)

The last selected item still stays illuminated.

This does not happen when the items are selected by dragging a rectangular area; only when the items are selected one by one.

**Comment by jeremypw** [comment] 2018-08-04 15:04
Changes are proposed to the styling of selected, focused, and hovered items which should fix this.

**Comment by jeremypw** [comment] 2023-06-25 16:04
Closing as the highlighting of the item is an indication of where the cursor is - e.g. if the RightArrow key is pressed then the item to the right of the highlighted item will become highlighted (and selected).  Highlighting is not intended to be an indication of selection state.

**Closed by jeremypw** 2023-06-25 16:04 UTC
Labels: Status: Out of Scope

**Comment by danirabbit** [comment] 2023-06-26 23:49
This is specifically a duplicate of #473
