### ISSUE TITLE
Receive assertion error when attempting to open a file

### ISSUE THREAD

**Issue by phase1geo** [elementary/files#600] opened 2018-08-15 15:44 UTC
From my application, I make the following code call:

```
/* Allows the user to choose an image file */
  public static string? choose_image_file( Gtk.Window parent ) {

    string? fname = null;

    FileChooserDialog dialog = new FileChooserDialog( _( "Select Image" ), parent, FileChooserAction.OPEN,
      _( "Cancel" ), ResponseType.CANCEL, _( "Select" ), ResponseType.ACCEPT );

    /* BMP */
    FileFilter filter = new FileFilter();
    filter.set_filter_name( _( "Images" ) );
    filter.add_pattern( "*.bmp" );
    filter.add_pattern( "*.png" );
    filter.add_pattern( "*.jpg" );
    filter.add_pattern( "*.jpeg" );
    dialog.add_filter( filter );

    if( dialog.run() == ResponseType.ACCEPT ) {
      fname = dialog.get_filename();
    }

    /* Close the dialog */
    dialog.destroy();

    return( fname );

  }
```

When I execute this function, I get the following assertion error:

`** (com.github.phase1geo.minder:1846): CRITICAL **: 10:24:38.214: marlin_view_chrome_basic_location_bar_real_set_display_path: assertion 'path != NULL' failed`

**Comment by jeremypw** [comment] 2018-08-15 16:40
I think PR #582 might fix this as well.  If you look at your settings with dconf-editor or otherwise is the 'last-folder-uri' setting an empty string?  Try changing it to a real folder and see if it fixes it.

**Comment by phase1geo** [comment] 2018-08-15 16:45
I opened up dconf-editor and browsed to /io/elementary/files/file-chooser. The last-folder-uri value is set to my home directory Downloads folder (file:///home/Trevor/Downloads), not an empty string.

**Comment by phase1geo** [comment] 2018-08-15 16:46
I forgot to mention that I am running Juno (latest updates applied).

**Comment by jeremypw** [comment] 2018-08-15 18:08
Thanks for the info.  Do you get the same message if you run io.elementary.code in the terminal and load a document using the filechooser there?  If not may be worth looking at their code.

**Comment by jeremypw** [comment] 2018-08-15 18:12
May also be worth looking at /org/gtk/settings/filechooser/last-folder-uri

**Comment by jeremypw** [comment] 2018-08-15 18:13
Does the app/filechooser crash or do you just get the message?

**Comment by phase1geo** [comment] 2018-08-15 18:16
I just get the message — the application stays running and otherwise seems to operate correctly. I do see that /org/gtk/settings/filechooser/last-folder-uri is set to the empty string. Additionally, if I run Code from terminal and attempt to open a file, I do see the same error message displayed in the shell.

**Comment by jeremypw** [comment] 2018-08-16 11:11
I cannot reproduce this exact by setting both the last-folder-uri settings to `''`, but the linked PR prevents the filechooser setting the display path to null so there is a good chance it will fix this issue.  I'll wait till that is merged and then ask whether it fixes things for you.

**Closed** 2018-10-08 15:00 UTC
