### ISSUE TITLE
Showing wrong disk/folder size on clicking properties on file system

### ISSUE THREAD

**Issue by knight-byte** [elementary/files#1381] opened 2020-06-27 10:29 UTC
**This is the issue : --**
![Screenshot from 2020-06-27 15-58-10](https://user-images.githubusercontent.com/54370855/85920171-19bef300-b88f-11ea-97f8-82df562c80d1.png)

I found this bug when i was just going though folders. when i opened the file system disk and check properties 
is was showing size as **140TB** and **18.4 EB** free out of **31.9 GB**.

**Comment by jeremypw** [comment] 2020-06-27 15:44
This is a duplicate of #1320

**Closed by jeremypw** 2020-06-27 15:44 UTC
