### ISSUE TITLE
Crashes when switching to ListView In RTL

### ISSUE THREAD

**Issue by donadigo** [elementary/files#232] opened 2017-11-16 22:53 UTC
1. Open Files in RTL mode (switch that in Gtk inspector)
2. Switch to list view from other mode.
3. Files crashes.

Here's the trace:
```
Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
0x00007ffff67a2860 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff67a2860 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#1  0x00007ffff67a31fb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff67a3214 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff67a3331 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff5a23c4f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff5a24d25 in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x0000000000455e7c in fm_abstract_directory_view_finalize ()
#7  0x00007ffff5a24d9a in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff67d3057 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff681aab0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff5a1ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff5a324de in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff5a3ad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff5a3b08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff6a1cb5a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff5a24d25 in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff4dc12fc in gof_abstract_slot_finalize () from /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0
#17 0x00007ffff5a24d9a in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x000000000045d33c in marlin_view_view_container_change_view_mode ()
#19 0x0000000000456762 in _marlin_view_window_action_view_mode_gsimple_action_activate_callback ()
#20 0x00007ffff5a1ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff5a31fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff5a3ad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff5a3b555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff54f029a in __lambda15_ () from /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0
#25 0x00007ffff54f037a in ___lambda15__granite_widgets_mode_button_mode_changed ()
   from /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0
#26 0x00007ffff5a230a7 in g_cclosure_marshal_VOID__OBJECTv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff5a201d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff5a3a9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff5a3b08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff7b8b88e in granite_widgets_mode_button_set_active () from /usr/lib/x86_64-linux-gnu/libgranite.so.4
#31 0x00007ffff7b8bcbe in granite_widgets_mode_button_set_selected () from /usr/lib/x86_64-linux-gnu/libgranite.so.4
#32 0x00007ffff5a1ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff5a31fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff5a3ad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff5a3b08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff69bf15d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff5a201d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
```

**Comment by jeremypw** [comment] 2017-11-17 16:16
Duplicate of #6.  Have you checked whether this occurs for you if you start Files in RTL mode with 
```
LANGUAGE=ar_DZ.UTF.8  io.elementary.files
```
rather than Gtk.Inspector? It doesnt for me

**Closed** 2017-12-28 19:02 UTC
Labels: Status: Duplicate
