### ISSUE TITLE
System breaks when drag/dropping certain folders, unable to click on anything

### ISSUE THREAD

**Issue by BlueDevil1998** [elementary/files#663] opened 2018-10-17 07:16 UTC
In the Elementary files app, whenever I try to move a folder from one place to another instead of moving it the folder gets duplicated which breaks the system and nothing can be clicked any longer. The system still works in the background (Notifications etc.) But the system has to be forcefully shutdown and restarted in order to regain access to the system. The cursor shows a small green plus next to it and it can be moved around but nothing can be clicked. I noticed this problem in the first beta release of Juno for the first time and it is still persistent in the final release. So far the only solution for me was to switch to a different files app.

**Comment by BlueDevil1998** [comment] 2018-10-17 08:14
So after diving a bit deeper into the issue, it appears that there is a specific kind of folder that causes this bug. I made a testfolder with a few different files and folders within, and the bug doesn' t occur there. So far i've only had it happening when i try to move a theme folder from the downloads folder to the terminal to copy it's exact path. Strangely enough after making sure that all of the permissions where set to the exact same as an user made folder the bug still persists in only the theme folder.

**Comment by jeremypw** [comment] 2018-10-17 15:42
So, does this only affect dragging and dropping theme folders to terminal?  This does not copy the folder, only its name.  Does it also happen with Copy/Paste?

If so, please amend the issue title accordingly.

I have not reproduced this so far with the current master version. Are you using Loki or Juno beta?

I did notice that with DnD the name was enclosed in single quotes whereas with Cut/Paste it was not.

**Comment by BlueDevil1998** [comment] 2018-10-17 16:53
It only happens when dragging the folder to a different destination whether this is the terminal or a different folder. Copy/Pasting doesn' t produce this bug so it is purely drag/dropping. I can' t drag/drop the folder to a different destination since this will trigger the bug. I can see in the folder that when drag/dropping occurs, a copy of the folder gets created in the source folder (in this case the Downloads folder) which leads me to believe that for some reason, instead of doing a drag/drop, a copy of the folder gets made instead. At first I thought it was my touchpad but using a mouse produces the same result.

**Comment by BlueDevil1998** [comment] 2018-10-17 16:55
Also i'm using the stable Juno release and not the beta or Loki. I can' t see anything unusual in the folder name or any of it' s content.

**Comment by BlueDevil1998** [comment] 2018-10-17 16:58
![schermafdruk van 2018-10-17 18 57 06](https://user-images.githubusercontent.com/44223671/47102994-7fe01f80-d23e-11e8-95ac-45d7bce14ed8.png)
This is what i see after restarting the system and checking the source folder

**Comment by jeremypw** [comment] 2018-10-17 17:41
This not the official elementary theme but that may not be relevant. Please advise if there is anything else non-standard about the install.  Files should look like: https://cdn-images-1.medium.com/max/1000/1*DzHGy_A0Mn3aQVO8BD4sYA.png in Juno.

Dragging and dropping into the same folder should create a link, not a renamed copy.  Dragging and dropping to any other folder on the same file system will move the folder not copy it.

Dragging and dropping folders from/to the themes folder (`/usr/share/themes`) to/from `~/Downloads` will fail unless you are running as administrator ( a dialog appears but no breakage).

Please give a precise example of something that triggers this bug.  If you can, run Files from a terminal window with the command `io.elementary.files` (after first closing any open Files window).  What terminal messages are given when the bug occurs?

When you say you cannot click on anything, does that include the sidebar, pathbar, modeswitch and history buttons?

**Comment by BlueDevil1998** [comment] 2018-10-17 18:32
Just ran Files in terminal. It shows no errors, and the bug appears to be gone. I can' t reproduce the bug anymore after running Files in terminal. So maybe running it there changes something. I noticed a few warnings the first time i ran files but i couldn' t reproduce the bug.

**Comment by jeremypw** [comment] 2018-10-18 15:36
Thanks for the update. I do not really have any suggestions as to what is happening here - I cannot reproduce it and it sounds very weird.  We will just have to wait and see whether anyone else has a similar problem.  Thanks for taking the trouble to report it anyway.

**Comment by apcamargo** [comment] 2018-10-19 04:34
I had the same issue twice today while dragging files into a folder. The only thing I could to was to reset the computer.

**Comment by jeremypw** [comment] 2018-10-19 09:21
Thanks for confirming this also affects you @apcamargo - I have now marked this as confirmed.  If you can identify any way to reliably reproduce this it would be helpful.  It is strange that Files manages to lock the whole system when dragging.  Does it happen when the drag passes over a particular widget/app/window?

**Comment by jeremypw** [comment] 2018-10-19 16:35
Was the destination directory in another tab or another Files window or another app?

**Comment by apcamargo** [comment] 2018-10-19 17:11
Same Files window. I was inside a directory with ~80 text files and an empty folder. I selected the files and tried to drag them into the folder.

**Comment by jeremypw** [comment] 2018-10-19 18:19
Still cannot reproduce.  I'll set it back to 'Not reproducible' for now.

**Comment by eth0OS** [comment] 2018-10-20 01:33
It happens to me all the time I try to drag'n'drop with the right button a file to the same folder

**Comment by apcamargo** [comment] 2018-10-20 02:58
It happened twice today again. The first time, I was dragging downloaded files into a folder inside the Downloads directory. In the second time, I was dragging a file into VSCode.

Maybe the problem is related to dragging, not Files.

**Comment by jeremypw** [comment] 2018-10-20 14:43
@eth0OS Thanks for the report.  Are you saying it happens every time when you drag any file into its own parent folder?   Under these circumstances you should get a context menu when you drop the file giving the options to link or cancel.  Does the problem occur before you drop - that is, before releasing the mouse button or as you release it?

**Comment by jeremypw** [comment] 2018-10-20 15:07
Which filesystem is in use?  Is it encrypted?

**Comment by nikitati** [comment] 2018-10-21 10:45
I have the exact same issue, happened several times today. Restaring gala did nothing, so only a reboot helps, unfortunatelly. I did not change standard file app by any means.

**Comment by jeremypw** [comment] 2018-10-21 12:07
@nikitati:  Thanks for your helpful report.  I have not been able to reproduce the problem yet using your instructions (doing a primary button drag).  However, I have now just got a similar freeze using a secondary button drag and hovering over the destination folder.  This happened when the drag icon showed a "copy" emblem (green plus) instead of the usual "ask" emblem.  I am not sure how this happened as I have not been able to repeat so far.

I did manage to get out of it by pressing Ctrl-Q to quit the application.

**Comment by apcamargo** [comment] 2018-10-21 18:05
It happened again today. One thing I can add is that the cursor is always this one:

**Comment by jeremypw** [comment] 2018-10-22 09:45
@apcamargo  Thanks. Yes, that what I find with the method given above.  Please try out the linked PR if you can to see whether it fixes things for you.

**Comment by eljefuri** [comment] 2018-10-23 05:30
Confirming this problem has happened to me numerous times as well. Same result as @apcamargo regarding the cursor.

**Comment by jeremypw** [comment] 2018-10-23 10:13
@eljefuri  The linked PR will fix the problem - please try it if you can!  It needs another elementary developer to review and approve before it can be merged however.

**Closed** 2018-10-23 12:36 UTC
Labels: Priority: Critical, Status: Confirmed, Status: In Progress

**Comment by apcamargo** [comment] 2019-04-14 14:31
A follow-up:

I don't think this issue has been solved. I've experienced it multiples times in different installations. Other people seem to be having it too (https://github.com/elementary/files/issues/890).
