### ISSUE TITLE
Then do you guys package as flatpak of Files?

### ISSUE THREAD

**Issue by KDGNOR** [elementary/files#1826] opened 2021-09-03 13:31 UTC
## Problem

so can install on other OS then elementaryOS-6 as Flatpak.
Are going be released at all as flatpak with year?

(I wait from 2019-2020... u start talk about AppCenter for All Camp...)

## Proposal

Elementary OS 7 or
Elementary OS 8 ?

## Prior Art

mabye going for never?

**Comment by cassidyjames** [comment] 2021-09-03 17:27
Please do not open duplicate issues; triaging new issues takes valuable time away from our contributors, and closed issues can still hold a discussion. Duplicate of #1825

**Closed by cassidyjames** 2021-09-03 17:27 UTC
