### ISSUE TITLE
[feature-request] Prompt password input to override pasting

### ISSUE THREAD

**Issue by johnneydc** [elementary/files#507] opened 2018-05-22 03:29 UTC
![image](https://user-images.githubusercontent.com/30046223/40340725-5215dbe4-5db3-11e8-9e22-68c67b47fbe2.png)

**Comment by jeremypw** [comment] 2018-05-22 10:17
Thanks for raising an issue.  This is essentially a duplicate of #165.

**Closed** 2018-06-01 18:31 UTC
Labels: Status: Duplicate
