### ISSUE TITLE
"File not found" when looking at a non-empty directory

### ISSUE THREAD

**Issue by inad9300** [elementary/files#339] opened 2018-02-17 13:36 UTC
Not sure exactly how I got to this state, but I got here:

![no_files](https://user-images.githubusercontent.com/3440331/36341487-46c6fa06-13ef-11e8-974e-9c624137934d.png)

Here is what I remember (probably not the *exact* actions). I was trying to move the folder X from Downloads to Software by cutting and pasting it with the keyboard. I cut it, I went to Software, I pasted it. I went back to Downloads and X was still there! I accessed it, it was empty. I went back, and Downloads was displaying the message you see on the screenshot.

Refreshing (Ctrl + R) doesn't fix it. Moving to a different folder (e.g. Documents) and coming back to Downloads doesn't fix it.

**Comment by jeremypw** [comment] 2018-02-17 17:58
Assuming your Downloads folder is in a local place, then when the folder was moved out of it then the display should have automatically updated, removing that folder from the view.  If not, then that is a regression.

If you entered that folder from the parent then presumably it was still in the directory cache (which could be due to it being displayed in another window or tab or due to another regression). When you reversed out of it, the normal behaviour is to select that folder in the parent view.  However if that view now realises that that file no longer exists you will get the message that you did. 

I am surprised Ctrl+R did not fix it - I guess that it is because it is not clearing the selection.  Moving to a different folder (using the same view) should definitely clear the selection.

I'll play around and try to reproduce - or if you can come up with a test procedure then please post.

**Comment by jeremypw** [comment] 2018-02-17 18:15
Preliminary tests on the current master using Icon View did not show any unusual behaviour - the view updated as expected when one of its children was deleted using the terminal or by using Ctrl-X / Ctrl-V to move to another folder.  It was possible to attempt to re-enter the missing folder by using the history buttons but that is not really a bug and an appropriate message was given.

Any more information as to how you arrived at this situation would be welcome.  Which view mode were you using?

**Comment by inad9300** [comment] 2018-02-22 21:48
I could not reproduce the issue again, sorry. In case this helps, the folder I was trying to move had appeared on my Downloads directory after uncompressing a zip file living in the same place, and they were both pretty big (around 1 GiB).

Regarding your last question, I was using the grid view.

**Comment by jeremypw** [comment] 2018-02-23 12:11
OK, thanks.  I'll leave this open for a while to see if anyone can confirm and provide a procedure to reproduce.  Maybe a rare timing issue causing a signal to get lost or ignored.

**Comment by jeremypw** [comment] 2018-05-19 09:32
Closing since no confirmation.

**Comment by solarkraft** [comment] 2019-02-24 15:38
I run into this issue every once in a while. Last (maybe every) time it was the Downloads folder. Switching around didn't help, but when I restarted it to open it in the terminal to see some logs (somehow `io.elementary.files -h` it closed all instances with `GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`, running it again showed the help text and then without the parameter it opened a new instance in the terminal) the issue was gone. 

![pantheon files 404](https://user-images.githubusercontent.com/1337470/53301390-9df40700-3852-11e9-8f78-ca1de6ca5550.png)

Maybe it has to do with the daemon?

**Comment by jeremypw** [comment] 2019-02-28 12:16
@solarkraft   Thanks for the additional info - I'll reopen the issue and try to reproduce.

**Comment by jeremypw** [comment] 2019-02-28 12:31
It is not immediately obvious how the daemon would be involved unless the item moved had a color tag?

Could you try completely uninstalling Files and check that all the plugins have been removed from `/usr/lib/x86_64-linux-gnu/io.elementary.files/plugins/core/`.  Kill the daemon, or log out and back in.  Then reinstall Files.  Maybe there is a mismatch between plugin versions and the main program version??

**Comment by jeremypw** [comment] 2019-02-28 12:35
If you can give any further info about how the file was moved I would be grateful.  i.e.
* Drag n Drop or Cut and Paste?
* Using one view and navigating (sidebar or history or
* Using two tabs or
* Using two windows

**Comment by jeremypw** [comment] 2023-10-31 16:53
Closing as outdated and not reproducible.  Please reopen if recurs in Horus.

**Closed by jeremypw** 2023-10-31 16:53 UTC
Labels: Status: Incomplete
