### ISSUE TITLE
Unraring a file with a password does not prompt for a password 

### ISSUE THREAD

**Issue by febrezo** [elementary/files#71] opened 2017-07-01 22:27 UTC
The unrar process is performed but the unzipped file is corrupted because the user has not been prompted for the password. This issue can be reproduced  when trying to extract the file using the context menu.

**Comment by matzipan** [comment] 2017-07-03 20:54
I belive this is not a bug with Files itself, since it does not do any uncompressing. Files calls the Gnome File Roller application through Contractor.

**Comment by matzipan** [comment] 2017-07-03 20:58
I am marking this as incomplete until you can give more info on this issue. 

Please check if extracting with the archive manager (File Roller) opens a password prompt. Then, please check if using the command line `file-roller --extract-here <your file here>` opens a password prompt.

If the first one doesn't work - it is a bug with File Roller. If only the second one doesn't work - it is a bug with the Files contract. If both work but Files doesn't, then this is a bug in Files.

**Comment by danrabbit** [comment] 2020-01-03 06:33
Closing since OP never replied and presumably this is an issue in File Roller

**Closed by danrabbit** 2020-01-03 06:33 UTC
Labels: Status: Incomplete
