### ISSUE TITLE
Files freezes if you try to move the window holding the back or the forward button

### ISSUE THREAD

**Issue by eth0OS** [elementary/files#672] opened 2018-10-19 18:39 UTC
Files freezes if you try to move the window holding the back of the forward button
Reproducible: Yes
Steps to reproduce:
Open Files
Enter any folder
Hold the back button and try to move the window
Files freezes
Only way to quit is to kill the process.

Thank you for your attention.

**Comment by apcamargo** [comment] 2018-10-20 03:09
Maybe a duplicate of #663

**Comment by jeremypw** [comment] 2018-10-20 15:13
There has to be some history so that holding the button down would normally produce a menu after a delay.  This bug occurs if the drag is started after the button being activated (dark grey circle) and the menu appearing.  Files freezes on releasing the mouse button.

**Closed** 2018-11-02 14:38 UTC
Labels: Priority: Medium, Status: In Progress
