### ISSUE TITLE
Open with selection is instantly forgotten

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#832] opened 2018-12-29 16:42 UTC
If I select an application to open images, it is instantly forgotten/overwritten wit the default application. See video:

https://my.mixtape.moe/ycqzam.webm

**Comment by citrusui** [comment] 2018-12-29 17:37
Seconding this issue, I can easily reproduce this. Files seems to be ignoring `xfg-open` for some reason. Extremely annoying! Unfortunately, there's no way to downgrade to the fixed version of Files from apt :disappointed:

**Comment by citrusui** [comment] 2018-12-29 17:57
Update: This appears to be the second side effect of https://github.com/elementary/files/commit/0e523cc4501e910c648d979c9932239c5ee6d45e (from issue #829). A fix is in the works on issue #830.

For now, you can download the latest stable release from [Launchpad](https://code.launchpad.net/~elementary-os/+archive/ubuntu/stable/+build/15548537). You will need to install all 6 packages for this to work.

**Comment by Gabriel-p** [comment] 2018-12-29 18:04
Thanks @citrusui but I'll wait for the fix to be implemented. I can live with the inconvenience for now.

**Comment by Gabriel-p** [comment] 2019-01-10 22:41
Seems to have been fixed by today's update.

**Comment by jeremypw** [comment] 2019-01-27 16:01
Closing as this is now fixed.

**Closed by jeremypw** 2019-01-27 16:01 UTC
