### ISSUE TITLE
No image previews in File Chooser Dialog?

### ISSUE THREAD

**Issue by ostov-larion** [elementary/files#2346] opened 2023-10-22 15:25 UTC
### Problem

eOS Hera had the ability to preview an image in File Chooser Dialog before loading it into the browser. eOS Horus does not have this feature. Is it possible to return it?

### Proposal

Preview of images in File Chooser Dialog as it was implemented in eOS Hera.

**Comment by jeremypw** [comment] 2023-10-23 16:34
Closing as a duplicate of #2008.

**Closed by jeremypw** 2023-10-23 16:34 UTC
Labels: Status: Duplicate
