### ISSUE TITLE
Update music icon in dark mode for better visibility

### ISSUE THREAD

**Issue by Lacplesis** [elementary/files#1954] opened 2021-12-22 20:57 UTC
### Problem

The current music icon looks fine on light mode, but once you switch to dark mode, it has far less contrast as compared to the other icons in Files.

### Proposal

Consider updating the icon with a color and value that would be more consistent with the other icons and easier to see at a glance (purple or orange maybe?). Also, consider making the stems of the notes wide enough to have the same color running vertically to make the icon read better. I've attached a screenshot of Pop OS's music icon as reference for the thickness.

### Prior Art (Optional)

![pop-os-icons](https://user-images.githubusercontent.com/88727658/147154186-33351f46-470e-4cb1-90b6-fedddde725cc.png)

**Comment by jeremypw** [comment] 2021-12-22 22:39
Thanks for reporting but this is a duplicate of elementary/icons#853.

**Closed by jeremypw** 2021-12-22 22:39 UTC
Labels: Status: Duplicate
