### ISSUE TITLE
By setting Terminal as a default file browser, the context menu "Open in Terminal" in Files do nothing

### ISSUE THREAD

**Issue by torikulhabib** [elementary/files#529] opened 2018-06-20 08:35 UTC
please help me.
can not open in terminal
![mpv-shot0001](https://user-images.githubusercontent.com/26135527/41647049-7be38d7e-749f-11e8-910e-47020888981f.jpg)

**Comment by ryonakano** [comment] 2018-06-20 09:41
![screenshot from 2018-06-20 18 30 46](https://user-images.githubusercontent.com/26003928/41650273-99f471e8-74b8-11e8-9921-73dc0c55729e.png)
@torikulhabib I can't confirm this issue. Are you using extension or something like that? I'm using Juno Daily like you, but there is no context menu like "Open in Terminal". Instead I can open in terminal from "Open in"→"Terminal", and this works well.

**Comment by ryonakano** [comment] 2018-06-21 11:28
Thank you telling me how to reproduce:) Maybe we should write down more details about this issue.

**Comment by ryonakano** [comment] 2018-06-21 11:34
## Actual Behavior

When we set Terminal as default file browser, the context menu "Open in terminal" in Files do nothing.

## Expected behavior

Terminal should appear when we click that context menu.

## Steps to reproduce this issue

1. Set Terminal as a default file manager
2. Open Files
3. Right-click any directory, file, or folder, then click "Open in Terminal"
4. Nothing happen

**Comment by ryonakano** [comment] 2018-06-21 11:56
If we **right-click any space** and select "Open in Terminal", nothing happen. But if we **right-click on a folder** and select "Open in Terminal", the folder opens in the same tab of Files.

**Comment by ryonakano** [comment] 2018-06-21 12:02
@torikulhabib Would you change this issue's title? I think we should change it to more clear one. For example, " By setting Terminal as a default file browser, the context menu "Open in Terminal" in Files do nothing" or something like that.

**Comment by pattontim** [comment] 2018-12-31 03:06
Issue still present in stable.

**Comment by jeremypw** [comment] 2018-12-31 12:35
@pattontim :  Could you give some more detail, please?

* Does this happen immediately you right-click on (a) any folder (b) any file.  Or when you click on "Terminal" option?
* Apart from the CLI messages, what happens?

**Comment by jeremypw** [comment] 2018-12-31 12:42
I am getting Terminal closing immediately after opening when launched from Files, but am not sure if its a Files problem or a Terminal problem yet ..

**Comment by jeremypw** [comment] 2018-12-31 12:51
I can confirm that Terminal crashes (or closes immediately) when launched as the default app for folders from Files using version 4.1.1.

**Comment by jeremypw** [comment] 2018-12-31 12:54
It launches OK from the submenu if Terminal is already running, but not if Terminal is not running.

**Comment by jeremypw** [comment] 2018-12-31 15:57
After install both FIles and Terminal from master source I now cannot reproduce this.

**Comment by jeremypw** [comment] 2018-12-31 16:12
I have uninstalled and reinstalled both Files and Terminal from the repository and it seems to be working OK. One quirk is that opening in terminal opens two identical tabs Terminal is not already running.

**Comment by pattontim** [comment] 2019-01-01 18:37
@jeremypw 

The above error I get is when files is run with sudo io.elementary.files-pkexec and appears immediately upon right click to open context menu. The issue appears when running it not as root as well.

The issue appeared as soon as terminal became the default option, ie when open in terminal becomes the first option in the context menu.

Behaviour is independent of whether a terminal is open or not.

If I'm recalling correctly, it works once after login but doesn't work after that. I need to verify this last point.

**Comment by jeremypw** [comment] 2019-01-01 19:30
@pattontim :  Thanks for the further info.  If Terminal is already open when you use Files context menu, do you get a new tab?  Are you using Juno?  Have you tried uninstalling and reinstalling Files and Terminal?  At present, I cannot reproduce with Juno and freshly installed Terminal and Files.

**Comment by pattontim** [comment] 2019-01-04 18:23
@jeremypw 

Yes it was on the latest version of Juno on a fresh install.

The issue disappears when reinstalling Terminal and Files, though it may be linked to when external applications are added to the context menu because that's when it began occurring.

**Comment by jeremypw** [comment] 2023-10-31 17:13
CLosing as appears fixed in Elementary OS 7 (Horus)

**Closed by jeremypw** 2023-10-31 17:13 UTC
Labels: Status: In Progress, Regression
