### ISSUE TITLE
Mouse hover and keyboard focus shouldn't use the same style (icon highlight)

### ISSUE THREAD

**Issue by jlnr** [elementary/files#322] opened 2018-02-10 12:04 UTC
After the following steps, I originally thought I was seeing a bug:

1. Select a file in icon mode.
2. Deselect it by clicking into the background.
3. The file keeps its hovered highlight state (bright icon) even after deselecting it.

What is happening is that the the file now has the *keyboard focus* which uses the same style (brighter icon) as mouse hover. I think this style makes sense to indicate mouse hovering because it matches Plank's behavior, but it shouldn't be reused for the unrelated concept of keyboard focus. 

I'm not even convinced that the keyboard focus needs a visual indicator. When using the arrow keys to navigate, the focused icon is automatically selected. But *if* a visual indicator is necessary, I think it should be either a blue outline (which is how e.g. the location bar indicates focus), or maybe a gray background as icons have it in List/Column mode when they are focused, but not selected (although I'm not sure if the gray background is used consistently, I also see it when I select several items in list mode).

**Comment by jlnr** [comment] 2018-02-10 12:09
Hmmm - might be caused by not properly installing my copy of Files.

**Comment by jlnr** [comment] 2018-02-16 15:07
I've realized that this is not actually a bug. The highlight represents both the mouse hover state and (in this case) the keyboard focus, as explained #330. I'll rename the issue because I don't think the styling here is intuitive.

**Comment by danrabbit** [comment] 2018-11-07 01:44
Gonna close this as a duplicate of #473 since a design proposal has been made there that will alleviate this concern

**Closed by danrabbit** 2018-11-07 01:44 UTC
Labels: Needs Design
