### ISSUE TITLE
Music folder icon in sidebar hard to see in Dark-mode

### ISSUE THREAD

**Issue by nicekiwi** [elementary/files#1893] opened 2021-11-15 08:15 UTC
### What Happened?

When dark-mode is enabled, the icon for the music folder in the sidebar is quite hard to see.

### Steps to Reproduce

1. Enable Darkmode
2. Open files app
3. Look at the Music Icon in the sidebar

### Expected Behavior

A more visible icon would be displayed, more like the light version of the icon in the path bar.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No log.
```

**Comment by nicekiwi** [comment] 2021-11-15 08:17
![Screenshot from 2021-11-15 21-17-07](https://user-images.githubusercontent.com/738975/141746221-ac0e48c1-cf55-46e8-979a-703b65006c0d.png)

**Comment by jeremypw** [comment] 2021-11-15 09:33
Thanks for the report!  This issue probably belongs in https://github.com/elementary/icons/issues as Files does not use custom styling or icon with respect to the music folder.

**Comment by Marukesu** [comment] 2021-11-15 19:08
This is a duplicate of elementary/icons#853

**Comment by danrabbit** [comment] 2021-11-15 20:33
Indeed, closing as a duplicate

**Closed by danrabbit** 2021-11-15 20:33 UTC
