### ISSUE TITLE
Color tags only show when hovering any icon in the directory

### ISSUE THREAD

**Issue by santileortiz** [elementary/files#736] opened 2018-11-05 06:04 UTC
When opening files or opening a folder, color tags don't show up.

In Grid mode hovering any icon makes tags appear, in List and Column modes I have to hover the tagged folders.

**Comment by jeremypw** [comment] 2018-11-06 16:20
I cannot reproduce this in the current master - are you using the stable version 4.0 (Juno)? Does it happen always or only e.g. with folders with lots of files?

There has been a commit related to color tags recently but it should not have affected this.

**Comment by santileortiz** [comment] 2018-11-06 19:07
Yes I have Juno, I just installed it 2 days ago. I'm using tagged folders is the home directory, there are not many things there. I don't know if it happened before because I just started using color tags.

I built the master branch and the problem is still there. Maybe it's something related to sqlite3?

**Comment by santileortiz** [comment] 2018-11-13 04:52
I installed some things in my system and the bug is now only a slight delay when opening files or changing directories. I don't know how to reproduce it again, more information will be required in order to fix it.

**Comment by jeremypw** [comment] 2018-11-13 13:30
OK, thanks.  How long is a 'slight delay'? There are a number of competing threads happening when a folder is first opened and getting the color tag involves messaging the pantheon-files-daemon over dbus.  I am looking at fetching the color tag only when needed anyway to reduce the cpu load fetching tags that are not actually visible so I would expect a slight delay, dependent competing loads. However that has not been merged yet.

**Comment by santileortiz** [comment] 2018-11-15 06:53
I would say the delay is about half a second, maybe less.

**Closed** 2019-01-11 00:56 UTC
