### ISSUE TITLE
Connect to server not possible.

### ISSUE THREAD

**Issue by dkotrada** [elementary/files#79] opened 2017-07-08 19:30 UTC
On Loki

When I click on the Item in the left panel in Files. "Connect to Server" "Mit Server verbinden"

I get an error. Please check your gvfs installation.

**Comment by jeremypw** [comment] 2017-07-09 11:21
Please provide more information. Did it start happening after an update or on a clean install? What error do you get?

**Comment by dkotrada** [comment] 2017-07-09 11:32
After an update.

**Comment by danrabbit** [comment] 2018-11-07 01:31
Closing since OP never responded to the follow up question. Feel free to reopen if this can be reproduced

**Closed by danrabbit** 2018-11-07 01:31 UTC
Labels: Status: Incomplete
