### ISSUE TITLE
Add an option to format USB devices

### ISSUE THREAD

**Issue by Odi-3** [elementary/files#2175] opened 2023-04-27 09:49 UTC
### Problem

In Files there is not an option to format USB devices.

### Proposal

- Right click
- Format USB device

**Comment by lenemter** [comment] 2023-04-27 10:12
Thanks for reporting! I believe this is a duplicate of https://github.com/elementary/files/issues/80

**Closed by lenemter** 2023-04-27 10:12 UTC

**Comment by Odi-3** [comment] 2023-04-27 10:29
Sorry, I hadn't seen it. Thank you
