### ISSUE TITLE
Files crash if replace canceled

### ISSUE THREAD

**Issue by Djaler** [elementary/files#696] opened 2018-10-23 05:42 UTC
Steps to reproduce:
1. Initiate replace dialog in Files
2. Click "Cancel"

Expected:
Dialog just canceled, everything else is as usual

Actual:
Files crashed

Screencast available here - https://youtu.be/qOZ0EH1SdD8

Crash message in terminal:
```
ERROR:/build/pantheon-files-JBeKj5/pantheon-files-4.0+r3132+pkg70~daily~ubuntu5.0.1/libcore/marlin-file-operations.c:4151:copy_move_file: code should not be reached
```

**Comment by arshubham** [comment] 2018-10-23 05:49
Possible duplicate of: https://github.com/elementary/files/issues/682

**Comment by jeremypw** [comment] 2018-10-23 10:38
The fix to #682 will fix this (the cause is the same).

**Comment by megatux** [comment] 2018-11-14 18:37
I can reproduce it here, I was doing a drag from a directory to the left quick access list . Most probably the same issue. The error in console is the same. Is the fix on #682 still not shipped?
screencast: https://youtu.be/DZBLsaeAE7M

**Comment by jeremypw** [comment] 2018-11-14 19:35
@megatux :  No, not yet.  The fix was merged 22 days ago, the last release (4.0) was 29 days ago.

**Comment by danrabbit** [comment] 2020-01-03 06:47
Closing since it's a duplicate

**Closed by danrabbit** 2020-01-03 06:47 UTC
Labels: Status: Duplicate
