### ISSUE TITLE
File-roller contract option extract here does not work for mounted drive

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#2144] opened 2023-02-21 14:33 UTC
### What Happened?

Unzip with right click in mountd drive fails but with terminal command (`unzip file.zip`) works fine. Unzipping with right click in my main drive works fine, the problem is the mounted drive

### Steps to Reproduce

1. Download https://yifysubtitles.ch/subtitles/two-witches-2021-spanish-yify-456019
2. Move zip file to mounted drive (mount point `/media/gabriel/...`)
3. Attempt to unzip using right click menu
4. Error shows saying I have no permissions
5. Attempt to unzip using terminal command (`unzip file.zip`)
6. Works fine

### Expected Behavior

Should unzip

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2023-02-21 18:43
Could you try looking at the permissions window for the target location?  I did not have any problem extracting `.zip` and other compressed files using Files on a USB hard disk partition to which I had read/write permission.  Regarding the terminal - you hadn't by any chance run `su` previously?  

You can run Files as Administrator by righting on the dock item in order to access partitions which an ordinary user does not have access.  Be careful though!  In this mode you can easily damage the system.

**Comment by Gabriel-p** [comment] 2023-02-21 19:21
This is the drive

![Captura de pantalla de 2023-02-21 16 19 08](https://user-images.githubusercontent.com/6054951/220438569-effa91dc-b504-433e-9b73-3ef88c1ae5ad.png)

I have all the permissions as far as I can tell

![Captura de pantalla de 2023-02-21 16 17 09](https://user-images.githubusercontent.com/6054951/220438203-da286f77-4065-4735-a718-4aded246406c.png)

but still:

![Captura de pantalla de 2023-02-21 16 17 49](https://user-images.githubusercontent.com/6054951/220438346-d7472862-8762-45b9-a614-451ec879fd4c.png)

Where using `unzip` (no `su`):

![Captura de pantalla de 2023-02-21 16 20 18](https://user-images.githubusercontent.com/6054951/220438755-60df4c66-6bbd-4016-ae78-dca6f30dbccd.png)

Again, I have no issues unzipping via right click in a folder inside my `/home/` tree

**Comment by jeremypw** [comment] 2023-02-21 20:14
Strange - nothing obviously wrong with the permissions.  Are you using the "Extract here" menu option?  Try using the "Open in Archive Manager" option and extracting there - do you still get the error?  You do need `file-roller` installed.

**Comment by Gabriel-p** [comment] 2023-02-22 11:46
Yes, I'm using the "Extract here" menu. If I open the Archive Manager and attempt to drag the file out to be extracted, I get a similar error about not having permissions

![Captura de pantalla de 2023-02-22 08 39 34](https://user-images.githubusercontent.com/6054951/220610048-d1438ac2-7b77-46ef-a36e-64d96ff55f10.png)

but if I hit the "Extract" button in the app it does allow me to extract it but  **not** in that drive but in some random folder:

![Captura de pantalla de 2023-02-22 08 39 47](https://user-images.githubusercontent.com/6054951/220610185-b1929b20-896f-42d2-b044-9257275d9f2c.png)

In fact, the app does not even see the mounted drive:

![Captura de pantalla de 2023-02-22 08 39 59](https://user-images.githubusercontent.com/6054951/220610328-dc487e25-f4b2-41ed-94e0-7a1b597334bd.png)

which should be under 'Otras ubicaciones' or 'Other locations' (not sure about the english version of this)

I should mention that I auto-mount this drive on startup with the line:

```
/dev/sdb1 /media/gabriel/rest ext4 nosuid,nodev,nofail 0 0
```
 in `/etc/fstab/` which results in it being mounted as:

![Captura de pantalla de 2023-02-22 08 44 59](https://user-images.githubusercontent.com/6054951/220610948-317aff88-862b-45c6-818d-7e0f25e8d9c3.png)

(it's the `rest` folder) Perhaps that's doing something strange?

**Comment by jeremypw** [comment] 2023-02-22 12:42
Ah! I see that you are using the Flatpak (sandboxed) version of the Archive Manager.  That would explain the permissions issue.  The Flatpak imposes its own permission restrictions.  Try installing the `.deb` instead.

**Comment by Gabriel-p** [comment] 2023-02-22 12:47
But this is the version that came with the system right? At least I do not remember installing it myself, this is what I see in the AppCenter

![Captura de pantalla de 2023-02-22 09 46 22](https://user-images.githubusercontent.com/6054951/220623757-0c144e49-ebf4-4f64-86a4-a9541a2ac7fe.png)

it says something like 'Appcenter (system scale)'

**Comment by jeremypw** [comment] 2023-02-22 20:26
Yes, unfortunately AppCenter only installs Flatpaks now :disappointed:  You would have to use `sudo apt install file-roller` in a terminal to get the deb.  Not sure who is responsible for the file-roller Flatpak permissions but it is not uncommon for Flatpaks to want to save files in strange places by default - but you may still be able to save them elsewhere manually.  There is an outstanding issue with contracts and Flatpaks as well.  Looks like Elementary is still shipping a contract requiring the deb but not installing the deb.  Let me check with a vanilla install of Horus.

**Comment by Gabriel-p** [comment] 2023-02-23 12:04
You are right, installing from terminal fixes the issue but now I've lost the 'Extract here' option in the right click menu. Is there a way to fix this?

**Comment by jeremypw** [comment] 2023-02-23 17:02
Hmm, that should not have happened, but you should be able to restore it by (re)installing `io.elementary.contract.file-roller` (`sudo apt install io.elementary.contract.file-roller`).

**Comment by Gabriel-p** [comment] 2023-02-23 17:55
Can not find that package
```
$ sudo apt install io.elementary.contract.file-roller
[sudo] contraseña para gabriel:     
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete io.elementary.contract.file-roller
E: No se pudo encontrar ningún paquete usando «*» con «io.elementary.contract.file-roller»
```

**Comment by jeremypw** [comment] 2023-02-23 18:56
Apologies - typo.  It should be `io.elementary.contractor.file-roller`

**Comment by Gabriel-p** [comment] 2023-02-23 21:56
It says not available (no candidate), wants to install ` org.gnome.fileroller`

```
$ sudo apt install io.elementary.contractor.file-roller
[sudo] contraseña para gabriel:     
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
El paquete io.elementary.contractor.file-roller no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente
Sin embargo, los siguientes paquetes lo reemplazan:
  org.gnome.fileroller

E: El paquete «io.elementary.contractor.file-roller» no tiene un candidato para la instalación
```

**Comment by jeremypw** [comment] 2023-02-24 10:48
This is what I have:
```
jeremyw@Kratos44b68d49OS7:~/Documents/Elementary/files/build$ apt show io.elementary.contractor.file-roller
Package: io.elementary.contractor.file-roller
Version: 0.1+r2~daily~ubuntu21.10.1
Priority: optional
Section: x11
Maintainer: Corentin Noël <corentin@elementary.io>
Installed-Size: 12.3 kB
Depends: file-roller
Enhances: file-roller
Download-Size: 2,308 B
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/elementary-os/daily/ubuntu jammy/main amd64 Packages
Description: Contractor extension for File Roller
 Extends the File Roller executable with the right contractor extension.

```

Its in the daily repository on by development install - I'll check whether its also in the stable repo.  You must have had it originally installed to have ever seen it.  The source is here https://github.com/elementary/file-roller-contract.

**Comment by Gabriel-p** [comment] 2023-02-24 11:29
I see no `daily` in my sources:

```
$ grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list:# deb cdrom:[elementary OS 7.0 _horus_ - stable amd64 (20230129)]/ jammy main
/etc/apt/sources.list:deb mirror://mirrors.ubuntu.com/mirrors.txt jammy main restricted universe multiverse
/etc/apt/sources.list:deb-src mirror://mirrors.ubuntu.com/mirrors.txt jammy main restricted universe multiverse
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
/etc/apt/sources.list:deb-src http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
/etc/apt/sources.list:deb mirror://mirrors.ubuntu.com/mirrors.txt jammy-updates main restricted universe multiverse
/etc/apt/sources.list:deb-src mirror://mirrors.ubuntu.com/mirrors.txt jammy-updates main restricted universe multiverse
/etc/apt/sources.list.d/bit-team-ubuntu-stable-jammy.list:deb https://ppa.launchpadcontent.net/bit-team/stable/ubuntu/ jammy main
/etc/apt/sources.list.d/bit-team-ubuntu-stable-jammy.list:# deb-src https://ppa.launchpadcontent.net/bit-team/stable/ubuntu/ jammy main
/etc/apt/sources.list.d/elementary.list:deb https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu jammy main
/etc/apt/sources.list.d/elementary.list:deb-src https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu jammy main
/etc/apt/sources.list.d/elementary.list:
/etc/apt/sources.list.d/google-chrome.list:### THIS FILE IS AUTOMATICALLY CONFIGURED ###
/etc/apt/sources.list.d/google-chrome.list:# You may comment out this entry, but any other modifications may be lost.
/etc/apt/sources.list.d/google-chrome.list:deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/jellyfin.sources:Types: deb
/etc/apt/sources.list.d/jellyfin.sources:URIs: https://repo.jellyfin.org/ubuntu
/etc/apt/sources.list.d/jellyfin.sources:Suites: jammy
/etc/apt/sources.list.d/jellyfin.sources:Components: main
/etc/apt/sources.list.d/jellyfin.sources:Architectures: amd64
/etc/apt/sources.list.d/jellyfin.sources:Signed-By: /etc/apt/keyrings/jellyfin.gpg
/etc/apt/sources.list.d/kelebek333-ubuntu-nvidia-legacy-jammy.list:deb https://ppa.launchpadcontent.net/kelebek333/nvidia-legacy/ubuntu/ jammy main
/etc/apt/sources.list.d/kelebek333-ubuntu-nvidia-legacy-jammy.list:# deb-src https://ppa.launchpadcontent.net/kelebek333/nvidia-legacy/ubuntu/ jammy main
/etc/apt/sources.list.d/patches.list:deb https://ppa.launchpadcontent.net/elementary-os/os-patches/ubuntu jammy main
/etc/apt/sources.list.d/patches.list:deb-src https://ppa.launchpadcontent.net/elementary-os/os-patches/ubuntu jammy main
/etc/apt/sources.list.d/patches.list:
/etc/apt/sources.list.d/sublime-text.list:deb https://download.sublimetext.com/ apt/stable/
```

**Comment by jeremypw** [comment] 2023-02-24 11:33
I have managed to get the contractor plugins to work by modifying the `.contractor` files as so:

**io.elementary.contractor.file-roller-extract-here.contract**
```
[Contractor Entry]
Name=Extract Here
Icon=extract-archive
Description=Extract the contents of the archives in the archive folder and quit the program
MimeType=application/x-7z-compressed;application/x-7z-compressed-tar;application/x-ace;application/x-alz;application/x-ar;application/x-arj;application/x-bzip;application/x-bzip-compressed-tar;application/x-bzip1;application/x-bzip1-compressed-tar;application/x-cabinet;application/x-cbr;application/x-cbz;application/x-cd-image;application/x-compress;application/x-compressed-tar;application/x-cpio;application/x-deb;application/x-ear;application/x-ms-dos-executable;application/x-gtar;application/x-gzip;application/x-gzpostscript;application/x-java-archive;application/x-lha;application/x-lhz;application/x-lrzip;application/x-lrzip-compressed-tar;application/x-lzip;application/x-lzip-compressed-tar;application/x-lzma;application/x-lzma-compressed-tar;application/x-lzop;application/x-lzop-compressed-tar;application/x-ms-wim;application/x-rar;application/x-rar-compressed;application/x-rpm;application/x-rzip;application/x-tar;application/x-tarz;application/x-stuffit;application/x-war;application/x-xz;application/x-xz-compressed-tar;application/x-zip;application/x-zip-compressed;application/x-zoo;application/zip;
Exec=flatpak run org.gnome.FileRoller --extract-here %U
Gettext-Domain=file-roller
```

**io.elementary.contractor.file-roller-extract-here.contract**

```
[Contractor Entry]
Name=Compress
Icon=add-files-to-archive
Description=Create a compressed archive with the selected objects
MimeType=!archive;inode/blockdevice;inode/chardevice;inode/fifo;inode/socket;
Exec=flatpak run org.gnome.FileRoller --add %U
Gettext-Domain=file-roller
```

These modified files I placed in `~/.local/share/contractor` so that the supplied contracts are overridden for the user.

All I did was modifiy the "Exec=" line.

**Comment by jeremypw** [comment] 2023-02-24 11:37
As you installed the released version "daily" is replaced by "stable" in your sources.

**Comment by jeremypw** [comment] 2023-02-24 11:42
Looks like that package was removed from the stable repo (see https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+index?field.series_filter=jammy).  Not sure how it is you saw the option - may be it was incorporated into another package.

**Comment by Gabriel-p** [comment] 2023-02-24 11:52
So right now I have file-roller installed from terminal. Should I remove it and re-install from the Appcenter and then create the `~/.local/share/contractor` file with those entries? If so, which option from the Appcenter should I use: Appcenter, Appcenter (system scale) or Flathub?

**Comment by jeremypw** [comment] 2023-02-24 12:08
I would reinstall org.gnome.FileRoller Flatpak from AppCenter. I usually do not install system-wide as I am the only user and I do not think there are any system level functions that use it. You might get different permissions if installed system-wide, I am not sure, but I would start with a user install anyway.

Hopefully this will get sorted out in the iso eventually!

**Comment by jeremypw** [comment] 2023-02-24 12:34
OK, so now I have looked at a vanilla Horus install with AppCenter FileRoller installed - and it already supplies the the contract files in the modified form! So just reinstalling the AppCenter Flatpak should allow you to compress and extract files with Files at least within you home directory.

Sorry for all the confusion - I didn't realize there was this difference between stable and my development version.  I think the root of this issue was just to do with the sandbox pernissions granted to the Flatpak version of FileRoller.

**Comment by jeremypw** [comment] 2023-02-24 17:36
It should not need a system restart.  Could you look in `usr/share/contractor` ? There should be two contracts there `io.elementary.files.contractor.file-roller-extract-here.contract` and `io.elementary.files.contractory.file-roller-compress.contract`. You can read the contents of these with Code or other text editor. The exec line should start with `flatpak run org.gnome.FileRoller `.  This is what I have after installing a fairly recent Horus iso.  Make sure you do not have entries in `~/.local/share/contractor` as these take precedence.  Might be worth running `flatpak list | grep FileRoller` to check you have the expected version (and only that version).  I get:
```
jeremyw@Kratos-faeb3077-OS7stable:~$ flatpak list | grep FileRoller
File Roller	org.gnome.FileRoller	43.0	stable	appcenter	system

```

**Comment by Marukesu** [comment] 2023-02-24 18:36
The correct contractors (the ones pointing to the flatpak installation) are in the `org.gnome.FileRoller` apt package. `pkexec apt install org.gnome.FileRoller` should install them.

**Comment by Gabriel-p** [comment] 2023-02-24 22:10
I reinstalled the Appcenter version, and then run the `pkexec` command to generate the contract files. This command brought back the "Extract here" entry in the menu. These are the contents of these files in `/usr/share/contractor/`

```
[Contractor Entry]
Name=Extract Here
Icon=extract-archive
Description=Extract the contents of the archives in the archive folder and quit the program
MimeType=application/x-7z-compressed;application/x-7z-compressed-tar;application/x-ace;application/x-alz;application/x-ar;application/x-arj;application/x-bzip;application/x-bzip-compressed-tar;application/x-bzip1;application/x-bzip1-compressed-tar;application/x-cabinet;application/x-cbr;application/x-cbz;application/x-cd-image;application/x-compress;application/x-compressed-tar;application/x-cpio;application/x-deb;application/x-ear;application/x-ms-dos-executable;application/x-gtar;application/x-gzip;application/x-gzpostscript;application/x-java-archive;application/x-lha;application/x-lhz;application/x-lrzip;application/x-lrzip-compressed-tar;application/x-lzip;application/x-lzip-compressed-tar;application/x-lzma;application/x-lzma-compressed-tar;application/x-lzop;application/x-lzop-compressed-tar;application/x-ms-wim;application/x-rar;application/x-rar-compressed;application/x-rpm;application/x-rzip;application/x-tar;application/x-tarz;application/x-stuffit;application/x-war;application/x-xz;application/x-xz-compressed-tar;application/x-zip;application/x-zip-compressed;application/x-zoo;application/zip;
Exec=flatpak run org.gnome.FileRoller --extract-here %U
Gettext-Domain=file-roller
```

and

```
[Contractor Entry]
Name=Compress
Icon=add-files-to-archive
Description=Create a compressed archive with the selected objects
MimeType=!archive;inode/blockdevice;inode/chardevice;inode/fifo;inode/socket;
Exec=flatpak run org.gnome.FileRoller --add %U
Gettext-Domain=file-roller
```

Is there a way to edit the `Exec` line so that it will work on mounted drives for which it shows that I have no permission (although I do)?

**Comment by jeremypw** [comment] 2023-02-25 16:37
Its the FileRoller sandbox that does not have permission, rather than you. Flatpaks only have such permissions as the developer thinks are necessary. Obviously it would contradict the security model of Flatpaks for it to be easy to override their permissions.  See https://docs.flatpak.org/en/latest/sandbox-permissions.html for more info. One way would be to rebuild it from source code after editing the manifest file I guess.  A workround is to extract into a directory that works and then use Files to move the extracted folder to where you want it.

I thought the correct contracts were in the Flatpak supplied by Appcenter - they certainly ought to be! I'll investigate further.

**Comment by jhaygood86** [comment] 2023-02-25 16:58
I wonder if some integration with the document portal could solve this: essentially give fileroller permissions to the directory to extract, and then remove it after fileroller exits?

**Comment by jeremypw** [comment] 2023-02-25 17:04
OK, so I can confirm that the AppCenter version of FileRoller does *not* reinstall the contract files if they somehow get deleted when installed with AppCenter. The `.deb` package however installs both the Flatpak *and* the contract files but has to be installed via the terminal.  Not very satisfactory but probably inevitable since the Flatpaks should be system agnostic while the contracts are an elementaryOS specific thing.

**Comment by jeremypw** [comment] 2023-02-25 17:07
@jhaygood86 Portals are the solution to many Flatpak permission problems - just need someone to work on it!

**Comment by jeremypw** [comment] 2023-02-25 17:30
I've raised an issue here: https://github.com/elementary/appcenter/issues/2011 about contract installation just for visibility; it may be considered too much of a corner case to address.

**Comment by Gabriel-p** [comment] 2023-02-27 11:53
Thank you both. It's a bit of a pain that File-roller does not work on my mounted drive, but it's a minor inconvenience anyway. Feel free to close this

**Comment by jeremypw** [comment] 2023-02-27 12:56
Closing as there is no obvious way of fixing this within the Files codebase.

**Closed by jeremypw** 2023-02-27 12:56 UTC

**Comment by Gabriel-p** [comment] 2023-03-20 20:43
Just a heads up, today I learned (thanks to this tweet https://twitter.com/elementary/status/1637909884397146112) that simply allowing File Roller to work on System Folders fixes this issue
