### ISSUE TITLE
Can no longer use delete key to delete directories or files

### ISSUE THREAD

**Issue by aral** [elementary/files#1944] opened 2021-12-17 15:05 UTC
### What Happened?

Files has lost the ability to delete directories/files using the delete key.

### Steps to Reproduce

1. Select file or directory
2. Hit the delete key

Nothing happens.

### Expected Behavior

They should get deleted.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

```
Version: io.elementary.files 6.1.1

OS: elementary OS 6 Jólnir x86_64 
Host: LabTop Mk IV 
Kernel: 5.11.0-41-generic 
Uptime: 1 day, 19 hours, 27 mins 
Packages: 2439 (dpkg), 89 (flatpak) 
Shell: fish 3.3.1 
Resolution: 1920x1080, 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 4775MiB / 15871MiB 
```

**Comment by aral** [comment] 2021-12-17 15:07
PS. Just noticed neofetch is reporting the OS as:

```
OS: elementary OS 6 Jólnir x86_64
```

Jólnir as in “new year?” Easter egg? :)

**Comment by jeremypw** [comment] 2021-12-17 16:25
I cannot reproduce this with the latest release (in a UK locale).  Can you delete(trash) the same folder other ways (e.g. with the context menu)?

**Comment by jeremypw** [comment] 2022-02-13 13:07
Closing as not confirmed to occur in latest release.  Please re-open if you disagree.

**Closed by jeremypw** 2022-02-13 13:07 UTC
