### ISSUE TITLE
can not copy many file/folder

### ISSUE THREAD

**Issue by torikulhabib** [elementary/files#583] opened 2018-08-06 01:00 UTC
![gifout](https://user-images.githubusercontent.com/26135527/43692110-ad232f38-994e-11e8-8318-9954b1fbd277.gif)

**Comment by ryonakano** [comment] 2018-08-07 06:17
I can reproduce this, but actually I think this issue occurs whether the file size is big or not. Instead, I think it does when we select and try to copy more than two files. Here is a GIF I took:

![peek 2018-08-07 15-12](https://user-images.githubusercontent.com/26003928/43757712-aa10d6fe-9a54-11e8-96d1-2bd3ea25b812.gif)

And maybe this is a regression bug.

**Comment by jeremypw** [comment] 2018-08-07 10:08
Apologies for missing this regression caused by the most recent commit.  A fix has been pushed for approval.

**Closed** 2018-08-13 20:37 UTC
Labels: Priority: Critical, Regression, Status: In Progress
