### ISSUE TITLE
ListView: Empty row at the end of the column

### ISSUE THREAD

**Issue by KeurKeur** [elementary/files#1705] opened 2021-05-12 10:12 UTC
## What Happened

When expanding a folder, there is empty rows adding to the current column : 
![Capture d’écran depuis 2021-05-12 12-02-55](https://user-images.githubusercontent.com/49370356/117957417-574b3400-b31a-11eb-81e9-136b4b31f887.png)

If we add the hidden files : 
![Capture d’écran depuis 2021-05-12 12-03-09](https://user-images.githubusercontent.com/49370356/117957488-6c27c780-b31a-11eb-9fc3-435004f3b438.png)

## Expected Behavior

No empty rows.

## Steps to Reproduce

1. Expand multiple folders.
2. Click on the blank zone after the last folder.

### Logs

No logs.

## Platform Information

Elementary OS 6 Beta on gnome-boxes. Tested with pantheon-files from the release and the master.

Thanks !

P.s : Not related, but if you look at the column size, it seems the po files are not updated. :sweat_smile: 
P.Ps; I don't know if this is an issue, and sorry to write it here, but when hiding the hidden files is it normal that it closes all opened folders ?

**Comment by jeremypw** [comment] 2021-05-12 13:04
Dummy rows are meant to be added only when an empty folder is expanded (and removed if a file is added to an empty folder).  Probably a regression due to recent rewrite of the underlying model in Vala. Will look into it.

**Comment by jeremypw** [comment] 2021-05-12 13:29
When "Show hidden" is toggled from "Off" to "On" the view is reloaded from disk.  At the moment it does not store the expansion states (there is an open issue about Files not storing expansion states in the settings so they are not restored on restart either).  I think it was always like this.  I guess you could raise a separate issue/feature request about it.

The item count is not matching the number of visible items in an expanded folder but if you open that folder in a new tab it appears to be correct. So there is definitely something weird going on when expanding folders.

**Comment by jeremypw** [comment] 2021-05-12 13:42
OK, so it seems that sometimes the children of a subfolder are being shown as children of the root folder.  It is associated with resorting the view and it seems to be fixed by draft PR #1688.  If you are able to confirm whether that PR fixes the title issue for you that would be helpful, thanks.

**Comment by jeremypw** [comment] 2021-05-12 13:50
After further fiddling PR #1688 does not fix the problem entirely - the model structure can still become incorrect after deleting files.

**Closed** 2021-06-07 17:48 UTC
