### ISSUE TITLE
Better visibility of thumbnails in dark theme

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/files#1460] opened 2020-09-03 21:16 UTC
When I look at the two Files screenshots in https://github.com/elementary/stylesheet/pull/802, the mediakeys.svg thumbnails don't look that recognizable to me.
Somehow it reminds me of this light theme issue https://github.com/elementary/files/issues/712, where I had a similar perception. Have you already thought about it?

**Comment by cassidyjames** [comment] 2020-09-03 21:37
It looks like this SVG is so short/wide that it's just hard to see its checkerboard background. I don't know what the solution is; it it were closer to a square ratio, it would be easier to see.

**Comment by micahilbery** [comment] 2020-09-03 23:45
Other than making the checkerboard background be the full size of the icon view, I don't know that there is a real solution to this without misrepresenting what the image is. It's a black svg on a dark background the same would happen with a white svg on the light background. But expanding the checkerboard pattern would misrepresent the aspect ratio of the image.

**Comment by danrabbit** [comment] 2022-06-24 02:28
Yeah I think this is ultimately a duplicate of #728

**Closed by danrabbit** 2022-06-24 02:28 UTC
