### ISSUE TITLE
No Recent section while saving files

### ISSUE THREAD

**Issue by arjunmenon** [elementary/files#316] opened 2018-02-04 08:33 UTC
Hey
_On 0.4.1 Loki, Linux 4.13.0-32-generic_
There is no Recent section in the file browser when you want to save a file from the web.
When you want to open a file however, you are shown the Recent section.

In Freya, it was consistent.

Open dialog
![screenshot from 2018-02-04 13 56 11](https://user-images.githubusercontent.com/953959/35775686-ac0ec358-09b3-11e8-9e2c-68d8253cce56.jpeg)

Save dialog
![screenshot from 2018-02-04 13 55 31](https://user-images.githubusercontent.com/953959/35775688-b5095a4a-09b3-11e8-9490-7450f26bd180.jpeg)

AS you can see, there is no Recent section in the Save dialog. Frankly, this is a bit annoying while working.

**Comment by jeremypw** [comment] 2018-02-04 10:02
Files uses a modified version of the Gtk.FileChooserDialog - Files does not manage the sidebar part. So I guess this is due to a different version of Gtk being used in Loki than Freya.  Presumably it was considered that saving to the Recents folder does not make sense although I can see it could be useful for navigating to the desired folder.  The filechooser should now reopen at the folder selected when it last closed (although that fix may not be released in stable).  Otherwise you can create custom bookmarks for you favorite locations and these will show in the filechooser.

**Comment by jeremypw** [comment] 2018-02-04 10:03
This is essentially a duplicate of https://github.com/elementary/files/issues/129

**Comment by arjunmenon** [comment] 2018-02-04 13:49
> Presumably it was considered that **saving to the Recents folder does not make sense** although I can see it could be useful for navigating to the desired folder. 

Humbly speaking, this is bad UX.

Recents folder makes total sense. While working within multiple folders I dont want to navigate each time there.
Creating bookmarks is also not an option for tons of folders for each situation.
I constantly see myself saving many resources from the web. _(Think of designers saving files carefully organized in multiple folders in Documents, think of working within Java folders)_
In Freya, this was easily handled. I could easily switch between each folder nested within a web of folders with Recent.
Please it should be there. And there should be consistency.

**Comment by jeremypw** [comment] 2018-02-04 14:23
OK, I understand your view  but I do not think it was elementary or Files that made this choice I think Gtk 3 based apps running on other desktops are likely to have this behaviour (I will check).   It would be possible for Files to modify the filechooser further to restore the behaviour I will see whether this can be done without replacing the whole sidebar widget (which is not trivial).  Then it would up to the UX team which behaviour they want.

**Comment by jeremypw** [comment] 2018-02-04 14:35
I just found that in the Gtk3 filechooser you can access the recent folder while saving by using the shortcut "Alt + R".  In the Files chooser this does not alter the pathbar which is a bit of a bug but the recent folder is displayed.  You could also set up a custom bookmark to the Recent folder (although that would mean two Recent  bookmarks normally)

**Comment by jeremypw** [comment] 2018-02-04 14:38
The GtkPlacesSidebar does have a "show_recent ()" function so it should be fairly easy for the Files filechooser to show it even in Saving mode .

**Comment by arjunmenon** [comment] 2018-02-04 17:59
Wooh..doing `Alt+R` crashes Firefox.
It does show on the first attempt but if you do that again, it simply crashes.
Is there a way I can find about this anywhere from a log? I can send that to you to see what is happening.

**Comment by jeremypw** [comment] 2018-02-04 23:01
Hmmm - I only tried it with Code, without problems.  Looks like that it may not be a viable work round at the moment then, although I could not reproduce a crash in Chrome in Loki/unstable.  Running a problematic executable from the terminal under gdb and typing bt when it crashes will give a backtrace and show where it is crashing.  This works with Epiphany but not Chromium or Firefox as they do not have "normal" executables in /usr/bin.  May need to look into handling Alt + R within Files filechooser module.

**Closed** 2018-05-19 21:18 UTC
Labels: Status: In Progress
