### ISSUE TITLE
Login prompt appearing twice after installation.

### ISSUE THREAD

**Issue by TryingHardNovice** [elementary/files#1943] opened 2021-12-17 06:32 UTC
### What Happened?

At first time login right after installation, the log in prompt appears twice. (When you enter your username and password and pressed 'Enter', you see the same login prompt so you have to enter your username and password again.)

### Steps to Reproduce

1. Perform a first time install of Odin without internet connectivity using a USB drive.
2. Enable/check proprietary software drivers.
3. Complete installation and shut down the machine.
4. The system asks you to enter your username and password, including the PC's name (and other things needed that I may not have listed here).
5. The system shows the login prompt twice, one after the other, the same prompt.

### Expected Behavior

The login screen should only appear once.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2021-12-17 09:41
This does not sound like a Files issue.  If the greeter screen is being displayed twice (and the password was correctly entered the first time) then maybe it is a greeter issue?  If you are unsure which part of the system is responsible best raise an issue in elementary/triage.

**Comment by cassidyjames** [comment] 2021-12-17 19:49
Duplicate of https://github.com/elementary/triage/issues/92

**Closed** 2021-12-17 19:50 UTC
Labels: Status: Duplicate, Status: Out of Scope
