### ISSUE TITLE
Some text is overwriting "open with"

### ISSUE THREAD

**Issue by alchehabii** [elementary/files#188] opened 2017-10-27 19:50 UTC
mp3 document properties shows some text positioned above "open with" text.

![screenshot from 2017-10-27 21 34 29](https://user-images.githubusercontent.com/10380737/32122499-d159b02e-bb60-11e7-8797-3129ad41b7a0.png)

**Comment by danrabbit** [comment] 2017-10-27 20:38
It looks like the device usage header and the open with label are being packed into the same grid quadrant 😬

**Comment by jeremypw** [comment] 2017-10-28 09:05
Thanks for the report, but this is a duplicate of #141.

**Comment by jeremypw** [comment] 2017-11-04 16:54
FIxed by #189

**Closed** 2017-11-04 16:54 UTC
Labels: Status: Duplicate
