### ISSUE TITLE
Color for file/folder not saved

### ISSUE THREAD

**Issue by Whemerson** [elementary/files#894] opened 2019-02-21 12:35 UTC
After the update I can no longer use this color feature in the folders, the colors disappear when I left the folder to another, and when I go back to the one I had colored there is no longer the color in the folder.
Elemenatry Team OS Congratulations, I love the distro, I recently migrated and I'm loving it, beautiful job !!!

**Comment by jeremypw** [comment] 2019-02-21 18:08
Thanks for report and I am glad you are enjoying elementary.  This is a duplicate of issue #892 which has just be closed by a recent commit.  Hopefully this fix will be released soon.

**Closed by jeremypw** 2019-02-21 18:08 UTC
Labels: Status: Duplicate
