### ISSUE TITLE
Multiple Files instances open up

### ISSUE THREAD

**Issue by kenedyroger** [elementary/files#981] opened 2019-07-04 18:31 UTC
If you open Files app from Trash Doklet Icon, all subsequent clicks on that icon will open a new instance of Files pointing to trash folder, I think that correct behavior at this moment should be to bring to front the Files window already opened instead open another instance of the same app.

**Comment by jeremypw** [comment] 2019-07-05 09:14
I cannot reproduce this exactly as described using Juno unstable - subsequent click causes the existing window to open Trash again in a new tab (and the cursor changes to a spinner for a while).

This is not specific to trash.  If you launch Files with a uri from the terminal, an existing Files window will open that uri in a tab even if there is already a tab with that uri.  This contrasts with Code, which does not open a duplicate document under these circumstances.

Maybe @elementary/ux should confirm correct behaviour.

**Comment by kenedyroger** [comment] 2019-07-09 13:29
I attached a short GIF to show you what I talking about.
![multiple_windows](https://user-images.githubusercontent.com/12687905/60891621-0b1d9d00-a234-11e9-98b0-c52e3a85f9f1.gif)

**Comment by jeremypw** [comment] 2019-07-09 15:50
Please could you confirm which version of Files you are using and whether it is from the stable or unstable repo?

**Comment by kenedyroger** [comment] 2019-07-18 12:57
So i'm using now files 4.1.8 from stable

**Comment by jeremypw** [comment] 2019-07-19 18:30
I can reproduce this in stable. I'll try and determine when it was fixed in master.

**Comment by kenedyroger** [comment] 2019-08-20 16:39
In the last version (4.1.9) the behavior was changed instead of it open multiple windows at click time it now open multiple tabs on the same window
just to inform you about this

**Comment by jeremypw** [comment] 2019-08-22 08:15
Thanks for letting me know.  I notice that Terminal, under equivalent circumstances (launching repeatedly from the commandline with the same parameter), opens multiple windows, but Code does follow the behaviour you wish - i.e. just opens presents the existing window/document. So there seems to be some inconsistency amongst elementary apps in this respect.

**Comment by jeremypw** [comment] 2019-08-22 08:18
I tend to agree with your view - it is unlikely that a user would want to open multiple view of the same folder from the commandline (which is equivalent to launching from the dock).  There is facility to open a duplicate tab from the tab context menu.

**Comment by jeremypw** [comment] 2019-08-22 08:23
Note that this does not only affect Trash.  If you drag a folder out of Files and drop on the dock you get an icon that allows you to open subfolders of that folder in Files.  Repeatedly clicking on the same subfolder opens multiple tabs, rather than presenting the existing window/tab.

**Closed** 2020-01-06 22:53 UTC
Labels: Needs Design
