### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alanmm** [elementary/files#314] opened 2018-01-28 21:21 UTC
I'm having this issue since yesterday, every time I try to access a mounted ntfs drive. 
I don't know if this is the culprit, but I've installed days ago the "gnome-disk-utility" so the drives could be automatically mounted since startup. I removed it already, and the problem persists. I don't know if it messed with the original config of fstab, but anyway, I can't access that drives via Files, or through any program that makes use of it, because the application closes immediately. But I can via terminal. 

Here is some log:

```
$ io.elementary.files .
[INFO 19:12:43.239460] Application.vala:154: Files version: 0.3.5
[INFO 19:12:43.239607] Application.vala:156: Kernel version: 4.13.0-32-generic
[INFO 19:12:43.287816] Application.vala:66: Report any issues/bugs you might find to https://github.com/elementary/files/issues
[WARNING 19:12:43.613499] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613569] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613622] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613670] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613717] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613760] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613794] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613826] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613870] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613922] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.613965] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614017] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614073] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614124] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614182] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614229] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614284] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614335] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614385] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614449] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614505] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614557] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614608] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614681] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.614754] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.695128] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.695235] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.695351] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.695474] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.695904] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.696305] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.696623] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.697380] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.697775] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.698267] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.700247] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.700438] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.700570] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.700721] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.700816] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.704918] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705003] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705075] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705144] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705210] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705267] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705363] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705458] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705556] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
[WARNING 19:12:43.705655] plugin.vala:238: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.files.db was not provided by any .service files
Segmentation fault (core dumped)

```

**Comment by jeremypw** [comment] 2018-01-29 11:22
Looks like a problem with the color tagging daemon.  Check that the process io.elementary.files.daemon is running (not panthon-files-daemon).  If you have just upgraded to a new version of Files you may have to logout or reboot for the correct daemon to start.

**Comment by jeremypw** [comment] 2018-01-29 11:25
However, if other apps are also crashing it may not be a Files issue.

**Comment by alanmm** [comment] 2018-01-29 23:25
Thanks for the quick reply! 
I'm not well versed in linux, so I don't know if I'm doing right.
I checked if the service was active ( sudo systemctl is-active io.elementary.files.daemon ) and it was inactive.
Then I tried to start it by typing
```
sudo systemctl start  io.elementary.files.daemon
Failed to start io.elementary.files.daemon.service: Unit io.elementary.files.daemon.service not found.
```
and

```
$ sudo systemctl start  io.elementary.files
Failed to start io.elementary.files.service: Unit io.elementary.files.service not found.
```
So.. perhaps there may be a command to reinstall and restore that package? Or I'll wait a little more for the next update

**Comment by jeremypw** [comment] 2018-01-30 09:20
OK. In /usr/share/dbus-1/services is there a file `io.elementary.files.service` or do you have a `pantheon-files.xxxx.service` (is can't remember the exact name) You may have a  partial upgrade of Files - in the stable Loki repository (version 0.3.5) it is still using the pantheon-files names; in the unstable repository (or if you installed from source) the io.elementary.files names are used.  You could try uninstalling and reinstalling files from the whichever repository you are using.

**Comment by jeremypw** [comment] 2018-05-19 09:33
Closing as not established whether this is a reproducible issue in Files.

**Closed by jeremypw** 2018-05-19 09:33 UTC
