### ISSUE TITLE
CD-Rom support is broken

### ISSUE THREAD

**Issue by Nine-H** [elementary/files#259] opened 2017-12-04 06:31 UTC
Files correctly recognises a blank cd, however it continues to beilieve that cd is blank after I have burned audio to it and won't recognise the burned disc untill after I reboot. Inserting an audio CD works on a clean boot, however you must restart the computer to change discs.

**Comment by Nine-H** [comment] 2017-12-04 08:10
DM me on slack if you want additional tests.

**Comment by jeremypw** [comment] 2017-12-05 11:31
What happens if you eject the disc with Files and then re-insert?  If you still have the problem even after ejecting, closing Files, logging out and logging back in it sounds more like a system caching issue.  Files has no memory of state between sessions.

**Comment by Nine-H** [comment] 2017-12-05 11:55
it runs fine, until I burn a cd, now it thinks every audio cd I insert has five tracks.

**Comment by jeremypw** [comment] 2017-12-05 12:15
Sounds related to #38 I'll see if I can reproduce.  Are you running Loki stable or daily?

**Comment by Nine-H** [comment] 2017-12-05 12:18
this machine's on stable. I used brasero to burn if it makes any difference.

**Comment by jeremypw** [comment] 2018-05-21 11:53
Is this still a problem on the latest version of Files? (preferably Juno).  I could not reproduce.

Note that if you insert an empty disc the path given is "burn://"  This will contain any files that you copied or dragged there using an app that uses gvfs.  Even if you burn these files onto disc using brasero, they remain in this virtual directory and will be shown whenever you insert a blank disc until you remove them.

If you insert an audio disc that has files burned on it then the path given will start with "/media/...."

Marking incomplete until update received.

**Comment by jeremypw** [comment] 2018-05-21 11:57
If you somehow have two discs that give the same path, then there is a bug where the corresponding directory object in Files may not be removed from the cache when the first one is ejected and therefore will be redisplayed when the second disc is inserted until you press refresh.

There is PR that fixes this awaiting review in Juno.

**Comment by jeremypw** [comment] 2023-06-25 12:15
Closing as marked incomplete.

**Closed by jeremypw** 2023-06-25 12:15 UTC
Labels: Status: Incomplete
