### ISSUE TITLE
About pantheon-file and mute key, big troublesome!

### ISSUE THREAD

**Issue by absop** [elementary/files#418] opened 2018-04-17 12:20 UTC
Sometimes when I press down the __mute key__ in the __pantheon-file__ for opening or closing the sound of deleting files, it make all the desktop system's services can't work!! At this point, the __mouse__ and __cursor__ will not response(the cursor will not display at a text editor)! and, many applications' menu bar will not response!!!

At this time, if I enter into a terminal and kill the __pantheon-file-daemon__, everything will be OK.

There are also some issue of the __mute key__, many times, if I press down the __mute key__, it would make some sound like __"du du du..."__!

System:  **elementary OS 0.4.1 Loki**.

**Comment by yezhiqiu1998** [comment] 2018-04-17 12:29
Sometimes when I press down the `mute key` in the `pantheon-file`
for opening or closing the sound of deleting files, it make all the desktop

system's services can't work!! At this point, the mouse and cursor

will not response(the cursor will not display at a text editor)!

and, many applications' menu bar will not response!!!

 At this time, if I enter into a terminal and kill the
pantheon-file-daemon, everything will be OK.

There are also some issue of the `mute key`, many times, if I press
down the mute key, it would make some sound like "du du du..."!

System: elementary OS 0.4.1 Loki.

**Comment by jeremypw** [comment] 2018-04-17 17:16
Thanks for telling us about this.  On my system the mute key is `<Fn>+F3`  and I have not experienced any problem using it during limited testing (pantheon-files should not pay attention to this key).   You say this issue "sometimes" happens.  If you can identify the exact circumstances that cause it that would be a great help.

**Comment by yezhiqiu1998** [comment] 2018-04-18 00:29
No, I just pressed down the __mute__ key<Fn +F0> and loosened it, didn't hold it down, many times it will cause the "du du du..." sound repeatedly untill I press down <Fn+F1> or <Fn +F2> to adjust the volume of sound, many times it is!

If this action is done in __pantheon-file__, it will result in the troublesome I have statemented,
at this time,  kill __pantheon-file-daemon__ will helpful!

**Comment by jeremypw** [comment] 2018-05-16 17:51
This issue is hard to understand since the pantheon-files daemon does not interact with the sound system or the keyboard - it offers two DBus services - one to color tag files and the other to offer the FreeDesktop "FIleManager1" interface to other apps wanting to show the location or properties of files.

I do not really understand what you mean by  `mute key` in the `pantheon-file`  - the Files application (io.elementary.files) does not have any sound controls - that is a system function.  Why are you muting the sound of deleting files?  Is this something that you would like and option to disable?

**Comment by jeremypw** [comment] 2023-06-25 15:23
Closing as it has remained unconfirmed for several years.

**Closed by jeremypw** 2023-06-25 15:23 UTC
Labels: Unconfirmed
