### ISSUE TITLE
It isn't obvious that the location bar acts as a file search. Add a search icon.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#396] opened 2018-03-27 05:46 UTC
The Files UI doesn't expose any visible search function, nor does it make it obvious that the location bar is searchable even on a mouse click.

1. No visible search function
![No visible search function](https://user-images.githubusercontent.com/22585732/37948840-9ca7015e-31af-11e8-914b-63612117afa0.png)

2. Mouse click in the location bar doesn't make it obvious is a file search function
![screenshot from 2018-03-27 11-10-55](https://user-images.githubusercontent.com/22585732/37948853-adc208d0-31af-11e8-9740-d4cab8e90af1.png)

3. Only on "Ctrl+F" is there a hint given but the keyboard shortcut isn't obvious either. 
![screenshot from 2018-03-26 12-39-01](https://user-images.githubusercontent.com/22585732/37948934-09d8ccbc-31b0-11e8-8f89-4da62f55eb0c.png)

IMO, discoverability of the file search function is underrated. Apart from Files, elementary doesn't offer an all files search function, so Files needs to make that role clear.

**Comment by jlnr** [comment] 2018-03-27 08:15
I think this is a duplicate of #170, which I've implemented in PR #325.

I went a little overboard in my PR and also added an app menu; I'll update the PR soon to remove the app menu again as I'm not happy with it. I really think the search icon would go along well with the new global search icon in Juno's wingpanel.

**Comment by jeremypw** [comment] 2018-04-21 16:48
UX team have determined that any solution to this should not involve adding extra icons to the header bar.

**Comment by danrabbit** [comment] 2018-04-21 16:51
Closing as a duplicate of #170

**Closed by danrabbit** 2018-04-21 16:51 UTC
Labels: Status: Duplicate
