### ISSUE TITLE
Stops copying files from smb:// to removable device

### ISSUE THREAD

**Issue by artemanufrij** [elementary/files#717] opened 2018-10-28 19:46 UTC
How to reproduce:
* you need ~ 4 GB files _(In my case I tried to copy some music files onto a SD-Card)_
* copy files from smb:// share to a removable device like SD-Card (as example) by ctrl+c ctrl+v

:arrow_right: copying stops at 1/1,5 GB. Progress window can't be closed. It stays open until you kill it or relog your session.
![screenshot von 2018-10-28 20 45 01](https://user-images.githubusercontent.com/16517095/47621067-69657e00-daf2-11e8-8daf-7d000f6ab372.png)

**Comment by jeremypw** [comment] 2018-10-29 11:51
I guess if they are music files that is quite a large number of individual files?  Might be worth checking with system monitor or htop whether Files is still using cpu and how much memory/swap is available.  I am assuming the card is not full?

Note: that because of system write caching the first tranche of files will appear to copy very quickly but once the cache is full the speed will drop drastically and Files may appear to make no progress for quite a long time.  You should still be able to cancel though.

I'll try to reproduce

**Comment by artemanufrij** [comment] 2018-10-30 17:45
Hey @jeremypw! yes, they are a lot of files. Process uses 0% cpu and htop doesn't show any trafic. Files doesn't freez and works as expected. The card ist not full :smile:. I copied all the files successful on loki. 
If you need more information, so let me know it...

**Comment by jeremypw** [comment] 2018-10-30 18:32
You say "Files doesn't freeze" -  so the progress window just remains on screen while you can continue to use Files as normal?  The progress window isnt modal so it is expected to be able to start several file operations sequentially and they will just add to the window.  If a file operation stalls for some reason I suppose the window would just stay open, but I would expect the cancel button to work.   Can you start and other file operations (using different devices) when the progress window is stuck open and do they appear in the progress window and are they cancellable?

I'll see if there is anything in the code that would make the cancel button unresponsive.  Probably should have some timeout on stalled file operations.

**Comment by artemanufrij** [comment] 2018-10-30 20:20
Cancel button doesn't work. If I start copying second time, then copy dialog shows two bars. and the second process works for a time. And it's not possible to close copy dialog by press ctrl+f4

**Comment by jeremypw** [comment] 2018-10-31 08:40
OK, thanks.

**Comment by jeremypw** [comment] 2018-10-31 09:50
An initial look at the code suggests that if an io operation hangs or blocks at a system level (e.g. in gvfs?) then even though the operation cancellable is cancelled, the code that checks for this Files is never reached.   A similar situation occurs in loading directories.  In that case an extra timeout was inserted in Files to forcibly abandon the operation if io blocks too long.

**Comment by jeremypw** [comment] 2018-10-31 11:15
If possible, could you check whether this (the stopping of progress, not the cancel problem) only occurs between the two devices mentioned?   Try copying from samba share to a local directory and then separately copy to the SD card.  Files is (theoretically) agnostic about the source and destination devices when copying so if it only affects certain devices it is probably an upstream or configuration problem.

**Comment by jeremypw** [comment] 2018-10-31 11:20
This looks like a duplicate of #128

**Comment by danrabbit** [comment] 2020-01-03 06:49
Closing as a duplicate

**Closed by danrabbit** 2020-01-03 06:49 UTC
Labels: Status: Duplicate
