### ISSUE TITLE
Remember Password forever does not work on remote volumes

### ISSUE THREAD

**Issue by MerlinElMago** [elementary/files#1244] opened 2020-02-27 09:33 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.
This bug is similar to #934 but neither is the scenario the same nor is the solution acceptable.

## Describe the bug
When connecting to a auto discovered network server over AFP, files will ask me for a password when connecting to the server. Then I am asked a second time when connecting to a share (which is annoying, but as said in #934 probably is due to the underlying system requirements - it would be fantastic although if this could be fixed). Both times I always choose "Remember forever". But the next time I connect to the server I am asked for my credentials again.

### Expected behavior
I expect the server I specified the password for and marked "remember forever" tu do just that... remember it forever ;)
It is not acceptable in my scenario to bookmark the server as I have various dozens of servers and shares to connect to and it would be a complete mess to bookmark all of them.

## Platform and additional Information
elementary OS 5.1 Hera updated to latest in a mixed office sharing network with mostly Macs and Synology Diskstations.
- [X] I'm using the latest released stable version of files

Best regards
Merlin

**Comment by jeremypw** [comment] 2020-02-28 09:40
I find that if I log onto an AFP server, I get a system dialog asking for a password and offering to remember forever (or just for session or not at all).  I choose forever.  This does not create any new network location in the sidebar (not entirely sure why).  Closing Files at this point does not lose the password - it can be reopened and this server can be accessed without reentry of password.  However, rebooting does lose the password.  Not sure if this is a Files or a gvfs issue - I'll look into it when I have time.

**Comment by jeremypw** [comment] 2020-02-28 09:46
Logging out also losses password but not suspending.  So looks like "forever" == "for session".

**Comment by MerlinElMago** [comment] 2020-02-28 10:32
>Closing Files at this point does not lose the password - it can be reopened and this server can be accessed without reentry of password.
While this is true for a server, it does NOT work for a share!

Best regards

**Comment by jeremypw** [comment] 2020-02-28 12:24
Another oddity with server login is that even if you choose "Forget immediately" you can close Files (including killing the Files daemon) and you are still logged in on reopening Files. I think this is a system "feature".

**Comment by jeremypw** [comment] 2020-02-28 12:31
Logging into my AFP server using Nautilus also shows the same behaviour (forgetting password even when "remember forever" is chosen) so I do no think this aspect is a Files issue.  However,  remembering share passwords still might be.

**Comment by jeremypw** [comment] 2020-02-28 12:41
The server password problem has occured on other distros there is a sort of workround here:
https://forums.linuxmint.com/viewtopic.php?t=197068

**Comment by MerlinElMago** [comment] 2020-02-28 19:02
> Another oddity with server login is that even if you choose "Forget immediately" you can close Files (including killing the Files daemon) and you are still logged in on reopening Files. I think this is a system "feature".

Haha.... never tried that one out...

>Logging into my AFP server using Nautilus also shows the same behaviour (forgetting password even when "remember forever" is chosen) so I do no think this aspect is a Files issue. However, remembering share passwords still might be.

Well, under Xubuntu and Regolith (both Ubuntu based) this did not happen...

> The server password problem has occured on other distros there is a sort of workround here:

I still think that the solution proposed here is not acceptable, specially if you have multiple servers to gather data from.

Best regards

**Comment by dsancheznet** [comment] 2020-05-01 13:06
Is there any news on this?

I have been testing many other distros with different filemanagers, and none showed this behaviour.

I believe that this is a quite important bug.

Best regards

**Comment by jeremypw** [comment] 2020-05-02 15:43
One way to avoid having to enter the password twice for an AFP share is to bookmark the root folder of the share.  Opening that bookmark only asks for the password once for some reason (assuming the server password and share password are the same).

**Comment by jeremypw** [comment] 2020-05-02 15:47
@dsancheznet Were the other distros/filemanagers you tested using the same versions as in Ubuntu Bionic?  Last time I looked at this I concluded that it was mainly a system issue so it may have been fixed in more recent system libraries.  I found the Bionic version of Nautilus had the problem.

**Comment by dsancheznet** [comment] 2020-05-02 17:06
I believe they were based on Ubuntu 18.4. With Regolith that was the case for sure (back then when I tested it), but others I would have to look closely into the specs. 

Do you think on the other hand that in more recent versions of Ubuntu, the problem is fixed? 

Regards

**Comment by jeremypw** [comment] 2020-05-03 08:16
I have noticed that the address generated directly by the "ConnectServer" dialog is different from that generated by navigating from a view of the network.  In the latter case, the address omits the username.  This could explain why it keeps asking the password.  Sorry not to have noticed this before - will try to fix soon.   In the meantime - always use the "ConnectServer" dialog to open a view of the location you want (checking "Remember Password) and then create a bookmark to it (which will contain the correct address).

**Comment by jeremypw** [comment] 2020-05-03 09:02
The problem seems to be with the GLib.FileAttribute.STANDARD_TARGET_URI returned for a location on an AFP server - the username is stripped out for some reason.  I'll try and workaround this.

**Comment by dsancheznet** [comment] 2020-05-03 15:10
Thanks a lot. 

Regards

**Comment by jeremypw** [comment] 2020-05-03 15:53
@dsancheznet  If you (or anyone affected by this issue) are able to build and test the linked PR #1315 that would be helpful.

**Comment by dsancheznet** [comment] 2020-05-03 16:14
Just built it and have the following behviour (which solves partially the problem, but not completely):
· Open files
· Search AFP network
· Double click on volume ↦ Password Dialog opens
· Put in my credentials, checking remember forever
· Get a list of shares
· Click on one share ↦ Password Dialog opens
· Put in my credentials (second time...which is kind of annoying) checking remember always
· Share opens and all files are visible
· Logout from share
· Search my AFP network
· Double click on share
· **NO CREDENTIALS ARE ASKED FOR** (until here, it's ok)
· Click on share
· Asked for my credentials again (undesired behaviour)

Best regards

**Comment by jeremypw** [comment] 2020-05-03 16:46
Thanks for testing. You should create the initial server connection using the "ConnectServer" dialog not by clicking on an AFP server in the network view (I'll have to think about how to fix that issue) because that way the correct initial uri is generated.  You can check whether you have the correct uri by looking at the pathbar.  The second breadcrumb should read `<user>@<host>`.  

At the moment the fix propagates the user name from an initially correct connection.  If you click through from the network:// view there is no user name to propagate, so I'll have to insert the current user name I guess.  This assumes that the required user name on the AFP server is the same as the current user name though.

**Comment by dsancheznet** [comment] 2020-05-03 16:52
> You should create the initial server connection using the "ConnectServer" dialog not by clicking on an AFP server in the network view

OK will do that, although this behaviour is not precisely user friendly. If we pretend that average Joe is to use Linux ( did somebody say "This is the year of Desktop Linux? ;) ) we can't tell him NOT to use the list of servers.

> At the moment the fix propagates the user name from an initially correct connection. If you click through from the network:// view there is no user name to propagate, so I'll have to insert the current user name I guess[..]

Or maybe just "remember" that we already have a username and password for that server.

>  This assumes that the required user name on the AFP server is the same as the current user name though.
In my case, the username is the same, but the password is different.

Regards and thanks for taking time to look into it.

**Comment by jeremypw** [comment] 2020-05-03 17:46
@dsancheznet  I have updated the PR to deal with clicking on network:// view.  Its a bit hacky but seems to work.  (Note. it does not matter that the local password is different from the afp server password - we are only assuming the username is the same).

**Comment by dsancheznet** [comment] 2020-05-03 18:39
Works perfectly! 

Haven't rebootet my computer yet (can't do it right now) so will report back as soon as I did that.

Thanks a lot!

**Comment by dsancheznet** [comment] 2020-05-05 08:24
Was able to reboot and it still works.

Good job.

**Comment by jeremypw** [comment] 2020-05-05 08:33
Thanks for letting us know.  If you could comment on the PR page as well that might help get it reviewed and merged.

**Closed** 2021-04-02 18:06 UTC
