### ISSUE TITLE
keyboard shortcuts view not work

### ISSUE THREAD

**Issue by TheRock892** [elementary/files#1487] opened 2020-09-28 08:07 UTC
it does not work change view with keyboard shortcuts ctrl + 1, ctrl + 2, ctrl + 3

**Comment by TheRock892** [comment] 2020-09-28 08:09
duplicate

**Comment by jeremypw** [comment] 2020-09-28 08:56
Duplicate of #1476

**Comment by jeremypw** [comment] 2020-09-28 08:57
PR #1479 fixes this.

**Closed by jeremypw** 2020-09-28 08:57 UTC
Labels: Status: Duplicate
