### ISSUE TITLE
Mouse button lockup when dragging files between Files windows on same file system

### ISSUE THREAD

**Issue by CosCal** [elementary/files#1130] opened 2019-12-21 23:17 UTC
While moving files between two windows, the mouse copy icon will get stuck intermittently.
![20191221_174917](https://user-images.githubusercontent.com/34515453/71314830-1e0cde00-241e-11ea-8981-2aa77ad156b6.jpg)

The mouse will still move around the screen, however clicking on items becomes impossible.
Keyboard still works, and Alt+F4 closing all instances of the Files app windows (sometimes unfortunately also first closing all other apps) will usually release the animation (restoring mouse functionality). On a few occasions, logging out of the session is the only remedy.
Problem has been around since at least during mid-Juno release.

It is a possibility that the built-in Archive Manager app could be involved, as that was what was being used during today's lockups. However I noticed it lock up while the Archive Manager was not launched. A full reboot and system update has still not solved this issue.
The situation could not be recreated on command, so it's possible that the travel path of the mouse was over something in the side bar that I cannot for some reason recreate precisely.

**Comment by jeremypw** [comment] 2019-12-22 17:47
@CosCal Thanks for the report. Presumably you are moving between two different file systems as the default for the same filesystem is to move the file? (To copy when dragging to the same filesystem you have you have to drag using the secondary button and choosing "Copy" from the menu). 
When the issue occured, were the two filesystems local or is one or more remote? What formats were they?   DId you use the auto-open function (hover over folder to open it)?  Any other relevant info e.g. Were you moving one or multiple files?  Small or large?  (May or may not matter but the more info the better).

**Comment by jeremypw** [comment] 2019-12-22 17:52
Maybe related to #1082 

There is a branch aimed at fixing this but has not been proposed for merging yet (waiting for merge backlog to diminish).

**Comment by jeremypw** [comment] 2019-12-22 17:57
May be duplicate of #890 

There are two or three branches related to DnD but not currently up for review.

**Comment by CosCal** [comment] 2019-12-23 14:38
This was happening on the SAME filesystem, mostly within the same user home directory.
This is also happening still after a semi-recent reinstallation of elementary. No remote shares used. There are three drives on SATA. All partitions involved, as my memory and a quick check showed, were ext4. The only other partitions used on this pc are hfs+ and fat 32 formatted, but those were copy from and never copy to operations. (importing from a previous installations/computers)
The repeated issue i had listed above, that led me to search for elementary support, was supposed to be a move operation (not copy) on the same drive, with ext4 in use. The only copy operation was between ext4 partitions while i was consolidating files. (Now that we brought up copy vs move, I'm wondering if previous ones were also move only, or possibly were copy between drives?)

This instance involved file types of zip and bin, usually 2-4MB.

Desktop orientation was both 50/50 split-screen left to right mouse dragging and centered window to 1/2 screen window. Destination drag window had 2 tabs open of common root but unique folders. I tried separate windows instead of tabs but encountered the same glitch.
During drag, when passing over the destination window, to the right, it changes to copy and gets stuck.

**Comment by CosCal** [comment] 2019-12-23 15:08
After reviewing the two links to other listings...

I can see # 1082 is similar, but mine also happened while not using archive. So it's not exactly the same.

# 890 varies because for me, alt+tab is functioning during lockup, and regaining control meant blind keyboard navigation through dialog boxes and originally shuttering whatever applications responded by keyboard. I'm unfortunately unfamiliar with his other keyboard shortcut combos as I'm still learning the depth of linux

And to finally answer your question on move quantity, it happened on both single file and group file move operations.

My installation is currently:
Hera 5.1 , 12GB RAM , USB Logitech LX3 mouse , Logitech Y-BF37 keyboard.

**Comment by jeremypw** [comment] 2019-12-23 15:49
@CosCal Thanks for the additional information - that's helpful.  I'll see if I can reproduce.

**Comment by CosCal** [comment] 2019-12-23 18:15
UPDATE:

(Realtime)
![realtime](https://user-images.githubusercontent.com/34515453/71373529-77435180-2585-11ea-8ef6-b046ad6a734b.gif)

(slow motion)
![slowmotion](https://user-images.githubusercontent.com/34515453/71373555-99d56a80-2585-11ea-89a3-11f596b190a9.gif)

OK, so I hope this helps some. Just recreated it during capture. Archive Manager was opened moments before, extracted single file to right window, and dropped over folder of choice. Closed Archive Manager. Previous Zip was still highlighted. Left Click Hold on new file (.bin extension) then the moments caught in GIF file above played out. Alt-F4 to close BOTH windows, then mouse returned to normal.

**Comment by jeremypw** [comment] 2019-12-23 19:26
This sounds very similar to #1082

**Comment by CosCal** [comment] 2019-12-23 21:08
Thank you.
Yeah, I've been trying to trigger it without zip decompression apps, and I was not able to recreate it without dragging. I tested Xarchiver app too. It happens right after a decompression drag and drop, but oddly NOT after an extract using the apps internal directory finder.
Again, thank you for taking time to untangle this mess. It's deeply appreciated!

**Comment by jeremypw** [comment] 2019-12-24 09:43
#1133 will hopefully fix this issue as well as #1082

**Comment by jeremypw** [comment] 2019-12-24 18:12
The drag out of archive fix has just been merged into master.  If you are on stable repository please compile master from source and try it out (if you are abel). Otherwise will have to wait until next stable release.  I am going to close this for now.  If after trying the fix you still have problems please feel free to reopen.

**Closed by jeremypw** 2019-12-24 18:12 UTC
