### ISSUE TITLE
Allow disabling single click to open on folder

### ISSUE THREAD

**Issue by undergroundwires** [elementary/files#1960] opened 2021-12-26 00:00 UTC
### Problem

Single click on folder opens it.

`gsettings set io.elementary.files.preferences single-click false` does not work anymore. There seems to be no way of going around this while using elementary OS/files.

**Background**
Sometimes I need rename many folders one by one. This is simply too challenging with what current UX offers.

It is frustrating to click on a folder to rename, then go back, then rename it. Trying to click on the blue tick is not so productive when you need to be fast to get things done but also be pixel perfect.

### Proposal

Introduce a setting to disable single click to open folder.

**Comment by jeremypw** [comment] 2021-12-27 15:46
There are couple of discussions at https://github.com/elementary/files/discussions covering the disadvantages of having only one selection mode.  Certain operations need a different way of working but can still be done efficiently - if they cannot we will iterate on the selection mode until they can.  In this case it seems to be the problem is that after renaming the renamed item does not remain selected after naming - which I think is a regression.  When that is fixed, you can just press the right-arrow to move the selection to the next item and then F2 to rename it.  I agree you do not want to have to keep switching between mouse and keyboard.

**Comment by jeremypw** [comment] 2021-12-27 16:52
You could also consider installing a bulk renamer program if you are doing a lot of renaming. There is at least one free one in the AppCenter.  I started work on a bulk renamer plugin for Files (see https://github.com/jeremypw/bulk-renamer-plugin) but haven't got round to submitting it yet.

**Comment by jeremypw** [comment] 2021-12-27 16:54
Another possibility would be for Files to modify the rename mode when there is a multiple selection so that after renaming the first item the next selected item enters rename mode.

**Comment by rdanter** [comment] 2021-12-29 15:09
I know it was a design decision to remove the option to have double-clicking to open files/folders, but for someone who often switches between eOS, macOS and various other Linux distros (for both work and personal), I find it really frustrating to have just eOS work this way.

I don't have a problem with this being the default, but for usability it would be really nice to have it optional.

**Comment by jeremypw** [comment] 2021-12-30 10:05
I understand but it is unlikely that design decision will be reversed any time soon. You could consider using list view as standard as the area where folders can be selected with a single (unmodified) click is much larger than in grid view (just avoid clicking on the filename column).  It would be possible to increase the size of the helper to make it much easier to select folders I guess.  I'll push a PR some time and see what the design team think.

I am not sure what macOS does with modified clicks but you might be able to use `<Alt>Click` or `<Ctrl>Click` on both to select folders.

**Comment by rdanter** [comment] 2021-12-30 12:54
> I understand but it is unlikely that design decision will be reversed any time soon.

That's what I thought, but having the option, even if not the default, would still be very much appreciated I think.
 
> I am not sure what macOS does with modified clicks but you might be able to use `<Alt>Click` or `<Ctrl>Click` on both to select folders.

Like I said, it's not just macOS, I use several different Linux distros too and none of them use a sing;e click to open a folder.

**Comment by jeremypw** [comment] 2021-12-30 16:44
My point was that if you get into the habit of using e.g. `<Alt>Click` to select a folder then you could maybe use that on all OSes you use.

I notice that double-clicking a folder with Files results in *two* single clicks so may result in navigating two folders deep - which is not intended.  I'll raise an issue about that.

**Comment by rdanter** [comment] 2021-12-31 08:34
Thank you for taking the time to reply @jeremypw , much appreciated. I will try your suggestions.

**Comment by cvpsmith** [comment] 2022-01-02 06:08
I would strongly suggest re-implementing this as well.  Lack of the double-click option is basically a deal-breaker for me; I had to switch from eOS to Pop!_OS specifically due to this change (I tried using Nemo instead of Files, but it didn't integrate as well for me).

Single-click just doesn't work well for covering all use-cases.  In MacOS this is handled very simply, IMO: double-click is the default (only) behavior for Icon View and single-click is the default for Tree View.  Best of both worlds and, best of all, choice in the matter.  There's a reason why both Windows 10 and MacOS use the double-click behavior in Icon View by default.  

I'm guessing that you may be losing a great many potential paying users (such as myself) without even realizing it (since we usually simply evaluate and move on), and the real shame of it is that there is a very simple fix.  You may think of this as a small (non-)issue but the fact of the matter is, the double-click option is a VERY big deal to a great many users...

**Comment by andrewdbate** [comment] 2022-01-09 21:47
Sadly, the project won't just lose users, it will also lose sponsorship. I had planned to sponsor the project this year but now won't.

I was going to sponsor at the $50 per month tier because I could ask for a bug to be looked into once per month, but after I saw the way the single-click issue was handled, I decided not to. Instead I have spent my time porting/integrating Nemo, which is mostly stylesheet fixes.

**Comment by jeremypw** [comment] 2022-01-10 18:12
I have pushed a PR to fix this, but it is uncertain whether it will be accepted.

**Comment by undergroundwires** [comment] 2022-01-20 18:55
Both suggestions from @jeremypw solves the case for me:

- Using keyboard
- ALT+Click

But they're not as convenient. Maybe it's because I also use Windows/macOS daily.

Just like @cvpsmith . I moved to third party file managers due to this but they do not integrate so well with OS6 (opening in terminal etc) and I tested almost all major ones. And I'm now considering switching distro due to this, most likely to Pop!_OS.

An OS file manager is one of the key areas to be most productive so even tough maintainers do not agree, please let us override this configuration.

Out of topic but I love your bulk renamer plugin @jeremypw . It would be great to see it integrated in Files. Thank you for your time, offering a lot of workaround and even code solutions. Thank you for being here, reacting quickly, listening and maintaining these, you make a difference so you know.

**Comment by undergroundwires** [comment] 2022-01-20 18:56
Both suggestions from @jeremypw solves the case for me:

- Using keyboard
- ALT+Click

But they're not as convenient. Maybe it's because I also use Windows/macOS daily.

Just like @cvpsmith . I moved to third party file managers due to this but they do not integrate so well with OS6 (opening in terminal etc) and I tested almost all major ones. And I'm now considering switching distro due to this, most likely to Pop!_OS.

An OS file manager is one of the key areas to be most productive so even tough maintainers do not agree, you should let us override this configuration.

Out of topic but I love your bulk renamer plugin @jeremypw . It would be great to see it integrated in Files. Thank you for your time, offering a lot of workaround and even code solutions. Thank you for being here, reacting quickly, listening and maintaining these, you make a difference so you know.

**Comment by jeremypw** [comment] 2022-01-21 10:51
@undergroundwires Thanks for the appreciation! I do think that accommodating users who need to frequently switch between elementary and Windows is perhaps the most convincing reason to maintain a double-click to open option.

**Comment by lilly-lizard** [comment] 2022-08-24 09:59
I totally thought this was a bug and wouldn't have guessed it's the intended behavior. Needing to use `<Alt>Click` to select is very un-intuitive imo, even if we lived in a world where every other file manager/OS didn't have the single/double click way of doing things...

Thanks for the PR @jeremypw! Really hope it gets merged before next release 🤞

**Comment by jeremypw** [comment] 2022-08-24 11:19
Thanks @lilly-lizard .

**Comment by jeremypw** [comment] 2022-08-24 11:21
If there are no objections in the next couple of weeks, I'll merge the PR into master and see what happens.

**Closed** 2022-09-30 16:26 UTC
