### ISSUE TITLE
Display dock on all extended displays

### ISSUE THREAD

**Issue by kryptoatom** [elementary/files#1775] opened 2021-08-01 22:46 UTC
## Problem
Working on multiple display but dock is accessible only on primary display. Even though there is an option to have dock displayed on secondary display but it would be nice to have it on both rather than only one display at a time.

## Proposal
Dock should be visible on all displays.

## Prior Art
Windows has this feature where taskbar is visible on all extended displays

**Comment by jeremypw** [comment] 2021-08-02 08:27
@kryptoatom Hi, thanks for the report.  However it does not really belong in the Files project and is a duplicate of this issue: https://github.com/elementary/dock/issues/71.  So closing.

**Closed by jeremypw** 2021-08-02 08:27 UTC
Labels: Status: Out of Scope
