### ISSUE TITLE
Clicking between file thumbnail and filename does not select the file while in grid view

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/files#1302] opened 2020-04-26 19:12 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Clicking between a file's thumbnail and the filename doesn't select the file and seems like a dead-zone when in grid view(see cursor in screenshot). However, clicking on the buffer region in list view seems to work perfectly fine.

![file_dead_zone](https://user-images.githubusercontent.com/46734097/80317060-c234d600-87be-11ea-812d-733feb92dba0.png)

### To Reproduce
1. Go to Files, switch to Grid View.
2. Click on the buffer zone between the file thumbnail and filename.
4. See error (i.e. file is not selected)

### Expected behavior

The file should be selected even when clicked on the gap between thumbnail and filename.

## Platform Information
 - elementary OS Hera 5.1.3
 - Files version 4.4.2
 - Hardware info: Dell XPS 13 9380

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

This problem occurs only in Grid View, not in List View.

**Comment by jeremypw** [comment] 2020-04-27 08:35
Confirmed. This is most noticeable for images that are smaller than the current icon size - for images that fill the full icon height it is negligible.  In List View, the item only activates when the pointer is over the visible image or text but the row does select when clicking on the blank space.

**Comment by jeremypw** [comment] 2020-04-27 09:12
After further investigation, this is a consequence of a hack that allows rubberbanding to commence by dragging between the icon and the name (it fakes a click outside the icon). If this hack were to be removed then you could select/activate by clicking on this region.  I gues that, for consistency with ListView, the area between the icon and the name should be activatable but I am concerned that it would be less obvious on IconView for which areas a drag will commence rubberbanding and for which it will drag the file item.  At the moment _all_ white space commences rubberbanding.  Design input required.

**Comment by jeremypw** [comment] 2020-04-27 11:12
There are some frustrating differences in the way Gtk.IconView and Gtk.TreeView work that makes it difficult to make the behaviour the same as IconView.  In particular `gtk_tree_view_is_blank_at_pos ()` does not seem to work exactly as documented and does not always return `true` even for areas that are visibly blank, including that between the icon and the text renderers.  Whereas documentation says the function returns the cell renderer relative position, it in fact returns the column relative position.  So if they are to behave exactly the same we would have to make the inter-renderer region activatable rather than rubberbandable. Maybe the activatable blank areas can be subtly shaded to distinguish them from the rubberbandable blank areas?  The cursor shape does change but this is not very noticeable and requires the areas to be probed to discover their properties.

**Comment by vikasnataraja** [comment] 2020-05-03 19:07
I noticed something interesting - clicking on that "dead zone" area doesn't select the file but if the file is already selected, clicking on that same area unselects the file. I assume this is because after the file is selected, it becomes a singular boxed area and clicking anywhere inside that box unselects the file but I could be wrong.

**Comment by jeremypw** [comment] 2020-05-04 08:04
@vikasnataraja Its because, at the moment clicking on the dead area has much the same effect as clicking on the background of the view, which also deselects any selected files.   If the linked PR #1311 were to be merged then this dead area would behave the same as clicking on the icon image or the name text.

Please build and text this PR if you are able.

**Comment by cmburg** [comment] 2020-06-25 05:14
>     * [x]  I have searched open and closed issues for duplicates.

I think this is a duplicate of https://github.com/elementary/files/issues/884

**Closed** 2020-11-05 11:50 UTC
Labels: Needs Design, Status: Confirmed
