### ISSUE TITLE
Ctrl+C, Ctrl+V, etc do not work on internationalized layouts

### ISSUE THREAD

**Issue by tetebueno** [elementary/files#257] opened 2017-12-03 17:20 UTC
Ctrl+C, Ctrl+V, and probably other keyboard shortcuts do not work on internationalized layouts.
For example, it works on English layout, but doesn't work if I switch to Spanish Dvorak layout.
This bug was reported and fixed on [Launchpad bug #1405315](https://bugs.launchpad.net/pantheon-files/+bug/1405315). It's happening again in Elementary OS Loki.

Files version: 0.3.5
Kernel version: 4.10.0-40-generic

**Comment by jeremypw** [comment] 2017-12-04 19:33
I find that although it does not work for Spanish Dvorak layout, it still works for Russian layout (which was the original bug). Will investigate.

**Comment by jeremypw** [comment] 2017-12-04 19:53
So, when using a Spanish Dvorak layout, which key would you expect to press for "copy"?  Is it the one in the same position as "C" on a standard English keyboard (which is "k" on a Spanish Dvorak) or is the one marked "C" (below the "8" key)?

**Comment by tetebueno** [comment] 2017-12-04 20:01
According to previous behavior, pressing the one below the "8" key would trigger the "copy" action. And so on for the rest of the keys.

**Comment by jeremypw** [comment] 2017-12-04 20:11
OK. thanks.  I checked some sites and apparently the Mac had a Dvorak system where when the "command" key was pressed, the keyboard acted like QWERTY.  Is this preferable?  Some people say that the position of the "C" on the Dvorak layout is inconvenient.

**Comment by jeremypw** [comment] 2017-12-04 20:12
What about other hot keys like <Ctrl>N and <Ctrl>T?

**Comment by tetebueno** [comment] 2017-12-04 20:15
I believe that'd be a matter of taste. It's hard to sound unbiased now, but I'd go for existing behavior and, when it's fixed, face the improvement of a Mac-like mechanism if it's worth it.

**Comment by tetebueno** [comment] 2017-12-04 20:17
Regarding `<Ctrl>N` and `<Ctrl>T`, that'd also be `<Ctrl>L` and `<Ctrl>K` speaking in QWERTY. Again, it's a matter of taste by now. Personally speaking, after a couple of years using Elementary OS with such keyboard layout, is not a problem anymore to me.

**Comment by jeremypw** [comment] 2017-12-04 20:31
OK, you are right that the priority is to restore existing behaviour.

**Comment by jeremypw** [comment] 2018-09-04 12:33
Need someone with an affected keyboard to test out the fix (#360).

**Comment by tetebueno** [comment] 2018-09-04 14:58
I'm in. Once I'll have the chance to give it a try I'll let you know.

Should I assign it to me?

**Comment by jeremypw** [comment] 2018-09-05 10:17
@tetebueno Thanks! I do not think the bug review can be formally assigned to you unless you have write permission (you do not seem to be in the list that pops up) but please do leave a review at  #360 - it will be very helpful as it looks like none of the elementary team have a relevant keyboard.

**Comment by tetebueno** [comment] 2018-09-08 17:49
Ok, looks like we're dealing with a noob here. I've never installed this project from source but I'd like to start contributing in this kind of projects, so I'm having the following issue: after making sure all dependencies mentioned in README file are installed I get the following error when running cmake:

```
~/files/build$ sudo cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- checking for a minimum Vala version of 0.34.0
--   found Vala, version 0.36.15
-- Checking for modules 'granite>=0.3.0;glib-2.0>=2.29.0;gthread-2.0;;gio-2.0;gio-unix-2.0;pango>=1.1.2;gtk+-3.0>=3.22;gmodule-2.0;gail-3.0;gee-0.8;sqlite3;dbus-glib-1;libbcanberra>=0.30;zeitgeist-2.0;plank'
--
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/ModulesFindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:54 (pkg_check_modules)
```

-- Configuring incomplete, errors occurred!

I couldn't find any additional info in CMakeOutput.log either.
I haven't been able to locate gthread, gio-unix and gmodule packages, but as far as I could find out in the interwebs those are part of glib-2.0.

Any ideas on what I might be doing wrong? Also, let me know if I should be asking this somewhere else.

Cheers.

**Comment by jeremypw** [comment] 2018-09-10 09:37
What system are you compiling on?

**Comment by jeremypw** [comment] 2018-09-10 09:39
It's odd because cmake should normally tell you which package was not found.

**Comment by tetebueno** [comment] 2018-09-11 01:34
So, I do had build-dep and build-essential packages. Also, all mentioned packages were their -dev versions.

Here's the information of the system I'm working on:

```
~$ uname -a
Linux PC 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~$ lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 0.4.1 Loki
Release:        0.4.1
Codename:       loki
```
I'll give it a try on using juno repositories (I'll first find out how to add the repos).

Thanks for the patience.

**Comment by jeremypw** [comment] 2018-09-11 12:07
If you are on Loki repos then it is most probably a dependency version problem.  Thanks for persevering with this.  I would not recommend installing the unstable repositories on an essential machine unless you have a backup Loki install on another machine or partition (in which case better to install the Juno beta iso).

**Comment by tetebueno** [comment] 2018-09-18 02:06
I work on a virtualbox for these things. I'll create a Juno beta machine for this now that I have the chance. I'll let you know how it goes.

**Closed** 2018-11-02 01:56 UTC
Labels: Status: PR under review

**Comment by jeremypw** [comment] 2019-01-21 12:01
@soutone: Thanks for the info.  I must admit I do not test Files with "Reveal pointer" activated - I guess I should if it turns out to have an effect.  I will check this out and raise another report if appropriate.

**Comment by jeremypw** [comment] 2019-01-21 12:02
By the way, there has been a recent regression affecting "paste" where the pasted item does not appear until the view is refreshed, although the file operation does succeed.

**Comment by alshenetsky** [comment] 2019-01-24 12:06
Sometimes I experiencing the same problem using Russian layout.

**Comment by Taalaybek** [comment] 2020-10-17 10:55
> I don't know if this is relevant for this thread but I was having similar problems (could not copy and paste in the directory bar using CTRL+C and CTRL+V) and now I find that it works perfectly after deselecting the "Reveal pointer" option on System Settings > Mouse & Touchpad. I am using a Portuguese layout.

thank u, it works for me
