### ISSUE TITLE
Add "New folder with Selection" in context menu

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#927] opened 2019-04-21 04:35 UTC
GNOME's file manager has this excellent feature where after you make a selection of files, the context menu has the option to make a new folder with the selected items. Upon clicking it, the folder is asked to be named, the folder is then made and the selected files are put in it automatically.

![photo_2019-04-21_10-01-27](https://user-images.githubusercontent.com/22585732/56465522-79647780-641c-11e9-836e-f36e2a2463aa.jpg)

**How is this better than regular cut-paste?**
It is reducing the number of steps to achieve the same result. 

_Current behavior_
1. Select files
2. "Cut" them
3. Create new folder
4. Name the folder
5. Enter the folder
6. Paste the files

_Proposes behavior advantage_
1. Select files
2. Select "New folder with Selection" in the context menu
3. Name the folder
4. Hit Enter

That's it!

**Comment by jeremypw** [comment] 2019-04-21 17:57
A PR providing this was submitted sometime ago but not accepted (I forget why exactly).

**Comment by jeremypw** [comment] 2019-04-21 18:02
This is a duplicate of #346 I think.

**Comment by jeremypw** [comment] 2019-04-21 18:07
I would be willing to implement this but there are already a large number of PRs awaiting review so I am reluctant to add to the backlog.

**Comment by danrabbit** [comment] 2020-01-04 02:30
Closing since this is a duplicate of #346

**Closed by danrabbit** 2020-01-04 02:30 UTC
Labels: Status: Duplicate
