### ISSUE TITLE
Focus bugs when selecting with the keyboard in Icon View

### ISSUE THREAD

**Issue by jlnr** [elementary/files#330] opened 2018-02-13 09:27 UTC
1. Enter a folder with several icons (four in my case) in Icon View
2. Select all of them using the mouse (I do so from right to left)
3. Press the left arrow key. Now the right-most icon is selected (bug 1?)
4. Press F2 to rename. Nothing happens (bug 2)
5. Press left to select the next icon.
6. Press F2 to rename the right-most (wrong) icon (bug 3)

Possibly related to #87 which was also about icon order and renaming.

Let me know if I should upload a GIF of this.

**Comment by jlnr** [comment] 2018-02-13 09:28
Sometimes step 3 results in three icons being selected (shrinking the selection), instead of one.

**Comment by jlnr** [comment] 2018-02-13 09:29
Reproduced both on stable Loki (0.4.1) and master.

**Comment by jeremypw** [comment] 2018-02-13 10:16
Thanks for pointing this out.  Regarding Bug 1 I guess part of the problem is that in Icon View, the cursor position is not distinguishable when there is multiple selection (unlike List View) so it is not obvious what will happen when an arrow key is pressed.  But you are right that what does happen is not always correct anyway.  I guess it should be the same as in List View, that is the cursor should move from its current position and other selected items be deselected?  This bug only seems to affect Icon View

The rename problems are related to keyboard selection and are confirmed. They affect all views so is likely to be a separate issue - I'll open another report.

**Comment by jeremypw** [comment] 2018-02-13 10:29
Actually the cursor position in Icon View multiple selections can be discerned - the color is a slightly brighter blue, but it is not obvious.

**Comment by jlnr** [comment] 2018-02-19 12:56
#333 fixes most of this, except part 3:

> Press the left arrow key. Now the right-most icon is selected (bug 1?)

This is still "buggy" from my initial perspective. If I open a fresh window containing three icons, select the one in the middle *using the mouse*, then press the left arrow key, I would expect the icon on the left to be selected. What happens is that Files selects the one on the right.

However, I just realized that this works as designed, so I'll spell it out: Selecting items with the mouse does not change the position of the *keyboard cursor*. Pressing the left arrow when there is no cursor moves the cursor to the last item on the list, and then selects this item. The F2 shortcut to rename icons does not operate on the keyboard *cursor* like the arrow keys, but instead renames the *selected* item.

Thinking about it, I think my expectation was that selecting icons using the mouse *also* moved the keyboard cursor to the (end of the) selection, in the same way that selecting text moves the keyboard cursor as well, but maybe I was misled by the styling, for which I've opened (repurposed) #332.

**Comment by jeremypw** [comment] 2018-02-19 13:34
@jlnr:  Thanks for testing this PR out.  I also noticed the issue with mouse selection and keyboard cursor.  I have addressed this separately in PR #340.

**Comment by jlnr** [comment] 2018-02-19 13:54
I've also tried #340 but wasn't sure if I understood the behavior, I'll comment on the PR.

**Comment by jeremypw** [comment] 2018-09-04 12:26
I am going to close this as I think most of the issues mentioned have been addressed.  Please open new single issues if necessary.

**Closed by jeremypw** 2018-09-04 12:26 UTC
