### ISSUE TITLE
Improve search discoverability and UX

### ISSUE THREAD

**Issue by alexgleason** [elementary/files#611] opened 2018-08-29 17:34 UTC
The search feature is critical for any user who stores more than a few files on their machine and wants to use a graphical UI to find them. Windows and MacOS handle this very well, as do most popular Linux distros. This is a place where I see a possibility for major improvement for elementary OS.

# 1. Search feature is not easily discoverable

When looking for the search feature, I do not know where to find it:

![screenshot from 2018-08-29 13 22 10](https://user-images.githubusercontent.com/3639540/44804169-95b25c00-ab8e-11e8-9673-a2a14945cb71.png)

It is found by putting your cursor in the address bar, *deleting* the path of the current directory, and then typing a search term and hitting enter.

![screenshot from 2018-08-29 13 23 12](https://user-images.githubusercontent.com/3639540/44804244-c4303700-ab8e-11e8-8d27-c30bebca533a.png)

I think it would be better if there were a dedicated search button like in other file browsers. I could see this making sense either in the toolbar or as a new entry in the sidebar (sort of like "Recent items").

# 2. Search UX could be improved

Once the search feature is discovered, it is often only minimally helpful. For one, it is difficult to navigate. Next, it only does a search within the current directory and doesn't help the user search the whole filesystem.

I wouldn't say that Windows handles this perfectly, but it does do a lot of things that elementary doesn't.

![search results](https://user-images.githubusercontent.com/3639540/44804690-0e65e800-ab90-11e8-88d5-960fbb5297db.png)

I think it is a good thing that searching creates a separate view where files can be interacted with in the normal way. The context is clearly visible, multiple files can be interacted with at once, etc.

**Comment by jeremypw** [comment] 2018-08-30 11:16
Essentially a duplicate of #170, where there is some discussion. Thanks for the detailed report though.

**Closed** 2018-08-31 16:40 UTC
Labels: Needs Design, Priority: Wishlist, Status: Duplicate
