### ISSUE TITLE
Duplicating  mount drive

### ISSUE THREAD

**Issue by udhay-infinite** [elementary/files#1702] opened 2021-05-11 04:38 UTC
----> in files application if you clicking it takes time to launching 
----> mounting drive a duplicate 
![Screenshot from 2021-05-11 10-09-22](https://user-images.githubusercontent.com/60108451/117759208-ff8cca00-b240-11eb-912e-0d36743b71c0.png)

**Comment by jeremypw** [comment] 2021-05-11 08:28
@udhay-infinite Hi, thanks for your report.

There is an existing report about Files taking time to launch for the first time in the session - at https://github.com/elementary/files/issues/1642. Is this the same as the issue you are experiencing?

There is a closed report about Files showing duplicate drives under some circumstances - at https://github.com/elementary/files/issues/1401.  Please could you give more information regarding which version of elementaryos and Files you are using and also about the drive that is shown duplicated.

**Comment by udhay-infinite** [comment] 2021-05-12 05:50
actually this is elementary os 6 early access beta because already i received patch for files still having face some issues's so i posted it  
myfiles is (above screen shot) drive  if mount that drive  files application side bar show duplicate one more entry(i.e it shows two times)
after unmounted drive duplicate entry doesn't close . if closing files application again open it up duplicate entry is gone .(if  if you close and again opening the problem duplicate entry is gone . if mount gain again duplicate entry shown on.

**Comment by jeremypw** [comment] 2021-05-12 09:07
If you are able to build and try out #1607 I would be interested to see whether it fixes your issue.  It is uncertain whether the idea of expandable drive items will be approved but there may be some improvements from that branch that can be included in the existing sidebar.

**Comment by selwynorren** [comment] 2021-06-03 10:21
Howdy,

So I have an fuse formatted USB drive, When I plug it in it is detected and the moment I mount it it then shows duplicate in the sidebar.

When I eject the first of the duplicated devices, it them shows that it has been ejected, however the duplicated USB listing remain active. however when I click on it it says the drive does not exist.

I am running an updated Early Release of Elementary OS 6

**Comment by queeup** [comment] 2021-06-11 19:54
Duplicate of #1665?

**Comment by jeremypw** [comment] 2021-07-29 09:07
Yes, appears to be a duplicate of #1665. 

There is an outstanding PR that may fix this #1752.

**Closed** 2021-07-29 09:08 UTC
Labels: Status: Duplicate
