### ISSUE TITLE
Hovering over items has a flickering effect under various conditions.

### ISSUE THREAD

**Issue by Schyken** [elementary/files#883] opened 2019-02-05 19:14 UTC
I've recently noticed that some directories will exhibit a flickering behaviour when items are hovered over in Files. Some experimenting with other users showed that this tends to happen sometimes when hidden files are toggled on, but the issue seems to disappear when thumbnails are disabled, leaving me to think this may be an issue with the thumbnailer.
An example of the issue here: https://youtu.be/FudbZJzOKBw

System information:
```
System:    Host: schyken-ryzen-horizon Kernel: 4.15.0-45-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Gnome  (Gtk 3.22.30-1ubuntu1) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 4207 date: 12/07/2018
CPU:       8 core AMD Ryzen 7 2700 Eight-Core (-MT-MCP-) arch: Zen rev.2 cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 55894
           clock speeds: max: 3500 MHz 1: 1374 MHz 2: 1329 MHz 3: 1361 MHz 4: 1350 MHz
           5: 1349 MHz 6: 1373 MHz 7: 1376 MHz 8: 1388 MHz 9: 1323 MHz 10: 1333 MHz
           11: 2211 MHz 12: 1437 MHz 13: 1314 MHz 14: 1335 MHz 15: 1307 MHz 16: 1324 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Vega [Radeon RX Vega] bus-ID: 0c:00.0
           Display Server: x11 (X.Org 1.19.6 )
           drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 2560x1440@59.95hz
           OpenGL: renderer: Radeon RX Vega (VEGA10, DRM 3.23.0, 4.15.0-45-generic, LLVM 7.0.0)
           version: 4.5 Mesa 18.2.2 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] Family 17h (Models 00h-0fh) HD Audio Controller
           driver: snd_hda_intel bus-ID: 0e:00.3
           Card-2 Advanced Micro Devices [AMD/ATI] Device aaf8
           driver: snd_hda_intel bus-ID: 0c:00.1
           Card-3 Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series]
           driver: snd_hda_intel bus-ID: 09:00.0
           Card-4 Logitech HD Pro Webcam C920 driver: USB Audio usb-ID: 003-003
           Card-5 C-Media driver: USB Audio usb-ID: 001-002
           Sound: Advanced Linux Sound Architecture v: k4.15.0-45-generic
Network:   Card: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: f000 bus-ID: 04:00.0
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 2250.5GB (4.5% used)
           ID-1: /dev/nvme0n1 model: Samsung_SSD_960_EVO_250GB size: 250.1GB
           ID-2: /dev/sda model: WDC_WDS500G2B0A size: 500.1GB temp: 20C
           ID-3: /dev/sdb model: WDC_WDS500G2B0A size: 500.1GB temp: 18C
           ID-4: /dev/sdc model: WDC_WDS500G2B0A size: 500.1GB temp: 19C
           ID-5: /dev/sdd model: WDC_WDS500G2B0A size: 500.1GB temp: 20C
Partition: ID-1: / size: 224G used: 24G (11%) fs: btrfs dev: /dev/nvme0n1p3
           ID-2: /boot size: 946M used: 151M (18%) fs: ext4 dev: /dev/nvme0n1p2
           ID-3: /home size: 224G used: 24G (11%) fs: btrfs dev: /dev/nvme0n1p3
           ID-4: swap-1 size: 8.01GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 30.5C mobo: N/A gpu: 40.0
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 433 Uptime: 2:50 Memory: 3252.0/32166.0MB
           Init: systemd runlevel: 5 Gcc sys: 7.3.0 Client: Shell (bash 4.4.191) inxi: 2.3.56
```

**Comment by terndrup** [comment] 2019-02-05 19:17
+1 for this issue which I'm also seeing. I'm using an NVIDIA GTX 1070 GPU with proprietary 415 Nvidia driver.

Only happens when toggling on show hidden folders (CTRL+H).

**Comment by DanyGee** [comment] 2019-02-05 19:23
Confirming this on my machine too.
```
System:    Host: elementary-os Kernel: 4.15.0-45-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Gnome  (Gtk 3.22.30) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: N/A
           UEFI [Legacy]: American Megatrends v: 3504 date: 06/29/2017
CPU:       Quad core Intel Core i7-6700K (-MT-MCP-) arch: Skylake-S rev.3 cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 32064
           clock speeds: max: 4300 MHz 1: 4100 MHz 2: 4100 MHz 3: 4136 MHz 4: 4135 MHz 5: 4100 MHz 6: 4100 MHz
           7: 4135 MHz 8: 4109 MHz
Graphics:  Card: NVIDIA GP104 [GeForce GTX 1080] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) driver: nvidia Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 version: 4.6.0 NVIDIA 410.78 Direct Render: Yes
Audio:     Card-1 NVIDIA GP104 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.15.0-45-generic
Network:   Card-1: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Broadcom Limited BCM4360 802.11ac Wireless Network Adapter
           driver: bcma-pci-bridge bus-ID: 07:00.0
           IF: N/A state: N/A mac: N/A
           Card-3: Intel I211 Gigabit Network Connection driver: igb v: 5.4.0-k port: c000 bus-ID: 0b:00.0
           IF: enp11s0 state: down mac: <filter>
Drives:    HDD Total Size: 2570.6GB (3.9% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 256.1GB
           ID-2: /dev/sdb model: Samsung_SSD_850 size: 1024.2GB
           ID-3: /dev/sdc model: Crucial_CT1050MX size: 1050.2GB
           ID-4: /dev/sdd model: KINGSTON_SH100S3 size: 120.0GB
           ID-5: /dev/sde model: KINGSTON_SV300S3 size: 120.0GB
Partition: ID-1: / size: 110G used: 93G (90%) fs: ext4 dev: /dev/sde1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 57.0C mobo: N/A gpu: 0.0:54C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 281 Uptime: 12:39 Memory: 4216.0/32101.8MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56 
```
Zipped video attached :eyes: 
[Screen record from 2019-02-05 20.03.12@2x.mp4.zip](https://github.com/elementary/files/files/2833507/Screen.record.from.2019-02-05.20.03.12%402x.mp4.zip)

**Comment by cmburg** [comment] 2019-02-05 21:37
I have the same issue but it seems to come by when I set colors to folders. 
I also notice a "resize/shift" of the icons when I have closed all tabs and point the mouse into the "folder area".

**Comment by jeremypw** [comment] 2019-02-06 11:15
This is a duplicate of #878 .  A fix for this was merged about 3 days ago but may not have been released yet.  You can work around that bug temporarily by using the "Hide Local Thumbails" option.

**Closed by jeremypw** 2019-02-06 11:15 UTC
Labels: Status: Duplicate
