### ISSUE TITLE
The name of the file and folder label is all white in Dark Variant

### ISSUE THREAD

**Issue by AdsonCicilioti** [elementary/files#976] opened 2019-06-21 23:05 UTC
![image](https://user-images.githubusercontent.com/6278398/59955249-7d823500-945f-11e9-91a0-350607adf4b0.png)

**Comment by jeremypw** [comment] 2019-06-22 15:50
Thanks for the report, it is a duplicate of #937.

**Comment by jeremypw** [comment] 2019-06-22 16:28
Sorry, actually not a duplicate as this refers to untagged files.

It has been recently fixed in master by d471f331824649503c7039160ab508b2e64366ba

**Closed by jeremypw** 2019-06-22 16:28 UTC

**Comment by AdsonCicilioti** [comment] 2019-06-22 21:44
Dear @jeremypw,
This is not duplicate. Those white colors tando in the text as in the background are in everything, even I not applying a label color.

Could not understand?

**Comment by AdsonCicilioti** [comment] 2019-06-22 22:03
But ok.. U've get the lastest connits and tag color is fixed. But when set any colors the name name stay illegible concern #937  issue.

![image](https://user-images.githubusercontent.com/6278398/59969265-f1841200-951f-11e9-9df3-6fc64457f852.png)
No contrast

And extra problem:
Context menu width cut color options.
![image](https://user-images.githubusercontent.com/6278398/59969282-40ca4280-9520-11e9-96d7-90f52becdb5c.png)

**Comment by jeremypw** [comment] 2019-06-23 06:54
@AdsonCicilioti Thanks - I have now pushed a PR to fix #937 and the width issue.
