### ISSUE TITLE
Stopped when I tried to enter in a folder that I don't have permission

### ISSUE THREAD

**Issue by andersrodigrue** [elementary/files#551] opened 2018-07-17 01:04 UTC
Stopped when I tried to enter in a folder that I don't have permission

**Comment by jeremypw** [comment] 2018-07-17 09:56
Please clarify "stopped" - did you mean the application crashed  or something else?

**Comment by andersrodigrue** [comment] 2018-07-17 13:00
Yes, the application crashed. I tried to click on parts of the window and nothing happened. It was like was froze.

**Comment by jeremypw** [comment] 2018-07-17 16:00
OK, technically, this is "hanging" - a crash causes the window to disappear.  Is this reproducible?  If you right click on the folder and inspect the Properties, what are the owner and permissions?.  What view mode does it happen in?  I could not reproduce this by clicking on e.g. system folders owned by root.  Unsetting the read, write and execute permissions on a test folder owned by the user resulted in the message  "This folder does not belong to you - You do not have permission to view this folder" being shown without hanging.  This was using Juno beta (Files version 0.3.6).

**Comment by jeremypw** [comment] 2018-07-17 16:07
Note, there is a known bug that can cause Files to occasionally crash when opening any folder.  A fix for this has been proposed and is awaiting review, but this sounds as if it may be different.  If you are able to run Files under gdb and get a backtrace when you interrupt it while hanging that might help.

**Comment by andersrodigrue** [comment] 2018-07-17 17:43
I was using Files version 0.3.6. I can't reproduce the error (Was the other error fixed?). I went to the file system folder (with my personal user/ without being superuser) and tried to click on a folder when the application crashed.

**Comment by jeremypw** [comment] 2018-07-17 18:05
OK, thanks. The other error's fix is not merged yet. Do you remember which view you were using ie. icon, list or column?  Some bugs depend on exact timing and positioning of clicks and these are hard to diagnose.

**Comment by andersrodigrue** [comment] 2018-07-17 18:38
Was the icon view.

**Comment by jeremypw** [comment] 2018-07-18 08:58
DId Files stop before or after showing the warning message?

**Comment by andersrodigrue** [comment] 2018-07-18 14:06
The warning message wasn't displayed.

**Comment by jeremypw** [comment] 2023-06-25 15:42
Closing as it has not been confirmed for several years and Files has changed substantially.

**Closed by jeremypw** 2023-06-25 15:42 UTC
Labels: Not reproducible
