### ISSUE TITLE
List view expand folder button difficult to click

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1534] opened 2020-12-11 15:36 UTC
## What Happened
The small arrow button to expand the folder contents is far too small to click quickly, and it could do with some more padding

## Image
![files-no-padding](https://user-images.githubusercontent.com/58219504/101922945-aacc2100-3bc6-11eb-8cc6-cc66224363c6.png)

## Expected Behavior
The arrow button has got enough padding to be easily clicked with a trackpad
Maybe it could even have swipe to open/close 👀️ (not sure how difficult it would be to implement, if the entries are gtk containers it shouldn't be impossible).

## Steps to Reproduce

1. Open Files
2. Try quickly clicking the expand folder button with a touchpad

## Platform Information
elementary OS 6 daily

**Comment by hanaral** [comment] 2020-12-11 16:10
> The expanders are drawn by Gtk not Files so I am not sure how to change their padding - maybe something can be done in the elementary stylesheet? Adding padding to the icon render would only increase the active area of the icon, not the expander I think. You can see this by observing where the cursor changes from an arrow (over the expander) to a hand (over the icon) for different icon sizes.

I noticed that the bounds are visible with the cursor, but I think that changing the stylesheet for it might mess with other treeviews that use the same icon (such as code/files/music sidebar)

> As a side note, you can also use the keyboard to expand and collapse the selected row with `<LeftArrow>` and `<RightArrow>`.

I already knew ;) cheers

**Comment by jeremypw** [comment] 2020-12-11 19:33
> ... I think that changing the stylesheet for it might mess with other treeviews that use the same icon (such as code/files/music sidebar)

If it is due to how Gtk draws the expander column then presumably these apps will suffer the same problem?  If they do not then maybe it is something to do with Files code.

**Comment by hanaral** [comment] 2020-12-12 08:40
>> ... I think that changing the stylesheet for it might mess with other treeviews that use the same icon (such as code/files/music sidebar) ...

@jeremypw I was talking about the granite source list, but now that I think about it they probably won’t be affected.

**Comment by andrewdbate** [comment] 2021-12-05 19:16
This is actually due to a bug in the elementary stylesheet. The same issue happens when using Nemo.

The problem is due to the hit region for the separator being to the right of the separator and is on top of the hit region for the arrows used to expand.

**Comment by jeremypw** [comment] 2021-12-06 10:28
Until this improved, note that you can watch the cursor to give feedback when you are in the right position.  It will be an arrow when over the expander.. You can also use the keyboard to expand a selected folder by pressing the right arrow key (left arrow key will then collapse it).

**Comment by jeremypw** [comment] 2024-10-08 12:20
This situation is slightly better than the native TreeView widget used, where you have to click exactly on the expander arrow.  In Files you can click on the white space around the arrow too but altering the width of that appear to be a stylesheet issue so outside the scope of this project.  Dolphin has very nice large areas around the expander but that uses a different toolkit.

I am going to close this as "Out of Scope".

**Closed** 2024-10-08 12:21 UTC
Labels: Status: Out of Scope
