### ISSUE TITLE
Allow starting a new selection when clicking on and dragging a selected text

### ISSUE THREAD

**Issue by undergroundwires** [elementary/files#1957] opened 2021-12-24 21:54 UTC
### What Happened?

Files tries to move the folder.

### Steps to Reproduce

1. Choose a folder
2. F2 to rename
3. Hold down left mouse button to start selection action

### Expected Behavior

Start selecting text from where I start

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2021-12-25 11:48
Clicking outside the rename edit entry should cancel the renaming *and* carry out whatever action the click indicates.  It should only start a move if you click on the icon and you drag the pointer a little while the button is down.  There is a possible argument that no action should be carried out except cancelling the renaming - is that what you mean?

**Comment by undergroundwires** [comment] 2021-12-25 17:13
Hi @jeremypw , thank you for fast response and I'm sorry for bad explanation. Sometimes I think people can read my mind 😀

I first activate rename mode with F2, then try to select the text I want to remove (`delete-this-part`) but it starts dragging the folder. I'm in rename mode, I don't want to move it! It works however if I single click somewhere else in text before doing that as you see in the video:

https://user-images.githubusercontent.com/15555035/147390090-2fe18362-2eb6-44f6-ac4f-2b24d5b2f63f.mp4

It's very unproductive when working with renaming intensively.

Thank you for your great job for elementary and creating such a lovable linux distro with very limited resources.

**Comment by jeremypw** [comment] 2021-12-27 15:13
Ah, OK I see now what you mean. It is the text that moves, not the actual file item.  Dragging the pointer over selected text to move the selected text is actually the behaviour built into a Gtk.Entry  (you can try it in other apps where you have selected text in an entry) .  The problem is that the text to rename is preselected on the assumption that more people want to just start typing to overwrite the original name.  So you have to deselect the text first if you want to select a different part which means single-clicking on the entry first.  The same behaviour occurs in other filemanagers, e.g. Nautilus.   Maybe consider changing the issue to a request to not preselect when renaming?

**Comment by undergroundwires** [comment] 2021-12-27 20:23
I just realize that it does not try to move the folder. But just the text. My bad.

I have no issue with finder preselecting it. But that the next action on drag is dragging the text around rather than starting a new selection.

A  good example is how Nemo handles it. It still preselects but dragging does not try to move around selected text, but just lets you drag into a new selection. 

The intention of start dragging again here I think here is almost always to select a different part, not to move around the text. How many times have you started renaming a file/folder then started dragging its name to drop that text somewhere? Usually we use copy/paste instead of dragging selected texts around after entering to mode, or am I wrong? At least I've never done it nor seen someone doing it. It's additionally secure as by intuition you don't know if if you're dragging a text or a file/folder (what I initially thought when I was creating this issue).

**Comment by undergroundwires** [comment] 2021-12-27 20:25
I just realize that it does not try to move the folder. But just the text. My bad.

I have no issue with finder preselecting it. But that the next action on drag is dragging the text around rather than starting a new selection.

A  good example is how Nemo handles it. It still preselects but dragging does not try to move around selected text, but just lets you drag into a new selection. 

The intention of start dragging again here I think here is almost always to select a different part, not to move around the text. How many times have you started renaming a file/folder then started dragging its name to drop that text somewhere? It can be os-wide behavior and make sense, but just in this case just confusing. Usually we use copy/paste instead of dragging selected texts around after entering to mode. At least I've never done it nor seen someone doing it. By intuition I didn't know I was dragging a text or a file/folder (what I initially thought when I was creating this issue).

**Comment by undergroundwires** [comment] 2021-12-27 20:25
I just realize that it does not try to move the folder. But just the text. My bad.

I have no issue with finder preselecting it. But that the next action on drag is dragging the text around rather than starting a new selection.

A  good example is how Nemo handles it. It still preselects but dragging does not try to move around selected text, but just lets you drag into a new selection. 

The intention of start dragging again here I think here is almost always to select a different part, not to move around the text. How many times have you started renaming a file/folder then started dragging its name to drop that text somewhere? It can be os-wide behavior and make sense, but just in this case just confusing. Usually we use copy/paste instead of dragging selected texts around after entering to mode. At least I've never done it nor seen someone doing it. By intuition I didn't know I was dragging a text or a file/folder (what I initially thought when I was creating this issue).

**Comment by jeremypw** [comment] 2021-12-28 09:42
OK, that makes sense - thanks for updating the description.

**Comment by jeremypw** [comment] 2021-12-29 09:44
I have made a PR that fixes this for Files by unselecting the text as soon as the button is pressed.  Not sure this will work in Gtk4 but we will cross that bridge when we come to it ...

**Comment by danrabbit** [comment] 2022-05-19 15:30
Sorry for the long lead time on responding here. I'm going to close this as "Design Conflict" since overriding this behavior would mean this one specific entry in Files behaves differently than every other entry in every other app. Sorry!

**Closed** 2022-05-19 15:31 UTC
Labels: Status: Design Conflict
