### ISSUE TITLE
White / Light File-Thumbnails are Invisible

### ISSUE THREAD

**Issue by amxmln** [elementary/files#712] opened 2018-10-27 13:09 UTC
Images that are mostly white, especially icons, aren't visible unless selected. This creates a very broken-looking, inconvenient user experience:
![bildschirmfoto von 2018-10-27 15-04-50](https://user-images.githubusercontent.com/15271679/47604402-ae59b980-d9f9-11e8-90db-d471267904e0.png)
![bildschirmfoto von 2018-10-27 15-06-00](https://user-images.githubusercontent.com/15271679/47604412-d6491d00-d9f9-11e8-8d93-506db5672fd0.png)

Perhaps in cases like this there should be some sort of border around the thumbnail? Or a darkened background color? It's a tricky thing to fix, but I believe it would be greatly beneficial if a solution could be found.

Keep up the great work!

**Comment by jeremypw** [comment] 2018-10-28 12:03
I guess an off-white background might be acceptable (perhaps as an option like in Code) but needs the UX-team to alter the style sheet.  Icons that are mostly the same color as the background (whatever it is) are always going to be hard to see. 

I doubt a border would be acceptable.

**Comment by amxmln** [comment] 2018-10-29 10:08
If a border is truly not an option (why not?), then an off-white background is probably going to be the best solution, I think there's much more pure-white out there than, say, a light grey.

**Comment by jeremypw** [comment] 2018-10-29 11:55
You are welcome to submit a mockup of how a border would look in the case shown above.

**Comment by Akryum** [comment] 2019-01-03 18:18
In Windows and MacOS, they chose to use a border shadow:

![windows](https://mspoweruser.com/wp-content/uploads/2016/03/Windows-File-Explorer.jpg)

![macos](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/social/macos-mojave-macbook-finder-social-card.jpg)
(Note the additional inner padding)

Gnome went with a border and inner padding:

![gnome](https://www.gnome.org/wp-content/uploads/2012/09/files-recent.png)

IMO the best looking solution is border-shadow + inner padding

**Comment by jeremypw** [comment] 2019-01-03 18:51
@elementary/ux  Any opinion on this?

**Comment by cassidyjames** [comment] 2019-01-03 21:11
I would not be terribly opposed to looking a subtle border + shadow or something on thumbnails (but not other icons, obviously).

**Comment by Akryum** [comment] 2019-01-03 21:19
The border makes it clear it's a thumbnail with a transparent or white image, and also where you can click with the mouse to open it.

**Comment by Akryum** [comment] 2019-01-03 21:20
Maybe some smart logic could be applied, if the thumbnail is mostly transparent or white, add a checkerboard. 😸

**Comment by jeremypw** [comment] 2019-01-04 10:55
Files code is carrying around a (now empty) file called "thumbnail_frame.png" but this has not been used for many years. There also used to be a function GOF.File.thumbnail_can_frame which stopped icons in certain directory being framed.  Presumably this was discontinued for design reasons. So we need to make sure the frame/border/shadow is sufficiently subtle to be acceptable for general use.

**Comment by Akryum** [comment] 2019-01-04 11:00
But imo it should be visible enough to be useful and make the thumbnail more accessible. 👁

**Comment by jeremypw** [comment] 2019-01-04 11:49
Nemo uses a drop shadow which looks good to me:

Nemo:

![nemo shadow](https://user-images.githubusercontent.com/10513844/50686785-a714e480-1016-11e9-990b-7d1d419b14b5.png)

for comparison Files:

![files no shadow](https://user-images.githubusercontent.com/10513844/50686819-c3b11c80-1016-11e9-94a6-9fc97b781f79.png)

**Comment by jeremypw** [comment] 2019-01-04 11:52
The problem with pale thumbnails is also exacerbated by the fact that Files lightens the items the cursor is hovering. Perhaps this can be tweaked so pale items are not lightened so much.  Or another way of highlighting is used.

**Comment by jeremypw** [comment] 2019-01-04 12:00
I notice that Nemo does not use the shadow in icon folders so the original problem (with folder "Custom Insync Icons") would not necessarily be fixed.  I do not know whether MacOS or Windows treats icon folders differently this way.  Is it desirable?

**Comment by Akryum** [comment] 2019-01-04 12:04
Here is a screenshot of a folder containing logos in Windows 10:

![image](https://user-images.githubusercontent.com/2798204/50687333-2f988280-1021-11e9-9bb6-a4dffb3b4d92.png)

**Comment by jeremypw** [comment] 2019-01-04 16:17
OK, thanks. It looks like Windows always uses the frame then.  I must admit was never sure of what the rationale was of treating icon folders differently.

**Comment by Akryum** [comment] 2019-01-04 17:20
I think every thumbnail should have it. Gnome files doesn't do it for PDF files (see the screenshot in previous posts), which shows the same issue Files currently has.

**Comment by 4jNsY6fCVqZv** [comment] 2019-07-31 08:50
The issue is still relevant.Any idea how to solve it?

**Comment by jeremypw** [comment] 2019-07-31 16:05
Looks like the design team has not decided on a solution yet. I'll ask what they would prefer.

**Comment by danrabbit** [comment] 2019-07-31 16:15
In Photos we add the `checkerboard` and `card` style classes. I think we could do the same here to resolve the issue.

![Screenshot from 2019-07-31 09 15 23@2x](https://user-images.githubusercontent.com/7277719/62229062-c0df9580-b373-11e9-96d0-cd7bf46e8c86.png)

**Comment by jeremypw** [comment] 2019-07-31 16:28
I suspect Photos uses widgets to display the thumbnails which are easier to style.  May not work so easily with a CellRenderer - but I'll see what can be done.

**Comment by cassidyjames** [comment] 2019-07-31 16:39
I agree stylistically with @danrabbit; if we can add the style classes themselves then let's do that, otherwise let's try something that looks similar.

**Comment by jeremypw** [comment] 2019-07-31 17:18
This is what you get when adding those style classes and (re)rendering the background of the cell area before rendering the icon:

![Screenshot from 2019-07-31 18 15 27](https://user-images.githubusercontent.com/10513844/62232989-7c79e700-b3bf-11e9-9d7b-35e282386b3d.png)

**Comment by danrabbit** [comment] 2019-07-31 17:22
Looks like the card class isn't really showing up but I think that checkerboard looks sane to me :)

**Comment by jeremypw** [comment] 2019-07-31 17:23
Mixed items:

![Screenshot from 2019-07-31 18 22 01](https://user-images.githubusercontent.com/10513844/62233286-29546400-b3c0-11e9-81bb-6a42753b9efb.png)

**Comment by fabiozaramella** [comment] 2019-07-31 17:25
Cool, but i agree they will look nicer with .card class (i don't know if this is possible) so that they will look like actual images in a grid instead of floating checkerboard.

**Comment by jeremypw** [comment] 2019-07-31 17:32
CARD class may only work for containers. I tried using render_frame after adding that class to the style context but nothing was visible.

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-01 06:42
Thanks for working on this! And for your ideas.
I ask myself: What does your solutions will look like for PDF's or Open Document file formats?

**Comment by jeremypw** [comment] 2019-08-01 07:11
@4jNsY6fCVqZv At the moment, the checkerboard background is only applied to image files (mimetype "image/*") but that could be extended.

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-01 09:29
@jeremypw That would be wonderful, if checkerboard or card class can be extended in the sense of these file types!
Why does a shadow make sense when displaying thumbnails? That only applies to images, right?

**Comment by jeremypw** [comment] 2019-08-01 11:10
@4jNsY6fCVqZv Whether and to which file types to apply a checkerboard background or shadow or frame etc open for discussion in the PR #1001. Its just a proof of principle at the moment. I am making progress on being able to add a frame or shadow if required.

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-01 13:34
@jeremypw Thank you for working on a PR and for opening a discussion! For me the problem with PDF and Open Document files is intensified by the fact that the whitening effect is intensified again when hoovering over the image preview. Maybe you can incorporate this into your PR as well?

**Comment by jeremypw** [comment] 2019-08-01 14:41
Its probably best to leave that for a different PR.  We need to decide what other visual feedback is appropriate for indicating the hovered file and cursor position. There is already another issue raised about this (#846).

**Comment by jeremypw** [comment] 2019-08-01 16:15
This has now been solved, or at least ameliorated by PR #1003 which was just merged.

**Closed** 2019-08-01 16:21 UTC
Labels: Priority: Wishlist, Status: Confirmed
