### ISSUE TITLE
Keep first item on a folder not "highlighted"

### ISSUE THREAD

**Issue by BenMorant** [elementary/files#2192] opened 2023-05-07 13:33 UTC
### Problem

Hello !
When navigating with pantheon-files on any folder, its first item looks "highlighted", even if not selected / "mouse-hovered".
I don't know if this behaviour is wanted or not.

![Captures d'écran de 2023-05-07 15 19 57](https://user-images.githubusercontent.com/52816705/236680603-d0cc78c2-4ccf-4d74-8804-a43b10eda1fc.png)

![Captures d'écran de 2023-05-07 15 29 36](https://user-images.githubusercontent.com/52816705/236680620-141db3b1-d582-4ac1-a798-171426003b74.png)

### Proposal

The first item of a folder should not be highlighted.

**Comment by jeremypw** [comment] 2023-05-07 22:02
This looks like a duplicate of #552.  Some discussion about this can be found there.  The matter of indicating keyboard focus independent of selection status can perhaps be revisited for the Gtk4 version as the file items are completely recoded there anyway.

**Closed by jeremypw** 2023-05-07 22:02 UTC
