### ISSUE TITLE
Crash when switching view (too fast?)

### ISSUE THREAD

**Issue by davidak** [elementary/files#2075] opened 2022-08-21 18:55 UTC
### What Happened?

I opened my download folder and switched from list view to grid view. it hangs for some seconds and crash then

video: https://youtu.be/3T--z3qY7ok?t=120

### Steps to Reproduce

0. open a folder with thousands of images
1. switch to list view
2. switch to grid view
3. switch back to list view and while it loads, click on the third views icon...

it might help if your ram is 95% filled and the system is swapping

### Expected Behavior

no crash

### OS Version

Other Linux

NixOS 22.05.2397.5c211b47aea

### Software Version

Latest release (I have run all updates)

Files 6.1.4

### Log Output

```
[root@gaming:~]# coredumpctl debug
...
(gdb) bt
#0  0x00007f52d9081dc8 in files_abstract_slot_get_current_slot ()
   from /nix/store/bgdd2rxfgh464nvpzwi7m8k7qqykasnr-elementary-files-6.1.4/lib/libpantheon-files-core.so.6
#1  0x00007f52d908228c in files_abstract_slot_get_directory ()
   from /nix/store/bgdd2rxfgh464nvpzwi7m8k7qqykasnr-elementary-files-6.1.4/lib/libpantheon-files-core.so.6
#2  0x000000000045bbfd in files_icon_view_real_scroll_to_cell ()
#3  0x000000000045bb68 in files_icon_view_real_set_cursor_on_cell ()
#4  0x000000000045ba5c in files_icon_view_real_set_cursor ()
#5  0x000000000044d30c in ____lambda95__gsource_func ()
#6  0x00007f52d8f71d04 in g_main_dispatch (context=0x1b81c00) at ../glib/gmain.c:3417
#7  g_main_context_dispatch (context=0x1b81c00) at ../glib/gmain.c:4135
#8  0x00007f52d8f720a8 in g_main_context_iterate (context=context@entry=0x1b81c00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4211
#9  0x00007f52d8f7215f in g_main_context_iteration (context=context@entry=0x1b81c00, may_block=may_block@entry=1) at ../glib/gmain.c:4276
#10 0x00007f52d8dbb71d in g_application_run (application=0x1b96140, argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2569
#11 0x000000000042f9ff in main ()

```

**Comment by jeremypw** [comment] 2022-08-24 17:38
Possible duplicate of #1983

**Comment by jeremypw** [comment] 2022-08-24 18:12
@davidak  The linked PR solves the issue for me - does it for you?  It could depend on folder size/machine speed etc as it is a race.

**Closed** 2022-08-27 14:33 UTC
Labels: Status: Confirmed
