### ISSUE TITLE
Selecting files is sometimes really hard

### ISSUE THREAD

**Issue by vaclavhlobil** [elementary/files#288] opened 2018-01-12 07:40 UTC
Hello,

sometimes selecting files is a real pain in elementary Files. Although it wants some playing around to invoke this buggy behavior.

In a folder with some content, try to select all the files/folders with Ctrl+A shortcut. Now try to deselect files by click to a blank space around files. And then again, select all the files with Ctrl+A. "Sometimes" you have to repeat Ctrl+A again to select all files, because for the first time nothing will happen.

Then (sometimes) if you have selected all the files in this way, it is impossible to deselect a few files with click to the "checkbox" icon (mouse only), because cursor is changed to a pointer with the mouse over that icon and action is not "active". With click nothing will happen.

To activate this strange behavior you have to play around with selecting files, selecting all the files with Ctrl+A, changing folders etc. It's not a rule, that everytime this happens. I can record a video if it will help.

Thank you.

**Comment by jeremypw** [comment] 2018-01-12 10:25
Thanks for the report. Please could you confirm which version of Files you are running - is it from the stable or daily repository? Does this occurs in IconView or ListView or both?

I can confirm the following part of the issue:
* In ListView select all with Ctrl-A
* Switch to IconView - the selection is reproduced in the new view.
* Have to press Ctrl-A twice to deselect all the files

I have not yet been able to reproduce the other aspects using the latest master of Files.  If you can determine the conditions and a sequence of actions that will *reproducibly* evoke the bug it will be easier to fix.

**Comment by vaclavhlobil** [comment] 2018-01-12 10:53
I have used it in this way only in IconView. It's default updated elementary OS Loki installation with Files 0.3.5. Will try to determine how to reproduce it (but later, sorry).

**Comment by jeremypw** [comment] 2018-01-12 15:37
There have been some commits affecting key and button handling since that release so hopefully that has fixed.  Probably best to raise separate issues re selecting with Ctrl-A and selecting with mouse.

**Comment by jeremypw** [comment] 2018-01-27 17:21
@vaclavhlobil Incidentally, do you use Files in an RTL environment?  There have been some issues with selection using the helper emblems in RTL.  There is a fix now merged but it will not have reached stable version yet.

**Comment by jlnr** [comment] 2018-02-10 11:58
I've just built Files from master and can reproduce this. Open a new window (shows home folder), ctrl+A works, click in white space, next ctrl+A doesn't do anything, next ctrl+A works.

**Comment by jeremypw** [comment] 2018-02-10 13:57
Does the source you built include commit dae8895eeb35dd7c529285dafc564641134986d2?  This refactored the select-all (Ctrl-A) code and should have fixed this problem.  I cannot reproduce it with the current master in either single click or double click mode.
Test carriedout was:
* Show home folder in Icon view
* Press Ctrl-A to select all
* Primary click in white space (deselects all)
* Press Ctrl-A
The second Ctrl-A selected all the items correctly.

**Comment by jlnr** [comment] 2018-02-10 14:44
Hrm, I must have accidentally tried it in a window of the original binary (before your commit). I can't reproduce it anymore, sorry for the confusion.

However, I've noticed a potential regression in the linked commit: Pressing Ctrl-A when all files are selected usually deselects everything, but this doesn't work when there are hidden files in the current directory (because selection size != number of directory entries).

**Comment by jeremypw** [comment] 2018-09-04 12:30
This seems to be fixed now in master. Please re-open if necessary.

**Closed by jeremypw** 2018-09-04 12:30 UTC
